### ISSUE TITLE
[Feature Request] Load Balance

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#10]
HI, I am the author of the "Free Weekend Load Balancer" add-on
[Free Weekend Load Balancer](https://github.com/cjdduarte/Free_Weekend_Load_Balancer)

This addon is based on "Load Balanced Scheduler"
[Load Balanced Scheduler](https://ankiweb.net/shared/info/208879074)

What I liked about this add-on is that it only used FUZZ to balance the days.
That is, if my fuzz is 3 days [-1, 0, 1] it would balance the cards in these 3 days.
if the fuzz is 5 days [-2 -1, 0, 1, 2] it would balance the cards in these 5 days.
And there is no info fuzz, it didn't balance.
Suggestion, leave optional (True or false) the load balancing option.
So that would mitigate something like this:

![image](https://user-images.githubusercontent.com/42243532/216571747-afab71b9-922b-4360-928d-2741982e6b7e.png)

In the long run, he would hate to laugh getting like this.
![image](https://user-images.githubusercontent.com/42243532/216571820-2226290f-ce5f-497a-a0f4-0408b66ce999.png)

**Comment by L-M-Sherlock** [comment]
I am implementing it, but I encounter a problem. The final load is uneven, even if I integrate your code into the rescheduling process.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/32575846/218119215-a0c55a0a-6038-4045-8c8d-9ddc3f30348b.png">

**Comment by L-M-Sherlock** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/32575846/218140703-7f1780b2-c0ed-4112-8fe6-f83f8428476c.png">

It seems to work well!

**Comment by cjdduarte** [comment]
If you're respecting the FUZZ limit, that's right.

Great.

**Comment by L-M-Sherlock** [comment]
Should I add a switch to ask users whether they need load balance?

**Comment by cjdduarte** [comment]
> I am implementing it, but I encounter a problem. The final load is uneven, even if I integrate your code into the rescheduling process.
> 
> <img alt="image" width="1064" src="https://user-images.githubusercontent.com/32575846/218119215-a0c55a0a-6038-4045-8c8d-9ddc3f30348b.png">

It depends on the amount of cards and the "lvl" they are at the moment, it will never be perfect. But what showed above, seems to be expected.

**Comment by cjdduarte** [comment]
> Should I add a switch to ask users whether they need load balance?

I think so.
`const enable_load_balance = true or false;`

**Comment by cjdduarte** [comment]
A doubt: You are implementing only when we answer the card.

Or also here?
![image](https://user-images.githubusercontent.com/42243532/218145387-a65eaf80-d5a6-4ff8-90e9-c5c6ccb264fa.png)

**Comment by L-M-Sherlock** [comment]
> A doubt: You are implementing only when we answer the card.

I could only implement it when rescheduling. Because the scheduler is encapsulated in the Rust backend, I couldn't hack into it.

**Comment by cjdduarte** [comment]
> > A doubt: You are implementing only when we answer the card.
> 
> I could only implement it when rescheduling. Because the scheduler is encapsulated in the Rust backend, I couldn't hack into it.

Entendi. OK.

**Comment by L-M-Sherlock** [comment]
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10712987/fsrs4anki-helper.zip)

Have a try!

PS: Replace `.zip` with `.ankiaddon`.

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/218251618-f9f5e84c-e9dc-4130-9f0d-1d1a81e25ef0.png)

Free weekend is in developing.

**Comment by L-M-Sherlock** [comment]
The latest version: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10713500/fsrs4anki-helper.zip)

**Comment by cjdduarte** [comment]
I'll test it here now.

**Comment by cjdduarte** [comment]
before
![image](https://user-images.githubusercontent.com/42243532/218256353-8fbf286d-f948-4b11-9d32-49db860fbeed.png)

after
![image](https://user-images.githubusercontent.com/42243532/218256583-d29378a7-b6af-4079-87c6-fcb19d7f2502.png)

**Comment by cjdduarte** [comment]
it works.
But that has nothing to do with what you did, because that happened to me yesterday.
he is putting cards like "overdue"

after I optimized my cards.

But this is another subject.

**Comment by L-M-Sherlock** [comment]
Yep, the new interval is likely shorter than the original interval.

**Comment by cjdduarte** [comment]
That high bar is right. they are the new cards that must come back in 1 a day. I.e. It doesn't have FUZZ.
So that's right.

![image](https://user-images.githubusercontent.com/42243532/218256670-f8437fac-5984-4212-b7b8-eb7d2cf3331c.png)

**Comment by L-M-Sherlock** [comment]
Re-run the rescheduling would make it more smooth.

**Comment by cjdduarte** [comment]
> The latest version: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10713500/fsrs4anki-helper.zip)

PERFECT 
![image](https://user-images.githubusercontent.com/42243532/218256879-d8ee2987-c32c-4efc-9eaf-7aecc4b2cfe2.png)

**Comment by cjdduarte** [comment]
A doubt:
every time I activate the rescheduler eme slightly changes the place of the cards. Shouldn't it always be the same?

![image](https://user-images.githubusercontent.com/42243532/218256987-c0b737ca-c01c-4ece-8b0a-fd974c3491ec.png)

**Comment by L-M-Sherlock** [comment]
Oh, the checkbox has a problem. Restart Anki would uncheck them. I fixed it: 
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10713599/fsrs4anki-helper.zip)

**Comment by L-M-Sherlock** [comment]
> every time I trigger the rescheduler, it slightly changes the position cards. Shouldn't it always be the same?

Because the number of due cards per day is modified by load balance. The context of each rescheduling is changed.

**Comment by cjdduarte** [comment]
> > every time I trigger the rescheduler, it slightly changes the position cards. Shouldn't it always be the same?
> 
> Because the number of due cards per day is modified by load balance. The context of each rescheduling is changed.

True.

**Comment by cjdduarte** [comment]
Work. 
For me, you can publish in production.

![image](https://user-images.githubusercontent.com/42243532/218257288-5a0cb95a-2883-4d96-8714-f28479dde735.png)

**Comment by L-M-Sherlock** [comment]
> Work.
> For me, you can publish in production.

Thanks for your test!
