### ISSUE TITLE
Add the option to customize shortcuts

### ISSUE THREAD

**Issue by Luca1152** [open-spaced-repetition/fsrs4anki-helper#104]
Hi! Thanks for this great tool! ❤️ 

I have one suggestion, that would really help my workflow - the ability to change the shortcuts from the addon config. The main reason is because the `CMD+R` shortcut for `Reschedule cards reviewed in the last 7 days` is an especially unfortunate combination in my case. 

This is because when reviewing, I'm sometimes editing notes, which sometimes implies changing text styling. So I end up using `CMD+R` for clearing the style of a selected area quite often (as I'm using color, underline, bold, etc.) - which is now overriden by the addon, now :( (it's triggered both in the Edit menu that appears when pressing `E` while reviewing, and directly in the reviewer, as I'm also using the `Edit Field During Review` addon).

Thanks!

**Comment by akavi1** [comment]
Temporary fix:
open addons, click FSRS4Anki Helper, view files, open  `__init__.py` , find this part, and change the shortcut to whatever you want. Save the file and restart anki.
```

menu_reschedule = build_action(reschedule, _(
    "Reschedule all cards"), "CTRL+SHIFT+R")
add_action_to_gear(reschedule, "Reschedule cards")

menu_reschedule_recent = build_action(
    reschedule_recent, _(f"Reschedule cards reviewed in the last {config.days_to_reschedule} days"), "CTRL+R")
add_action_to_gear(reschedule_recent, "Reschedule cards (recently reviewed)")

```

**Comment by L-M-Sherlock** [comment]
I plan to remove shortcuts.
