### ISSUE TITLE
idk if im doing something wrong 

### ISSUE THREAD

**Issue by QueenEvanescence** [open-spaced-repetition/fsrs4anki-helper#105]
I started a new user profile on anki and setup the whole FSRS feature and opted for the reschedule on sync feature but it always shows as 0 cards rescheduled and actually doesnt rescehdule anything. Then just to test it i clicked on the reschedule all cards (CTRL+ R) option and it rescheduled everything that wasnt being rescheduled 
When i used to use the auto reschedule feature on another user profile it used to work perfectly.
Have i not set something up correctly?

**Comment by L-M-Sherlock** [comment]
CTRL+ R is used to reschedule the cards reviewed recently. Auto-rescheduling is only applied to those cards reviewed in other devices.

**Comment by QueenEvanescence** [comment]
Im so sorry for wasting your time. i hadnt noticed this earlier. Thank you for the response !
