### ISSUE TITLE
OverflowError: Python int too large to convert to C int

### ISSUE THREAD

**Issue by galantra** [open-spaced-repetition/fsrs4anki-helper#106]
# What I did

1. I generated parameters with https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/Expt/new-baseline/experiment/fsrs4anki_optimizer_alpha_parametrized-curve.ipynb
2. I entered them into Anki; FSRS4Anki v3.20.0 Scheduler Qt5
3. I ran Ctrl+Shift+R
4. As soon as I did that, the below error message popped up. The Helper add-on did not schedule any cards.

# The parameters for FSRS

`[1.8776, 1.7955, 1.5418, 0.2136, 1.9132, 0.0135, 7.6606, 0.4994, 1.9491, 3.2514, 0.0269, 0.2933, 0.6814, 1.411, 0.1088, 1.2354, 3.5719, 5.2544, 0.3675]`

`-----suggested retention (experimental): 0.75-----`

# The error message

<details>
<summary>Details</summary>

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.64 (581f82c5) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-05-25 15:26:29

Caught exception:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\759844606\__init__.py", line 46, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did))
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\759844606\__init__.py", line 84, in reschedule_recent
    reschedule(did, recent=True)
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 242, in reschedule
    hard_ivl = fsrs.next_interval(last_s * hard_factor, retention, max_ivl)
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 94, in next_interval
    new_interval = self.apply_fuzz(stability * math.log(retention) / math.log(0.9))
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 81, in apply_fuzz
    due_date = datetime.now() + timedelta(days=day_offset)
OverflowError: Python int too large to convert to C int

</details>

# Files

I don't want to share the note contents, but here are revlog_history.tsv, revlog.csv, evaluation.tsv, prediction.tsv, stability_for_analysis.tsv and expected_time.csv:

[OverflowError.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11573704/OverflowError.zip)

**Comment by L-M-Sherlock** [comment]
> 1. I generated parameters with https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/Expt/new-baseline/experiment/fsrs4anki_optimizer_alpha_parametrized-curve.ipynb

The parameters generated by alpha version are incompatible with the current Helper and Scheduler.

**Comment by galantra** [comment]
Thank you for the answer. So, currently, the alpha is not for use within Anki yet, but for improving the Optimizer. I am going to close the issue.

By the way, I am excited to see you guys working on the Optimizer. Although I am not well-versed in the technical and mathematical aspects, it is great to be able to evaluate the output thanks to section 4 in the Optimizer and to see whether a different approach has brought an improvement.
