### ISSUE TITLE
review cards drastically cut

### ISSUE THREAD

**Issue by kieranlblack** [open-spaced-repetition/fsrs4anki-helper#109]
The merging of the latest PR (#108) seems to have caused some really weird behaviour with my deck. Rescheduling with the cards before the update I see

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/48463323/283c274c-e10d-47ef-8b2d-6e81df1ea539)

whereas rescheduling after I am getting:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/48463323/8df81ddf-aa0d-47e3-b4d3-5cb4458a0297)

I can provide an export of my deck later and settings for more useful debugging. Without having looked at what was changed in too much detail my initial thought is maybe because I use learning steps > 1 day.

**Comment by L-M-Sherlock** [comment]
Do you compare the stats graph?

**Comment by kieranlblack** [comment]
Looking at the stats menu, it looks to me like whole distribution was more or less shifted by one day with some slight fuzz. Maybe there is an erroneous `+1` or `ceil` floating around the code somewhere? I am busy at the moment but should have time later tonight to look in more detail.

**Comment by L-M-Sherlock** [comment]
> Looking at the stats menu, it looks to me like whole distribution was more or less shifted by one day with some slight fuzz. Maybe there is an erroneous `+1` or `ceil` floating around the code somewhere? I am busy at the moment but should have time later tonight to look in more detail.

It's intended. For details, please see this issue: #107

**Comment by kieranlblack** [comment]
我刚刚看了一眼，这行代码好像不对：

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/588fe5b07952da87c84e19f3ea90e8915612feb8/utils.py#L199

应该是：
```python
return math.floor((last_revlog.time - mw.col.sched.day_cutoff) / 86400) + mw.col.sched.today + 1
```

因为你是先除法，再使用`round`，所以rounding的错误就变了更严重，甚至加起来了一整天。

汉语不是我的母语，请原谅错误。

**Comment by L-M-Sherlock** [comment]
Could you check some cards' due date? I need some cases that the rounding is incorrect.

**Comment by L-M-Sherlock** [comment]
<img width="767" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/85c24eb6-392b-4c07-9492-8420a0afc8e7">

c = a + b. Could you provide some cases that the c != a + b?

**Comment by kieranlblack** [comment]
There many such cases of this due to the linear offset coming from the day starts at, for example:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/48463323/14a931b3-8213-466f-b641-d0bddbbc3bc4)

The problem is with the rounding after the linear shift has been removed. We want to make sure we get the day following the day a card was last reviewed. Inserting a `print((last_revlog.time - mw.col.sched.day_cutoff) / 86400)` show us what is going on:
```
1
-4.306898148148148
1
-25.294120370370372
1
-22.33244212962963
1
-6.953912037037037
-3.239525462962963
1
-5.306041666666666
1
```
all of the values are being rounded at the granularity of a whole day, and some in the wrong direction! Take for example the review which occurred `-4.306898148148148` days ago. This means that this review occurred more than 4 days ago, so it occurred in the -5th day. However, this is such that `round(-4.306898148148148) = -4` which is implying that this occurred on the -4th day.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11614661/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/4a1e4d253b4e71368afb76049ea6fcca031d3720

Could you help me test it?

**Comment by kieranlblack** [comment]
I can later tonight. Don't forget right here as well:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/4a1e4d253b4e71368afb76049ea6fcca031d3720/utils.py#L200

**Comment by L-M-Sherlock** [comment]
> I can later tonight. Don't forget right here as well:

Get it. Here is the latest patch:  [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11615093/fsrs4anki-helper.zip)

**Comment by kieranlblack** [comment]
This seems to have fixed things!
