### ISSUE TITLE
[BUG] FSRS helper rescheduled 500+ cards shown as "due today" upon update on 2/7/2023

### ISSUE THREAD

**Issue by connwork** [open-spaced-repetition/fsrs4anki-helper#11]
**Describe the bug**
FSRS helper was used after update on 2/7/2023 to sync a mobile session, and suddenly shows a huge backlog on cards (ie, went from 0 backlog to >500) after using the FSRS scheduler and helper exclusively for scheduling and updating the FSRS helper to the most current version.

**Expected behavior**
Preservation of most of the schedule based on the scheduler and daily use of the FSRS helper after mobile studying

**Additional context**
Why did this update so massively change my card count? Have I been under-studying this whole time due to an error in the FSRS helper?

**Comment by connwork** [comment]
[collection-2023-02-07@10-20-27.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10677278/collection-2023-02-07%4010-20-27.zip)

**Comment by connwork** [comment]
Actually an update on this: Somehow my carefully tuned fsrs config was reset to default? I'm not sure if this was from a backup, sync, the scheduler, or what, but my config was set back to a previous state on sync and I lost all of my deck-specific configs.

**Comment by L-M-Sherlock** [comment]
I found that the 500+ cards are mainly from the deck named "AnKing Overhaul + AnatoKing Tagged for FSM::1 Previous Modules::04 Cardiovascular-Blood", which seemly was applied by other add-on. 

<img width="819" alt="Snipaste_2023-02-08_10-31-40" src="https://user-images.githubusercontent.com/32575846/217413919-54c9d1bb-e9fa-437d-bca5-1b12212c8aa5.png">
<img width="805" alt="Snipaste_2023-02-08_10-32-13" src="https://user-images.githubusercontent.com/32575846/217413928-d5914662-4b76-4ddc-a988-642bfd47f672.png">

**Comment by connwork** [comment]
As per my previous comment, what actually happened is that somehow the entire scheduler was reset in the settings. Maybe this is an anki issue? Free weekends definitely did not do this, as I have been using that for the last few weeks without issue. 

For some reason, anki reset my entire custom scheduler field. I'm not sure why any addon or anki itself would do this, but it is what happened.
