### ISSUE TITLE
[Feature Request] Change the way "Postpone/Advance cards" is done or implement a new feature

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#114]
**Which module is related to your feature request?**
Scheduler and Helper Add-on.

**Is your feature request related to a problem? Please describe.**
Currently, if the user wishes to decrease his workload, he can use "Postpone cards", and enter the requested level of retention, such that cards with retention above that level will be rescheduled. However, it has two significant downsides:
1) The user can't affect how many cards will be rescheduled.
2) If he has different requested R for different decks, this will mess up scheduling.

**Describe the solution you'd like**
Instead of postponing cards according to their retention, I think cards should be postponed according to their interval. Here's a step-by-step description of the new feature:
1) The user presses "Postpone cards" and enters the number of cards he wishes to postpone.
2) All cards in the chosen deck that are due **today** are sorted by interval length (time elapsed since the last review). This means that longer intervals will result in a higher priority when postponing.
The card with the greatest interval length gets postponed by a random number of days (say, between 1 day and max(floor(0.03*interval_length), 1), for example).
The reason why we should prioritize postponing the cards with the longest intervals is because they will be affected relatively less by the same absolute delay than cards with a short interval. Example: suppose one card's last interval was 3 days and it's due today. It gets postponed by 1 day, now the time elapsed since the last review is 4 days instead of 3. That's a 4/3=1.33x increase in interval length! But suppose instead that the interval was 90 days and it got postponed by 1 day. That's a very small increase, just 91/90=1.01x. In other words, postponing cards with long intervals is less detrimental than postponing cards with short intervals, as it has a smaller relative effect on the length of the interval, even if the absolute change (in days) is the same.
In case of a tie (2 cards having the same interval length) D should be used to resolve ties. Lower D = higher priority. For example, if two due cards both have an interval of 20 days but one has D=5 and the other has D=4, the second gets postponed first. And if they have the same interval length and the same D, well, it's time for a random number generator to decide postponing priority.
3) The process is repeated until the desired number of cards is postponed. If the user enters 100, then the top 100 cards with the longest intervals will be postponed by a random number of days, with ties (equal intervals) being resolved according to their D. Again, this should only include cards that are due on the day the user pressed "postpone cards".

This means that the user now has control over how many cards will be postponed, and it won't mess up scheduling when different decks have different requested R.
The issue is that this could affect cards that are already overdue (weren't reviewed in time), and without some kind of extra stopping mechanism, this could be used to keep postponing the same overdue cards, making them even more overdue each time. I don't know how to solve this problem, hopefully you will have an idea. Maybe tag cards as "postponed" (and remove the tag later once the card is reviewed), and if a card already has that tag it won't be included in the postponing queue?
The same algorithm, with a few changes, can be applied to advancing cards, too.

**Additional context**
Postponing cards shouldn't be abused too much. If the user has to postpone cards often, that means they need to learn fewer new cards, set their target retention lower, or find some other way to decrease their workload. But postponing can still be useful as a short-term solution, and we need to ensure that it does as little harm to learning as possible. I believe that this solution is superior to postponing based on retention rate. If you do not wish to change how postpone cards works, you can implement this as a separate feature and call it "Mercy". I believe that this approach is superior to the way postponing currently works, and instead of implementing it as a new feature you should replace the existing "Postpone cards".

**Comment by L-M-Sherlock** [comment]
> 2\. All cards in the chosen deck that are due **today** are sorted by interval length (time elapsed since the last review). This means that longer intervals will result in a higher priority when postponing.

What about the overdue cards?

**Comment by L-M-Sherlock** [comment]
What if the user needs to postpone the backlog?

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11667393/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/2f946dc967947fac953b05bfbe38d78cdf0c60ff
I implemented a demo patch.

**Comment by L-M-Sherlock** [comment]
Those cards whose retention is lower than `requested retention - 0.01` will be skipped.

**Comment by Expertium** [comment]
That will work if it checks requested R for all subjects within a deck. If it doesn't, then we run into the same issue - subdecks with different requested R all being posptponed according to a single value of R.
If a deck had 2 subdecks, and one has, for example, requested R=95%, and the other subdeck has R=90%, then either your code has to go through every subdeck and check requested R, or it has to not rely on R at all, which is why I proposed this new feature. That, and extra control over the number of posptponed cards.

**Comment by L-M-Sherlock** [comment]
> That will work if it checks requested R for all subdecks within a deck.

It does. It reads the custom scheduling code and extracts the requested retention from the config.

**Comment by L-M-Sherlock** [comment]
> That's good. So, do you think we should allow the user to set priority for decks in a menu? I think that would be neat. That way the less important material will be postponed first.

How to set priority for decks in a menu? Could you draw a GUI draft for it?

**Comment by Expertium** [comment]
I'm not at home right now, but I think there are 2 ways of doing this:
1) Add "Set deck priority" to the same menu that has "Postpone cards" and "Advance cards", the one that appears when you click the deck icon. This sets priority for this one deck (and automatically applies it to subdecks within it)
2) Add a new option to Tools, call it "Deck priorities", for example. It will open a list that would look like this:
```
Deck_One: 1
Deck_Two: 1
Deck_Three: 1
```
Where numbers are priorities (greater number = higher importance). And then the user can modify them.
These two approaches can be combined.

**Comment by L-M-Sherlock** [comment]
I think this `priority` will be implemented later. There is still another important problem need to solve. What if there are not enough cards postponed? For example, the cards are extremely overdue, and their retention is lower than the requested retention - 0.01 (or some other value). The user inputs 100, but there are only X (X < 100) cards could be postponed.

**Comment by L-M-Sherlock** [comment]
By the way, to sort cards by `relative_overdueness` is better than `interval`.

**Comment by Expertium** [comment]
> What if there are not enough cards postponed? For example, the cards are extremely overdue, and their retention is lower than the requested retention - 0.01 (or some other value). The user inputs 100, but there are only X (X < 100) cards could be postponed.

Then only X cards will be postponed. Either that, or keep track of which cards got postponed before using flags or any other method, to ensure that the user cannot postpone the same card twice without reviewing it in-between.

**Comment by L-M-Sherlock** [comment]
> Then only X cards will be postponed.

I think it would confuse the user.

Perhaps we could allow users to postpone an arbitrary number of cards, commencing with those least overdue, and prioritizing the deferral of cards with longer intervals. Ultimately, we would alert users to the expected retention rate of the postponed cards.

**Comment by Expertium** [comment]
> commencing with those least overdue, and prioritizing the deferral of cards with longer intervals.

So sort by relative overdueness first, and then sort by interval length, right?

**Comment by Expertium** [comment]
I wish we could make a multi-criteria using interval length, overdueness, D and time investment (total amount of time spent reviewing this card), but it would be very difficult to balance the contribution of each variable.

**Comment by L-M-Sherlock** [comment]
As a developer, I believe we shouldn't impose restrictions on the postponement feature. It is the user's responsibility to avoid abuse. However, I shall fulfill my obligation to inform.

> So sort by relative overdueness first, and then sort by interval length, right?

Yep.

> I wish we could make a multi-criteria heuristic using interval length, overdueness, D and time investment (total amount of time spent reviewing this card), but it would be very difficult to balance the contribution of each variable.

It will make the query of database more complex. I want to implement a simple version first.

**Comment by Expertium** [comment]
Ok, then implement the simple version. Sort by relative overdueness (higher = lower in the postponing queue), then by interval length (higher = higher in the postponing queue).

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11673737/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/5dce135fed0ea6567d9a26e3575d62a27ae5d1a1

**Comment by Expertium** [comment]
1) I think it should display how many cards are eligible for dispersal.
2) I don't think it's necessary to tell the user how long the new interval will be, remove that. And the part about retention can be simplified to something like "It skips cards whose retention is lower than requested" (btw, we still need to deal with the recall vs retention naming convention issue).
3) Include a warning: "**Warning!** Each time you use Postpone or Advance, you depart from optimal scheduling! Using this feature often is not recommended.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/968226af-b8eb-450b-916e-ba9a6b570d10)

Also, unrelated to the current issue, but I changed my mind about "Disperse siblings", I don't think it's necessary to have a button for that for each deck. As long as siblings are dispersed automatically when Anki starts and when the user syncs his collection, it should be fine.

**Comment by Expertium** [comment]
Wait, if it skips cards with R < requested R, doesn't that lead to the problem you mentioned [here](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/114#issuecomment-1579838419)? With X being less than the total number of cards due today.

**Comment by L-M-Sherlock** [comment]
> Wait, if it skips cards with R < requested R, doesn't that lead to the problem you mentioned [here](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/114#issuecomment-1579838419)? With X being less than the total number of cards due today.

I haven't updated the information in the message box. And I have rewritten all code in the `postpone` just now. The old code would postpone cards deck by deck, which messed up the sorting condition.

**Comment by L-M-Sherlock** [comment]
And I encounter a new problem. If we set the `new_ivl = elapsed_days * 1.05`, some cards will be postponed too long. If we set `new_ivl = old_ivl * 1.05`, some cards would still be due today.

**Comment by Expertium** [comment]
> And I encounter a new problem. If we set the `new_ivl = elapsed_days * 1.05`, some cards will be postponed too long. If we set `new_ivl = old_ivl * 1.05`, some cards would still be due today.

How about this?
`new_ivl = max(old_ivl + 1, min(old_ivl * 1.05, elapsed_days * 1.05))`
This way new new_ivl is at least 1 day longer than before whiel at the same time the card isn't postponed for too long.

**Comment by L-M-Sherlock** [comment]
> How about this?
> new_ivl = max(old_ivl + 1, min(old_ivl * 1.05, elapsed_days * 1.05))
> This way new new_ivl is at least 1 day longer than before while at the same time the card isn't postponed for too long.

The elapsed_days is always greater than old_ivl for due cards. So min(old_ivl * 1.05, elapsed_days * 1.05) is always old_ivl * 1.05.

**Comment by Expertium** [comment]
Would `new_ivl = max(old_ivl + 1, old_ivl * 1.05)` work?

**Comment by L-M-Sherlock** [comment]
For example, suppose today is 2023-06-07, and a card is due in 2023-06-05. Its `old_ivl` is 5 days, and its `elapsed_days` is 7 days. new_ivl = max(elapsed_days + 1, old_ivl * 1.05) = max(8, 5.25), so it will be postpone to 2023-06-08.

But when the backlog is large and many cards has been overdue, it will postpone most cards to the next day, and form a new backlog.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/c404f4c1-aa81-47d6-8a4e-6b36edd9d40f)

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11675988/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/a666a43bbbc651b351c36e233d01fc2c6fb49518

You can test it for yourself.

**Comment by Expertium** [comment]
Well, damn. Then I guess let's use elapsed_days * 1.05. Do you have an idea for how to keep track of postponing to at least prevent "double postponing", aka the same card being postponed twice without a review in between? Using flags, for example.

**Comment by Expertium** [comment]
After thinking about it, I realized that it's impossible to solve both problems:
1) X cards available to be postponed < total number of due cards today
2) "Double postponing"
If we make it so that X is always equal to the total number of due cards today, then that will allow double postponing (and triple/quadruple/infinite postponing of the same card). And if we forbid double postponing, it will lead to X < total number of due cards today. So we have to accept one of these downsides.

**Comment by L-M-Sherlock** [comment]
> Well, damn. Then I guess let's use elapsed_days * 1.05. Do you have an idea for how to keep track of postponing to at least prevent "double postponing", aka the same card being postponed twice without a review in between? Using flags, for example.

It's unlikely to postpone the same card twice. Because I use a new condition to sort cards.

```
    # x[0]: cid
    # x[1]: did
    # x[2]: interval
    # x[3]: stability
    # x[4]: elapsed days
    # x[5]: requested retention
    # x[6]: current retention
    cards = map(lambda x: (x + [did_to_deck_parameters[x[1]]["r"], math.pow(0.9, x[4]/x[3])]), cards)
    cards = filter(lambda x: x[3] is not None, cards)
    # sort by requested retention - current retention, -interval (ascending)
    cards = sorted(cards, key=lambda x: (x[5] - x[6], -x[2]))
```

When a card is postponed, its `requested retention - current retention` will increase, so this card will be sorted to the end of the queue in the next postpone.

**Comment by L-M-Sherlock** [comment]
> Well, damn. Then I guess let's use elapsed_days * 1.05

Oh, I have a new idea. There is an inequality: `ivl * 1.05 < ivl * 1.05 + delay < (ivl + delay) * 1.05`. We can choose `1.05 + delay` as the new interval.

**Comment by Expertium** [comment]
Will you add fuzz to it?

**Comment by L-M-Sherlock** [comment]
> Will you add fuzz to it?

No yet. Should we add fuzz to it?

**Comment by Expertium** [comment]
I think so. It will spread reviews more evenly, balancing the load.
Btw, don't forget my suggestions here: 

> * It should display how many cards are eligible for dispersal.
> * I don't think it's necessary to tell the user how long the new interval will be, remove that. And the part about retention can be simplified to something like "It skips cards whose retention is lower than requested" (btw, we still need to deal with the recall vs retention naming convention issue).
> * Include a warning: "**Warning!** Each time you use Postpone or Advance, you depart from optimal scheduling! Using this feature often is not recommended."

**Comment by L-M-Sherlock** [comment]
> * It should display how many cards are eligible for dispersal.

What does it mean? I think the all due cards are eligible for dispersal.

> * Include a warning: "**Warning!** Each time you use Postpone or Advance, you depart from optimal scheduling! Using this feature often is not recommended."

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/540d22f6-eb4f-485d-bf44-49c6b89aa734)

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11676168/fsrs4anki-helper.zip)

**Comment by Expertium** [comment]
> What does it mean? I think the all due cards are eligible for dispersal.

If we allow double postponing, then it's simply the number of cards due today. If we don't allow it, then it can be lower.

**Comment by Expertium** [comment]
Minor nitpick, but change "Only affect cards scheduled by" to "This feature only affects cards scheduled by".

**Comment by L-M-Sherlock** [comment]
> I tried it and it doesn't postpone all cards that are due today when I enter the number of due cards

I'm fixing it.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11676605/fsrs4anki-helper.zip)

It works well for me.

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/7bc8f60c-9e26-42df-941b-32de3b47ebca)
It leaves 1 card in some of my decks. Also, perhaps we should reschedule cards in the "learning" phase as well?

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/bdc3ff7e-1047-4eab-a264-42ac3447c6a3)
Here is one of them

**Comment by L-M-Sherlock** [comment]
Weird. Could you share this card with me? I need to check the database.

**Comment by Expertium** [comment]
Here are 5 of them
[Test.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11677063/Test.zip)

**Comment by L-M-Sherlock** [comment]
I can't reproduce it. Is it severe?

**Comment by Expertium** [comment]
It only affects a few cards, so it's not severe. Still, it would be better if it was fixed at some point.
I suggest adding fuzz. Also, will you implement [deck priority](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/114#issuecomment-1579194608) now or will you do something else right now?

**Comment by L-M-Sherlock** [comment]
OK. I will release it soon. Or change the `advance card` feature also?



> I suggest adding fuzz.

The original interval has fuzz. Is it meaningful to add fuzz to the postpone?

**Comment by L-M-Sherlock** [comment]
> Also, will you implement [deck priority](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/114#issuecomment-1579194608) now or will you do something else right now?

I think it is better to set priority in the deck config. And it could be used by more add-ons.

**Comment by Expertium** [comment]
> Or change the `advance card` feature also?

About that. Originally, I thought that advance can be easily done after we implement postpone - just run the same sorting algorithm, but in reverse (so if previously you sorted intervals in descending order, for example, now you have to sort them in ascending order). But there is a caveat. For postponing we only need to consider cards that are due today. For advancing we might consider cards that are due tomorrow, or tomorrow + the day after tomorrow, or tomorrow + 2 days after, etc. So it's not clear how advancing should be implemented.

> The original interval has fuzz. Is it meaningful to add fuzz to the postpone?

It's just to spread cards out more evenly so that all future reviews won't happen on the same day. So the same reasoning as to why we are using fuzz in the first place.

**Comment by L-M-Sherlock** [comment]
> For advancing we might consider cards that are due tomorrow, or tomorrow + the day after tomorrow, or tomorrow + 2 days after

They all are the undue cards. It is easy to filter them via `due > today`.

**Comment by Expertium** [comment]
I don't think there is a reason to open a new issue. Both Advance and Postpone are closely related.
So do you think that advancing should involve all undue cards?

**Comment by Expertium** [comment]
Good, then implement advance and that's it, unless you plan to implement priority as well.

> I think it is better to set priority in the deck config. And it could be used by more add-ons.

I'm not sure what you mean. Can you explain what it will look like?

**Comment by L-M-Sherlock** [comment]
<img width="667" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/c08ef44c-04a7-426f-91b2-4f07f44f83ef">
<img width="400" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/3c54aeb1-b696-46f2-bf17-246e1cc6c5b5">

Maybe we can save the priority in the deck's description.

**Comment by Expertium** [comment]
I think adding a menu here
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/0016a14c-705b-4e5f-bbb8-155d0d33e2f9)
is better because you can add verification to ensure that the user has entered a positive integer, and not "-1", or "0.1", or "sa;jiciowehfryhbv:". In the description window, the user can just type whatever he wants.
Alternatively, you could make a GUI where user can adjust priority like this, but that's too much work.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/78e5571a-67d9-4c16-8f99-fbaf4156a9d2)

Btw, remove Disperse Siblings. I mentioned this before, but as long as siblings are dispersed automatically on sync and on Anki startup, it should be fine. I know I was the one who requested that button, but I changed my mind.

**Comment by user1823** [comment]
> > * Include a warning: "**Warning!** Each time you use Postpone or Advance, you depart from optimal scheduling! Using this feature often is not recommended."
> 
> ![image](https://user-images.githubusercontent.com/32575846/244026286-540d22f6-eb4f-485d-bf44-49c6b89aa734.png)

@L-M-Sherlock, I think that any warning should be made prominent. I recommend using a red font color and a bold font for the "Warning!" part (but not for the whole sentence).

**Comment by L-M-Sherlock** [comment]
> I think that any warning should be made prominent. I recommend using a red font color and a bold font for the "Warning!" part (but not for the whole sentence).

Anki doesn't support this feature. I can't add any style to the text.

**Comment by L-M-Sherlock** [comment]
I have to re-write the wiki and README. Any idea? I'm not good at introducing my work.

**Comment by user1823** [comment]
@L-M-Sherlock, in my opinion, you should remove the asterisks (*) that you added recently around the "Warning!". They look odd.

Also, I think that @Expertium suggested to remove the Disperse Siblings button from the Deck gear and not from the main menu. In my opinion, it is still useful after manually rescheduling the cards (such as after updating the parameters).

**Comment by Expertium** [comment]
> Also, I think that @Expertium suggested to remove the Disperse Siblings button from the Deck gear and not from the main menu. In my opinion, it is still useful after manually rescheduling the cards (such as after updating the parameters).

Correct. My bad, I didn't explain it clearly.

**Comment by L-M-Sherlock** [comment]
> disperse siblings is on by default and it's impossible to turn it off, right?

No. The current implementation will ask the user whether disperse siblings after auto-rescheduling. Because I think this feature is still experimental.

**Comment by Expertium** [comment]
Ah, ok. I couldn't find it in the Tools, so I thought it's impossible to turn it off.

**Comment by Expertium** [comment]
See my comment above, about Disperse Siblings option (on/off). Other than that and priority, no, I don't have anything else to add.

**Comment by user1823** [comment]
> I have to re-write the wiki and README. Any idea? I'm not good at introducing my work.

In the README, you can say:

> These options can be used to postpone or advance a selected number of cards. Postpone is useful to deal with a backlog. Advance is useful to review your cards before a large exam or before going on a vacation. Remember that every time you use Postpone or Advance, you depart from the optimal scheduling. So, using this feature often is not recommended.

For the Wiki, @Expertium might be able to help you better because I don't completely understand how this new feature works.

**Comment by L-M-Sherlock** [comment]
> See my comment above, about Disperse Siblings option (on/off).

It is not a switch. It is like Advance & Postpone & Rescheduling.

**Comment by Expertium** [comment]
I'm currently making an image that explains a bunch of stuff, give me some time.

> It is not a switch. It is like Advance & Postpone & Rescheduling.

But it should be. It should either be on for all decks or off for all decks, and work after each sync. I thought that's how it works.

**Comment by L-M-Sherlock** [comment]
> I suggest bringing the input box between "Advance {n} undue cards" and "This feature only affects..."

Anki doesn't support it, too. I only use the basic tool provided by the lib of Anki.

**Comment by user1823** [comment]
Just two minor things and then we are good to go.
- In the Postpone/Advance options, remove the newly added "the" before FSRS4Anki because the "the" should be used before "FSRS4Anki Helper" (which is why I suggested to add it) but not before just "FSRS4Anki".
To make it clear, I want that line to read: "This feature only affects the cards that have been scheduled by FSRS4Anki."
- I don't see a new option in the config to control whether auto-disperse is enabled or not.

**Comment by L-M-Sherlock** [comment]
> I don't see a new option in the config to control whether auto-disperse is enabled or not.

It's always enabled after auto-rescheduling now.

**Comment by Expertium** [comment]
@L-M-Sherlock I made this table, you can add it to the wiki
@user1823 feel free to point out if I made any spelling mistakes or if something should be rephrased
![Description of features](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/3264643e-a088-4f09-bba8-b9042ea76110)

**Comment by L-M-Sherlock** [comment]
> I made this table, you can add it to the wiki
> @user1823 feel free to point out if I made any spelling mistakes or if something should be rephrased

Could you provide the plain text? I could add the table with markdown format.

**Comment by Expertium** [comment]
Feature name

How does it work?

When should I use it?

Postpone

Increases the intervals of cards that are due today based on deck priority, current and requested R, relative overdueness, and interval length in a way that minimizes damage to long-term learning.

When you are dealing with a large number of reviews after taking a break from Anki.

Advance

Decreases the intervals of undue cards based on deck priority, current and requested R, relative overdueness, and interval length in a way that minimizes damage to long-term learning.

When you want to review your material ahead of time, for example before a test.

Free Days

After the optimal interval is calculated, it is slightly adjusted to change due date.

If you don't want to study on some days of the week, for example on Sundays.

Disperse Siblings

Siblings are cards generated from the same note. Their intervals are adjusted to spread them further apart from each other.

Always. This feature increases the spacing effect; disabling it will only decrease the efficiency of spaced repetition.

Load Balancing

After the optimal interval is calculated, it is adjusted by a random amount to make
the distribution of reviews over time more uniform.

Always. This feature makes your workload (reviews/day) more consistent.

**Comment by user1823** [comment]
> > I don't see a new option in the config to control whether auto-disperse is enabled or not.
> 
> It's always enabled after auto-rescheduling now.

But, there should be an option to control this feature, even if the feature is turned on by default.

**Comment by L-M-Sherlock** [comment]
Final patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11680923/fsrs4anki-helper.zip)
Just test for debugging. Any issue about the improvement in `disperse` will be discussed in a new issue.

**Comment by L-M-Sherlock** [comment]
> EDIT: actually, I'm not sure if it's a bug.

It's not a bug.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/62fecc64b15d0391bf23bfc06d06baefcc332b6d/postpone.py#L91-L99

The min retention is calculated by the new interval. So it is the retention in the future.

**Comment by L-M-Sherlock** [comment]
> To be honest, I don't fully understand how this sorting works.

This sorting is relied on the difference between the current retention and the requested retention. Those cards with a low current retention or a high requested retention will be sorted to the end of queue.

**Comment by Expertium** [comment]
By the way, when I made [this](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/114#issuecomment-1580948416) example of a GUI, I forgot that it must allow users to assign equal priorities to different decks and that all priorities must be equal by default. Keep that in mind.

**Comment by user1823** [comment]
I think that we should display the number of cards that can be postponed/advanced relatively safely.

In my opinion, for postpone, these cards can be defined as the cards for which `current retention > requestRetention ^ 1.15`

Here, the 1.15 is the twice of the average delay applied to the cards by the postpone function. 

You can add this to the Postpone dialog box as:
"For this deck, it is not advisable to postpone more than x cards."

For advance, I think we should use the cards for which `current retention < requestRetention ^ 0.87`

Here, the 0.87 is just the reciprocal of 1.15.

**Comment by Expertium** [comment]
No, let's keep the current sorting algorithm. All I want is just to see how many cards can be advanced ot postponed displayed in the menu.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/e73cfe04-c746-4379-818b-d71d9eee46dc)

**Comment by user1823** [comment]
I didn't propose any change to the sorting algorithm. I just provided a logic to calculate the number of cards that can be safely postponed/advanced.

**Comment by Expertium** [comment]
But add cards that are not in the (re)learning stage should be eligible.

**Comment by user1823** [comment]
@L-M-Sherlock, what do you think about https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/114#issuecomment-1582507214?

Also, I would like you to replace `requested retention - current retention` in the sorting for postpone with `log(current retention) / log (request retention)`. This logic would result in better sorting when cards have different request retentions, keeping in mind the exponential nature of the forgetting curve.

Similarly, I would like you to replace `current retention - request retention` in the sorting for advance with `log(request retention) / log (current retention)`.
