### ISSUE TITLE
[BUG] An error when using the new experimental version of Helper Add-on

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#115]
**Describe the bug**
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/963c2e02-2838-402b-b543-d01845b02af0)

**To Reproduce**
1. Download 
[fsrs4anki-helper (3).zip](https://github.com/open-spaced-repetition/fsrs4anki/files/11681052/fsrs4anki-helper.3.zip)
and replace files in the add-on folder with the new files
2. Restart Anki
3. See error

**Environment**
 - Anki version: ⁨2.1.64
 - OS: Windows 10
 - Scheduler version: v3.15.1

**Additional context**
I tried deleting all files in the add-on folder and pasting new files into an empty folder, it didn't help.

**Comment by Expertium** [comment]
It works, but there is one minor problem - the name of the add-on isn't displayed properly.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/6b43d386-7e40-4807-b346-24de20926a4f)

**Comment by L-M-Sherlock** [comment]
OK. I fixed and released it. The name is displayed properly now.

**Comment by Expertium** [comment]
Nice!
