### ISSUE TITLE
[Feature Request] Improve the sorting condition in postpone/advance

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#118]
Also, I would like you to replace `requested retention - current retention` in the sorting for postpone with `log(current retention) / log (request retention)`. This logic would result in better sorting when cards have different request retentions, keeping in mind the exponential nature of the forgetting curve.

Similarly, I would like you to replace `current retention - request retention` in the sorting for advance with `log(request retention) / log (current retention)`.

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/114#issuecomment-1582536568_

**Comment by user1823** [comment]
> This suggestion works for the exponential curve, but in the future we will most likely use power curve as it gives better results.

We can again change it in the future when we start using a power curve. For now, I think that we use the exponential forgetting curve because it is still the default for the scheduler.
