### ISSUE TITLE
[Feature Request] Make it easier to access `Reschedule all cards` functionality in helper

### ISSUE THREAD

**Issue by artjomsR** [open-spaced-repetition/fsrs4anki-helper#12]
**Which module is related to your feature request?**
Helper

**Is your feature request related to a problem? Please describe.**
I'm syncing cards between Desktop and iOS Anki and the mobile version messes up the intervals. As I reschedule them via the Desktop app helper, it gets tedious to select the option with the mouse. You can't use the Alt shortcut either because no letters are underlined for `Reschedule all cards`
![image](https://user-images.githubusercontent.com/6875790/217604899-86735f2a-f7f1-4e8a-8145-9de6f29e5be3.png)

**Proposed solutions**
It would be great to add shortcuts for quick access.

Even better, it would be better to have an option to do such rescheduling automatically when opening the app

**Comment by L-M-Sherlock** [comment]
I have added the shortcut `Ctrl+R` to`Reschedule all cards`.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/32575846/217790967-e9fbc27d-25e4-445d-8019-9c413465502f.png">

https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/d8e675ca8babf24b75f3cf857ef443ce0b5bf94d
