### ISSUE TITLE
快捷键失效

### ISSUE THREAD

**Issue by xjqm-tao** [open-spaced-repetition/fsrs4anki-helper#124]
2023-06-10的版本，Ctrl+R重排快捷键失效了。
版本信息：    
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Windows-10-10.0.19041
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-06-11 22:50:37
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiWebView Inspector ['31746032', 2022-04-09T03:44, 'None', '']
    BetterSearch ['1052724801', 2023-06-11T05:51, 'None', '']
    FSRS4Anki Helper ['759844606', 2023-06-09T23:54, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1052724801 1374772155 31746032 759844606
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by L-M-Sherlock** [comment]
并不是失效了，而是移除了。现在有了auto-reschedule 后，不需要频繁进行 reschedule，所以移除了该快捷键。

**Comment by xjqm-tao** [comment]
> 

哦，感谢

**Comment by xjqm-tao** [comment]
> 

哦，感谢
