### ISSUE TITLE
[Feature Request] Add fuzz support to FSRS Helper

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#13]
Currently FSRS helper doesn't support fuzz as informed by @L-M-Sherlock 
in https://github.com/open-spaced-repetition/fsrs4anki/issues/145#issuecomment-1424427238.

I suggest that fuzz should be added to FSRS helper because it would be needed in these two scenarios:
- Rescheduling cards studied using standard Anki algorithm before switching to FSRS
- Rescheduling cards studied using AnkiDroid and then synced to Anki Desktop

Without fuzz being implemented, the helper would cause cards to stick together.

**Comment by galantra** [comment]
3rd scenario:

Rescheduling cards with new `var w` or `let requestRetention` after the using the optimizer for the first or any subsequent time.
