### ISSUE TITLE
Styling of FSRS Stats & Interpretation

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#134]
1. Currently, the values in FSRS stats are centre-aligned. This is inconsistent with the Anki stats. So, I think that these should be made left-aligned to make the styling of the stats more consistent with Anki.
The main reason for asking this is that the value of the burden looks out of place in the current version (see the screenshot below). 
<img width="429" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/751a2f15-5da7-4c76-9f92-c270ca334136">

For comparison, refer to the following screenshot of Anki stats:
<img width="515" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/8142967f-da8d-479b-a7c8-72f4bd04b98e">

2. Currently, the interpretation section is somewhat hard to read. This could probably be made better by making the terms (e.g. "Average retention:") bold.

By the way, is it possible to merge commits into the main branch without immediately pushing the changes to AnkiWeb? If it is possible, please use this approach for any minor changes you make to the add-on (such as this one).

I am asking this because after every update, I have to set the values in the config file again. If the add-on is updated less frequently, the users won't need to reconfigure their config files that frequently.

**Comment by L-M-Sherlock** [comment]
<img width="750" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/a0e2369c-dea3-44e9-bc51-5659040d75a6">

**Comment by user1823** [comment]
It looks better.

However, you can make the first column right-aligned again, which is consistent with Anki stats (new stats page). But, I don't have a very strong opinion on it. Do as you deem it fit.

Screenshot of new Anki stats:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/8c9ecd76-2365-4e9d-9159-b42c90fe586d)
