### ISSUE TITLE
Add distribution of difficulty to FSRS stats

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#135]
Idea for the add-on stats: distribution of difficulty.
Like this (the numbers are random, it's just an example):
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/7319276c-7293-43d9-8285-353f7c52a6b6)

_Originally posted by @Expertium in https://github.com/open-spaced-repetition/fsrs4anki/issues/264#issuecomment-1556022827_

**Comment by Expertium** [comment]
Last time Sherlock said that he doesn't have a lot of experience with plotting and displaying charts in Anki stats. Perhaps code from [True Retention](https://ankiweb.net/shared/info/613684242) or a similar add-on could hel?

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/1abf4b44-7411-4862-88d8-85d0f6f2a207)

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11789014/fsrs4anki-helper.zip)

**Comment by Expertium** [comment]
Dark blue on a dark background is a bit unpleasant for the eyes, maybe change the color of the bars?

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/37b42ee3-2d38-45d9-a117-985185e7268a)
The last bar is weirdly cut off. The color looks good.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/8b68f0bc-be9c-4d08-b9cf-325230b8324a)

If there are not other problems, I will merge this branch.

**Comment by Expertium** [comment]
Wait, I have one final suggestion. Add the following text below the chart

> Lower number = less difficult (easier), higher number = more difficult (harder)
