### ISSUE TITLE
Reschedule bug due date?

### ISSUE THREAD

**Issue by jcznk** [open-spaced-repetition/fsrs4anki-helper#137]
https://forums.ankiweb.net/t/how-to-use-the-next-generation-spaced-repetition-algorithm-fsrs-on-anki/25415/167?u=jcznk

**Comment by L-M-Sherlock** [comment]
Do you reschedule the card with the latest helper add-on and get the same abnormal result?

**Comment by jcznk** [comment]
Yes! Here are my steps

0. Make sure my only add-on is the latest FSRS helper (I copied the content of the zip file into a new addons21 folder)
1. Create a filtered deck with the Search filter a&e, so that only the 2 sample cards are included
2. Run the rescheduler on the filtered deck (by clicking on the cogwheel icon -> reschedule cards)
3. Do not study the cards and empty the filtered deck

Here are the due dates

Card1 before rescheduling: 2023-06-28
Card2 before rescheduling: 2024-11-06

Card1 after rescheduling, before emptying: 2023-05-01
Card2 after rescheduling, before emptying: 2024-09-09

Card1 after rescheduling, after emptying: 1749-08-09
Card2 after rescheduling, after emptying: 2024-09-09

**Comment by L-M-Sherlock** [comment]
<img width="667" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/5626c518-9994-4ef2-96c7-4f4b56c35d2f">

Weird. I try to follow your steps. But there is zero card rescheduled.

**Comment by L-M-Sherlock** [comment]
Could you update the add-on via this button: 

<img width="544" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/6a7a620a-b721-4054-a6a8-6107b60fd8ef">

**Comment by L-M-Sherlock** [comment]
<img width="848" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/c3baab91-9774-49e4-aaea-f6a7191c154a">

<img width="841" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/d15e5013-7420-4d7a-8bfe-f976e93563a8">

<img width="841" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/55c5467a-6a64-46b0-828e-7da85e66dc06">

<img width="857" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/44075b83-52c2-4cd4-9869-205d2572c8a5">

Some weird things happened. I'm still debugging.

**Comment by jcznk** [comment]
Thanks! But it seems something went wrong when sharing the patch?

**Comment by jcznk** [comment]
Perfect! So far no weird due dates anymore. Thanks again!
