### ISSUE TITLE
[Feature Request] Disable "x cards rescheduled" after sync

### ISSUE THREAD

**Issue by emagaliff** [open-spaced-repetition/fsrs4anki-helper#141]
**Which module is related to your feature request?**
Helper

**Is your feature request related to a problem? Please describe.**
A recent update seems to have added a popup everytime Anki is synced where the add-on will display the number of cards synced. However, it is unnecessary and requires additional user inaction for what should be a one-click procress (especially closing Anki).

**Describe the solution you'd like**
Either get rid of the feature or add a toggle to enable/disable it.

**Describe alternatives you've considered**
N/A

**Additional context**
It's very unlikely that knowing how many cards were rescheduled is useful information for the majority of users. Added annoyance with little benefit.

**Comment by neznansky** [comment]
The pop-up is short, but beside popping-up it also centralizes Anki's window. That is, if I switched to another window and in the meantime Anki finished syncing, the system would switch back to Anki — which is a little annoying.

**Comment by neznansky** [comment]
Also, at least in my case (on Linux), the message appears both as a tooltip and as a popup, making the latter redundant.

**Comment by L-M-Sherlock** [comment]
Please see the discussion in #128, where some users suggest to remove `tooltip`.

**Comment by L-M-Sherlock** [comment]
I think it is OK to remove the popup. @user1823, what do you think of?

**Comment by user1823** [comment]
I still think that we should not remove the popup. But, if the majority thinks that the popup should be removed, I am fine with it.

But, before making the final decision, I think that all the users here should read my comment here: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/128#issuecomment-1599939379
