### ISSUE TITLE
16 June update freezes Anki startup

### ISSUE THREAD

**Issue by algieg** [open-spaced-repetition/fsrs4anki-helper#142]
Hi! First of all, thanks a lot for the scheduler and helper! 

Unfortunately, after I ran Anki on 16 June, I got a pop up for the add-on's update. After the update installed, Anki becomes unresponsive on start up run the add-on enabled. I tried running Anki without add-ons (holding shift to start it) and it runs fine. The only other add-on I use (HyperTTS) works fine and I can get Anki to work normally if I disable the helper but leave HyperTTS on.

I have the latest Qt6 Anki downloaded from the official website on Windows 11 (latest standard updates as well).

Any suggestions to fix it?

Thanks!

**Comment by L-M-Sherlock** [comment]
Do you enable auto-reschedule?

**Comment by L-M-Sherlock** [comment]
Could you update the add-on now? I fixed a related bug.

**Comment by L-M-Sherlock** [comment]
Does this issue still exist?

**Comment by algieg** [comment]
Apologies for the late reply. I haven't experienced this issue after the update you suggested first. Thank you!
