### ISSUE TITLE
FSRS new update issue

### ISSUE THREAD

**Issue by Axnpotential** [open-spaced-repetition/fsrs4anki-helper#144]
Hi,

I updated to the new FSRS 3.23.0 and click on "Auto reschedule cards reviewed in other device after sync" "Autodisperse sibling" and "Load balance when rescheduling"

Now when I re-opened Anki these pictures I have attached is what I get and I am unable to used Anki.
I am wondering how I can go back and unclicked what I have clicked from FSRS. 

Thank you for your help!
![1](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/135545011/6a8a1ec4-b1b9-48af-ba4c-fa4a650cedac)
![2](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/135545011/53e678d3-57fa-41e8-befb-bfcfdbf4928e)

**Comment by L-M-Sherlock** [comment]
The message shows that you doesn't configure the scheduler code correctly.

You can down the Shift key and click Anki to start it without loading add-ons.

**Comment by L-M-Sherlock** [comment]
> Now when I re-opened Anki these pictures I have attached is what I get and I am unable to used Anki.

Do you mean that your Anki is frozen?

**Comment by Axnpotential** [comment]
Yes that is correct,  Anki would freeze and I have to ctrl+alt+del.

I did disabled the add-on holding the shift and Anki was fine but when I enabled back the add-on, the same issue occurred where Anki would freeze again.

I was wondering if there were any other solutions.

My next step was to delete the add-on and re-install it back again. My worry is that I would have to do the steps to manually to the scheduling/optimizer code again.
But if it is the only solution then I will just do that and re-install the add-on.

**Comment by L-M-Sherlock** [comment]
> I did disabled the add-on holding the shift and Anki was fine but when I enabled back the add-on, the same issue occurred where Anki would freeze again.

Could you share your collection file which freeze when you open it? I need it to debug.

**Comment by Axnpotential** [comment]
Did you need me to upload my whole anki collection?

**Comment by L-M-Sherlock** [comment]
Yes, it would be helpful.

**Comment by Axnpotential** [comment]
https://drive.google.com/file/d/1OaiiIVSD00twIHwnKCoWZdTmWwc1TPFf/view?usp=sharing

This is the link. Hopefully it works.

Thank you

**Comment by Axnpotential** [comment]
The link should work now.

**Comment by L-M-Sherlock** [comment]
<img width="584" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/706a6b2e-b61b-4208-802d-6928c64fb268">

The format of `w` is incorrect.

**Comment by L-M-Sherlock** [comment]
By the way, when I use the latest helper, rescheduling doesn't freeze my Anki with your collection.

**Comment by Axnpotential** [comment]
What would be the correct format for the w?

Also I did not upgrade my Anki to 2.65 version (newest update version)
I am still on Anki 2.56 version

**Comment by L-M-Sherlock** [comment]
<img width="666" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/d773e0d2-9743-4573-9b90-4815ecd17a11">

You can refer to other configuration.

**Comment by L-M-Sherlock** [comment]
> Also I did not upgrade my Anki to 2.65 version (newest update version)

I mean the version of the helper add-on, not Anki itself.

**Comment by Axnpotential** [comment]
How would I edit the w format?
Because I would have to enable the add-on and it would freeze again.

**Comment by Axnpotential** [comment]
> <img alt="image" width="666" src="https://user-images.githubusercontent.com/32575846/246910734-d773e0d2-9743-4573-9b90-4815ecd17a11.png">
> You can refer to other configuration.

I changed the "w" to the format you gave me. It still refers back to the first picture I sent.

**Comment by Axnpotential** [comment]
Thank you for your help.
I was able to fix it by re-installing the add-on as well as using your "w" parameters.

It does not freeze anymore.

Thank you!
