### ISSUE TITLE
Question: Free Days - manual reschedule?

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki-helper#146]
If I want to use the Free Days feature, do I need to reschedule daily using the addon? Or will scheduling with the FSRS custom scheduling code honor the Free days settings?

I understand that the addon can read the code in the custom scheduling box. But how does the code read the addon settings?

**Comment by L-M-Sherlock** [comment]
Yep, Free Days feature requires rescheduling. The scheduler code doesn't know the global review information, so it couldn't follow the setting of Free Days.

**Comment by akavi1** [comment]
Does the same thing apply to Load balance?

**Comment by L-M-Sherlock** [comment]
> Does the same thing apply to Load balance?

Yep.

**Comment by user1823** [comment]
I would like to add one thing.

If you do your reviews on another device (AnkiMobile, AnkiDroid or AnkiWeb), you can set the helper add-on to auto-reschedule the synced reviews. This way, you won't have to manually reschedule your cards everyday.

If you do your reviews on Anki Desktop, you can use the "Reschedule cards reviewed in the last x days" option manually every day.
