### ISSUE TITLE
[Question] Should I manually disperse siblings when "Auto disperse siblings after auto rescheduling" is enabled?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#150]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
I noticed that even though I have "Auto disperse siblings after auto rescheduling" enabled, if I reschedule them manually (by pressing "Disperse all siblings"), a lot of cards get rescheduled. 
1) Is it necessary to press "Disperse all siblings" from time to time? 
2) Does "Disperse all siblings" work differently compared to automatically dispersing siblings?

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11834460/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/5d5b2ceaf147b4c88209607822a018b249f758eb

I added a feature to disperse siblings when you review the card.

**Comment by Expertium** [comment]
I didn't notice any lag even when 8-10 siblings were dispersed, that's good.
But the pop-up is pretty annoying, I recommend either removing it entirely or making it turned off by default so that the user has to turn it on if they want to. Once you do that, feel free to close this issue.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/a6fd5923-c097-4050-91b2-a7dda0c491dd)

**Comment by L-M-Sherlock** [comment]
OK, I will remove it.

**Comment by Expertium** [comment]
@L-M-Sherlock I guess I didn't test it thoroughly enough. Now I noticed a bug: if I review a card, press "Again", and then review it again on the same day, it will say "Dispersed n siblings" _again_, even though siblings should have been dispersed already.

**Comment by L-M-Sherlock** [comment]
The multiple dispersing is safe because the dispersing only modify the cards' due in their fuzz range.

**Comment by user1823** [comment]
I didn't test it practically. But, in the code, I found the following line:
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/3d19740c6d0afe18e3da9178215929b72b458f81/disperse_siblings.py#L263

This implies that the add-on uses the display of the answer as the trigger for dispersing siblings.

If it is the same as what I understand, this approach has three problems:
- Dispersal of siblings occurs before the card is actually answered. This means that
   - the last review date used for dispersing is not the same as the current date.
   - the due date of the card being answered is changed even before the card is answered.
- Dispersal of siblings can occur even if the card is not answered (if the user clicks "Show Answer" but doesn't rate the card).

A better approach would be to use `reviewer_did_answer_card` as the trigger. You can take help from the [Straight Rewards add-on](https://github.com/hgiesel/anki_straight_reward).

**Comment by L-M-Sherlock** [comment]
> * the due date of the card being answered is changed even before the card is answered.

I have exclude the current card. Only the siblings would be dispersed:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/3d19740c6d0afe18e3da9178215929b72b458f81/disperse_siblings.py#L249-L250
