### ISSUE TITLE
Undo review of card with disperse_siblings during review enabled

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#154]
With disperse_siblings during review enabled, the Undo option in Anki says "Undo Siblings Dispersing". (screenshot below)
<img width="308" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/3dae05d3-887d-4b8e-b1f2-964c625bf9c1">

I assume that after clicking "Undo Siblings Dispersing", I will see the usual "Undo Answer Card" option.

However, I think that undoing should be a single-click operation that undoes both dispersal of siblings and rating of the card. Based on the documentation, I think that the Straight Rewards add-on supports this. So, you can take help from that add-on.

Also, because you would be still using the "Undo Siblings Dispersing" option for undoing manual disperse_siblings, I would suggest renaming it to "Undo Disperse Siblings" because this looks nicer.

**Comment by L-M-Sherlock** [comment]
> However, I think that undoing should be a single-click operation that undoes both dispersal of siblings and rating of the card. Based on the documentation, I think that the Straight Rewards add-on supports this. So, you can take help from that add-on.

I find a weird thing:

```python
def init_review_hook():
    gains = {}


    reviewer_will_answer_card.append(
        lambda ease_tuple, reviewer, card: on_will_answer_card(
            gains, ease_tuple, reviewer, card
        ),
    )


    card_will_flush.append(
        lambda card: flush_with_straight_reward(gains, card),
    )
```
Source: https://github.com/hgiesel/anki_straight_reward/blob/3fe72255f667d2eb544afb2541a1eb974c23eede/src/lib/review_hook.py#L96-L107

Straight Rewards add-on doesn't use `reviewer_did_answer_card`. And it doesn't set checkpoint for undo.

By the way, I also haven't set the checkpoint for disperse siblings when review. I don't know why you can see the "Undo Siblings Dispersing".

**Comment by user1823** [comment]
It looks like it did a mistake. Possibly, I checked the undo option after sync instead of checking after review.

Now, I am seeing the usual "Undo Answer Card" option after reviewing cards with no siblings. However, the Undo option is greyed out after reviewing cards with siblings. (screenshot below)

<img width="267" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/8e387977-7673-4d87-b1e4-631f88a1f755">

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11855999/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/155/commits/6c0ac7d3a060f41fe7be5972d8ba8219fb7c55da

I refactor the undo operation in Helper add-on. Could you help me test it?

**Comment by user1823** [comment]
With this patch, I see the "Undo Disperse Siblings When Review" option.

However, I think that there should be a "Undo Answer Card" option which undoes the rating of the card as well as the dispersal of siblings.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11856074/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/155/commits/0bcd9637fd8211a80951b8c7016afb7a210449a5

This patch will work as you describe.

**Comment by user1823** [comment]
This works as intended. Thanks!!

**Comment by aleksejrs** [comment]
It looks like I am having this issue with the latest version and Anki 2.1.66.
It happens if the "Auto disperse siblings" is enabled. So I guess it just disperses the siblings after I answer a card, so the Undo Disperse button undoes that dispersion. Does it undo the answer, too?
