### ISSUE TITLE
不能撤销

### ISSUE THREAD

**Issue by xjqm-tao** [open-spaced-repetition/fsrs4anki-helper#156]
当天的所有卡牌复习完了（到期卡牌数量是0），不小心点了Reshedule all cards，到期卡牌数量非常多，想撤销，但Ctrl+z无作用，我记得以前它是可以撤销的啊？！
然后试点undo reshedule in all cards，结果到期卡牌数量有许多，不是点Reshedule all cards之前的状态

    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Windows-10-10.0.19041
    FSRS4Anki Helper ['759844606', 2023-06-24T18:02, 'None', mod]

**Comment by L-M-Sherlock** [comment]
最近重构了撤销的代码，因为现在qt6的客户端更多，所以优先支持qt6的撤销。
另外undo reschedule in all cards是撤销历史上的所有reschedule，直接删除FSRS相关的所有记忆状态，恢复到Anki默认算法。

**Comment by L-M-Sherlock** [comment]
建议reschedule all cards，然后用postpone把多出来的复习推迟。

**Comment by xjqm-tao** [comment]
> 
哦，我以前用过一段时间qt6的，有许多操作很慢很卡（比如进入编辑窗口、编辑后保存卡牌），经历几个新版本还是卡慢，所以换用qt5了

**Comment by L-M-Sherlock** [comment]
> For compatibility with existing code, the old checkpointing system, and the undo log in the v1 and v2 scheduler have been retained. To ensure the collection does not get into an inconsistent state however, any of the following operations will clear the new undo queue:
> 
> * a call to mw.checkpoint()
> * a call to a pylib routine that does not support undo (eg fixIntegrity())
> * directly writing to the database with col.db (read-only queries are fine)
> * reviewing a card with the v1 and v2 scheduler (v3 uses the new system)

来源：https://forums.ankiweb.net/t/add-on-porting-notes-for-anki-2-1-45/11212#undoredo-4

现在新的撤销系统和旧的撤销系统是不兼容的。使用旧的撤销系统，就会将新的撤销系统的队列清空。同样，使用新的撤销系统，也会清空旧的撤销系统的队列。
另外，我刚才也下了 qt5 版本的 Anki，测试了一下，可以正常撤销。不知道你能不能再提供一些其他信息。我暂时无法复现这个问题。

**Comment by xjqm-tao** [comment]
> 

今天我试了几次，我也不能复现了，不知道原因（我知道同步后撤销就会失效，但昨天我确信reshedule之后没有进行同步，最后我是从云端覆盖本地数据进行恢复的）

**Comment by xjqm-tao** [comment]
> 

今天我试了几次，我也不能复现了，不知道原因（我知道同步后撤销就会失效，但昨天我确信reshedule之后没有进行同步，最后我是从云端覆盖本地数据进行恢复的）

**Comment by L-M-Sherlock** [comment]
一个多月了，目前没有收到类似反馈，我将关闭这个问题。
