### ISSUE TITLE
[BUG] Disperse all siblings gets stuck 

### ISSUE THREAD

**Issue by ayyubshaffy7** [open-spaced-repetition/fsrs4anki-helper#157]
After rescheduling all my cards, I clicked on the option to disperse all siblings in the FSRS Anki helper addon and it always gets stuck at the 1000th note and remains there :
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/44515527/c99e098d-7275-43ce-8916-9ec27fcc26c3)

these are my addon settings :
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/44515527/7b3673eb-7966-4682-a280-b9b601b6d21c)

Environment
- Anki version: 2.1.63
- OS: Windows 11
- Scheduler version: Qt6
- Optimizer version: v3.20.0

**Comment by L-M-Sherlock** [comment]
Could you share your collection file with me?

**Comment by ayyubshaffy7** [comment]
> Could you share your collection file with me?
do you mean the .apkg file?

**Comment by L-M-Sherlock** [comment]
> do you mean the .apkg file?

I mean the backup file (.colpkg).

**Comment by ayyubshaffy7** [comment]
[backup-2023-06-28-19.13.29.txt](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11895360/backup-2023-06-28-19.13.29.txt)

changed .colpkg to .txt since github wouldn't let me upload

**Comment by ayyubshaffy7** [comment]
works now, thank you so much!
