### ISSUE TITLE
[BUG] Problem with intervals given by Helper

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#16]
I have some issues with the intervals given by the Helper. Two examples of cards with problems are shared below:

1. I reviewed the following card today. However, the due date given to this card by the Helper is 1st February. Also, the length of the interval is shown as 12 days. How is this possible?
<img width="50%" src="https://user-images.githubusercontent.com/92206575/218136448-9eb5dafb-5551-4f92-8570-483fc4396619.jpg">

2. The second issue is related to cards with copied scheduling data, which I mentioned in https://github.com/open-spaced-repetition/fsrs4anki/issues/136. In this case, the interval changed from 1.04 years to just 2 days. Please add a fix for this.
<img width="50%" src="https://user-images.githubusercontent.com/92206575/218136465-d5b85447-9ff6-4ac3-ad37-9cc6b62e31d4.jpg">

My settings are as follows:

- w = [1.0813, 1.5326, 5.0874, -1.1416, -1.1778, 0.0161, 1.6118, -0.0405, 0.992, 1.7511, -0.4642, 0.9, 0.6785]
- requestRetention = 0.94
- FSRS4Anki v3.13.4

**Comment by L-M-Sherlock** [comment]
Could you share the related cards with me? I need them to test the patch.

**Comment by user1823** [comment]
Here are these cards: [Selected Notes 1.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10709309/Selected.Notes.1.zip)
Please change the extension from .zip to .apkg

These cards are those formed after the interval has been changed by the Helper. Let me know if you want the original cards.

**Comment by L-M-Sherlock** [comment]
> 3\. The second issue is related to cards with copied scheduling data, which I mentioned in [[Question] Would FSRS work correctly for cards with copied scheduling data? fsrs4anki#136](https://github.com/open-spaced-repetition/fsrs4anki/issues/136). In this case, the interval changed from 1.04 years to just 2 days. Please add a fix for this.

It is easy to fix, but the helper couldn't recover the card. You need to restore to the backup.

**Comment by user1823** [comment]
> I need this original card.

Here are the original cards: [Selected Notes 2.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10709425/Selected.Notes.2.zip)

**Comment by user1823** [comment]
> It is easy to fix, but the helper couldn't recover the card. You need to restore to the backup.

I rescheduled the cards in a Test profile by making a copy of my collection. So, my original collection is safe.

**Comment by L-M-Sherlock** [comment]
The original card's due and interval were wrong, too.

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/32575846/218147496-677fcde7-7ef8-4dee-b54c-03a6aea4be70.png">

**Comment by user1823** [comment]
Then, I will ask about it on Anki Forums tomorrow. I am not able to open Anki Forums today.

**Comment by user1823** [comment]
> The original card's due and interval were wrong, too.

I thought about it again and realised that it is a not a bug on the part of Anki. It is due to my Anki settings.

As per my settings, when I press Again, the minimum interval given to the card is 22 days. However, this interval comes into play only after the relearning steps (which go up to 18 days) are complete.

<img width="50%" src="https://user-images.githubusercontent.com/92206575/218236361-597b28f0-9c66-4383-85fe-2259f23985b3.png">

What Helper did in this case was it reduced the interval from 22 days to 12 days and as a result pushed the due date of the card 10 days behind (from 11 Feb to 1 Feb).

To resolve this issue, I think that the Helper should **not reschedule relearning cards**.

**Comment by user1823** [comment]
I get your point that I should not use multiday learning or relearning steps with FSRS. However, these are the cards that I am studying before I switch to FSRS and these cards would take some time to leave their learning and relearning steps after I switch to FSRS. So, the FSRS scheduler and helper should be prepared to handle such cases.

I have an idea to make FSRS helper better in dealing with such cases. I am describing it here:

- The helper should not reschedule the learning and relearning cards.
- But, it should count the number of learning and relearning cards that were not rescheduled.
- After the rescheduling (of other cards) is complete, it should show the following message:
"## (re)learning cards were not rescheduled. Try rescheduling a few days later when these cards would have left their learning stage."
(Where ## should be replaced by the actual number)

**Comment by L-M-Sherlock** [comment]
> * But, it should count the number of learning and relearning cards that were not rescheduled.
> * After the rescheduling (of other cards) is complete, it should show the following message:
>   "## (re)learning cards were not rescheduled. Try rescheduling a few days later when these cards would have left their learning stage."
>   (Where ## should be replaced by the actual number)

I don't know its purpose. It could interrupt/confuse the user.

**Comment by user1823** [comment]
The purpose is to inform the user that some cards were not rescheduled but should be rescheduled after they leave their leave their learning steps.

**Comment by L-M-Sherlock** [comment]
I have pushed the patch. You can test it: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10712634/fsrs4anki-helper.zip).

Note: Rename the `.zip` to `.ankiaddon`. Then you can install the add-on via click.

**Comment by L-M-Sherlock** [comment]
> The purpose is to inform the user that some cards were not rescheduled but should be rescheduled after they leave their learning steps.

Counting the cards not rescheduled is not easy. I need to consider the learning/relearning/suspended separately. So I plan not to develop it in this patch version.

**Comment by user1823** [comment]
> It could interrupt/confuse the user.

To avoid confusion, we can also frame it as "Helper doesn't reschedule the cards in the (re)learning stage. ## such cards were not rescheduled. Reschedule again a few days later  when these cards would have left their (re)learning stage."

**Comment by user1823** [comment]
> Counting the cards not rescheduled is not easy. I need to consider the learning/relearning/suspended separately. So I plan not to develop it in this patch version.

Ok. I have a manual alternative in mind. So, I will not be affected much. But for the benefit of future users, you may keep this suggestion in mind.

**Comment by L-M-Sherlock** [comment]
> To avoid confusion, we can also frame it as "Helper doesn't reschedule the cards in the (re)learning stage. ## such cards were not rescheduled. Reschedule again a few days later when these cards would have left their (re)learning stage."

I will add this description to the add-on page.

**Comment by user1823** [comment]
> Note: Rename the .zip to .ankiaddon. Then you can install the add-on via click.

Can I update the add-on through AnkiWeb?

> You can test it.

I will test it in the evening (about 7 hrs later from now).

**Comment by L-M-Sherlock** [comment]
> Can I update the add-on through AnkiWeb?
> 
> >

To avoid more bugs, I will update the add-on on AnkiWeb after your test.

**Comment by L-M-Sherlock** [comment]
The latest version: 
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10713636/fsrs4anki-helper.zip)

**Comment by user1823** [comment]
I have tested it. It works better now, but I have the following points to share:

- With the current patch, all cards with copied scheduling data will always follow the standard Anki scheduling if I am using AnkiDroid and then rescheduling with the helper. This is fine until I eventually forget the card. Now, suppose that I forget one of those cards. Even then this card would not be rescheduled by the helper and would continue to follow the standard Anki scheduling. 
I think that this situation can be made better if we program the helper to **skip only those cards whose first review kind isn't learning AND which don't have any again rating**. (That is, it should skip only those cards which fulfil BOTH of the conditions.)
I am saying this because for the cards with an again rating, the behavior of the previous version of the Helper was correct. 
- With the current patch, the helper is not rescheduling in which the first review kind is relearning. I think that there should be **an OR condition between learning and relearning**.

Another observation, which is not related to this patch:
Sometimes, I use the "easy" button to push some learning cards far off when I think I know them well enough. But the helper decreases their interval back to a small value. Two such cards (one affected, one unaffected) are shared below. Can something be done for this?
<img width="50%" src="https://user-images.githubusercontent.com/92206575/218262255-3f34bdcb-2046-4a22-95fe-24f94d9efb5a.jpg">
<img width="50%" src="https://user-images.githubusercontent.com/92206575/218262260-58315419-12c6-49fd-b485-ce25b77e9001.jpg">

**Comment by L-M-Sherlock** [comment]
It would make the rescheduling process more complicated. The helper considered the entire review history, even if the card has some again ratings.

**Comment by user1823** [comment]
I think you misunderstood my point.

I also want the helper to consider the entire review history.

In the above patch, you made the helper skip those cards in which the first review is not of learn type.

I said that this is not the sufficient condition to skip the card. For the helper to skip the card, the condition should be that the first review is not of learn type AND the card should not have any again rating. (This means that the card will be skipped only if both conditions are satisfied, and not if only one of the conditions is satisfied.)

My second point was that in the above condition, learn should mean both learning and relearning.

**Comment by L-M-Sherlock** [comment]
If the card is in relearning, it means its previous rating is `again`. But the helper doesn't know the days that elapsed from the previous rating.

**Comment by user1823** [comment]
I am saying that for the above two conditions, the helper was working fine before the patch.

I think that this statement should clarify it to you what I am trying to convey.

**Comment by L-M-Sherlock** [comment]
OK, you mean it works in practice. I will develop a patch to improve it. But there still are some details that need to confirm.

> 1. The first review of the card is not of learn type, but "again" was pressed later on.

In this case, should the helper consider the review history older than the `again` review?

> 2. The first review of the card is of the relearn type.

In this case, `again` or the recorded first rating, which one should be considered as the first rating?

**Comment by user1823** [comment]
Before the patch, the helper was working fine. So, whatever it considered previously should be considered.

Also, I think that the patch should not be difficult.

I don't know coding. But from my general understanding, I can suggest you the following:

In the last patch, you added the following lines:

```
if i == 0 and revlog.review_kind != 0:
break
```

You can change it to
```
if i == 0 and (revlog.review_kind != 0 or revlog.review_kind != %) and _____:
break
```
where
- % should be replaced for the number representing the relearning type of review 
- _____ should be replaced by the code to check if the card has any again rating

**Comment by L-M-Sherlock** [comment]
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10715612/fsrs4anki-helper.zip)

I upload the patch here. Could you test it?

**Comment by user1823** [comment]
I am testing it. Could you also link the commit here so that I can also review the code changes?

**Comment by L-M-Sherlock** [comment]
> I am testing it. Could you also link the commit here so that I can also review the code changes?

https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/6a55a1b67d16ca669b3875ec0c3bb2761aba3160

**Comment by user1823** [comment]
I am facing a difficulty in finding a card in my collection in which the first review is not of learn (or relearn) type, but which has an again rating.

To find cards with again rating, I can use `rated::500:1` as the search term in the Anki Browser.

Can you suggest a search term to find cards in which the first review is not of learn (or relearn) type?

**Comment by L-M-Sherlock** [comment]
No idea. But you shared a card whose first review is not of learn (or relearn) type.



> <img alt="" width="50%" src="https://user-images.githubusercontent.com/92206575/218136465-d5b85447-9ff6-4ac3-ad37-9cc6b62e31d4.jpg">

**Comment by galantra** [comment]
> Can you suggest a search term to find cards in which the first review is not of learn (or relearn) type?

Do you only need to find _some_ card, or all cards of that kind? In the first case, you can use something like `prop:reps>3 rated:31:1`.

**Comment by user1823** [comment]
I have found one such card (manually) which fulfills both of the conditions. This card has been rescheduled by the Helper (as expected).

<img width="50%" src="https://user-images.githubusercontent.com/92206575/218302407-4face6d1-af8b-4e33-a4bf-8e040b4d94dd.jpg">

Kindly wait until I do some more testing.

**Comment by user1823** [comment]
It looks good. Thanks.

**Comment by user1823** [comment]
Now that all of my issues have been resolved, I have finally switched to FSRS.

Rescheduling with the Helper gave me a large backlog to overcome (about 950 cards). But, these cards are precisely those which I didn't learn properly earlier.

Thank you very much for developing such a good spaced repetition algorithm and also for resolving the issues quickly.
