### ISSUE TITLE
[Bug] Card not rescheduled after sync

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#161]
For an unknown reason, the following card didn't get custom data after sync. (I answered it on AnkiDroid)
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/c6b91537-4632-4afa-8b66-7bc80ee64912)

All the other cards were rescheduled.

**Comment by L-M-Sherlock** [comment]
Only reviewed cards will be rescheduled. The card shown in the figure is still in learning stage.

**Comment by user1823** [comment]
Possible reason: It was still in its learning stage.

But, the helper is supposed to add custom data to such cards as well. (https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/8977a10bb48f753bbce3b127b93dde7c50e64e3b)

**Comment by L-M-Sherlock** [comment]
Weird. Could you share this card with me?

**Comment by user1823** [comment]
[bugged_card.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11970207/bugged_card.zip) (Change extension to .apkg)

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11970334/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/31b71ce78b04a828840c77f3a0a1da89e5803a09

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11970334/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/31b71ce78b04a828840c77f3a0a1da89e5803a09
