### ISSUE TITLE
[Question] Does the code for "Disperse siblings" check all decks?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#163]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
Does the code for "Disperse siblings" check decks other than the one where the card came from? The reason I'm asking is because I have two decks with cards that are made from the same note. Type 1 cards are in deck 1, and type 2 cards are in deck 2. And it seems that they don't get dispersed. I suggest modifiying the code so that siblings will be dispersed even if they are in different decks.

**Comment by L-M-Sherlock** [comment]
"Disperse siblings" always checks the entire collection to find out all siblings.

**Comment by Expertium** [comment]
Then I wonder why I see siblings on the same day when they are in different decks. I'll keep an eye for this bug and probably report later.

**Comment by Expertium** [comment]
Ok, I finally figured out when it happens: if one card is in the "learning" stage, and the other is not, they will not be dispersed. Both cards from the same note have to be in the "review" stage.

**Comment by L-M-Sherlock** [comment]
> Ok, I finally figured out when it happens: if one card is in the "learning" stage, and the other is not, they will not be dispersed. Both cards from the same note have to be in the "review" stage.

Anki's auto-bury also doesn't affect cards in the "learning" stage:

> Anki will only bury siblings that are new or review cards. It will not hide cards in learning, as time is of the essence for those cards. On the other hand, when you study a learning card, any new/review siblings will be buried.

Source: https://docs.ankiweb.net/studying.html?highlight=bury#siblings-and-burying
