### ISSUE TITLE
Will Helper still support version 3.x or just new version 4.0?

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#166]
Will Helper still support version 3.x or just new version 4.0?

**Comment by L-M-Sherlock** [comment]
> Will Helper still support version 3.x or just new version 4.0?

It will keep backward compatibility.

**Comment by cjdduarte** [comment]
> > Will Helper still support version 3.x or just new version 4.0?
> 
> It will keep backward compatibility.

I forgot to ask. And the Optimizer too, right?
