### ISSUE TITLE
Ideas to refactor the code

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#167]
While I was looking at the code for finding the formulas that haven't been updated for v4 yet, I realised that the following parts of the code could be refactored:

1.
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/reschedule.py#L267-L275

In this, why not just use the code in line 273 instead of calculating the stability for each rating separately?

The same holds true for the following: https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/reschedule.py#L282-L289

I think that you did it this way because the formula for calculating the interval is different for different ratings (in v3)

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/reschedule.py#L304-L318

But, I think that there should be a better way of doing this.

2. In the following lines, shouldn't the `last_due` be obtained using the `get_last_review_date` function in utils.py?

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/browser/custom_columns.py#L115-L118

**Comment by L-M-Sherlock** [comment]
> In this, why not just use the code in line 273 instead of calculating the stability for each rating separately?

Because `again_s`, `hard_s`, `good_s` and `easy_s` are used to calculate `again_interval`, `hard_interval`, `good_interval` and `easy_interval`. And these intervals are related to each other because these lines of code:

```python
     hard_ivl = min(hard_ivl, good_ivl) 
     good_ivl = max(hard_ivl + 1, good_ivl) 
     easy_ivl = max(good_ivl + 1, easy_ivl) 
```

**Comment by user1823** [comment]
> Because again_s, hard_s, good_s and easy_s are used to calculate again_interval, hard_interval, good_interval and easy_interval. And these intervals are related to each other because these lines of code:

Ok. I understand.

Let's do these also:
- Turn on features by default (https://github.com/open-spaced-repetition/fsrs4anki/issues/348#issuecomment-1634541222)
- Renaming options (https://github.com/open-spaced-repetition/fsrs4anki/issues/300#issuecomment-1597198047)

**Comment by L-M-Sherlock** [comment]
> * Renaming options ([Collection of low priority & breaking ideas for FSRS fsrs4anki#300 (comment)](https://github.com/open-spaced-repetition/fsrs4anki/issues/300#issuecomment-1597198047))

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/80820b6f-5a97-47cd-a160-a4d1f996e4c2)

It has been done.

> * Turn on features by default ([[Beta Testing] FSRS4Anki 4.0.0 Scheduler, Optimizer and Helper. fsrs4anki#348 (comment)](https://github.com/open-spaced-repetition/fsrs4anki/issues/348#issuecomment-1634541222))

I don't know why these options should be turn on by default.

**Comment by user1823** [comment]
> > * Renaming options ([Collection of low priority & breaking ideas for FSRS fsrs4anki#300 (comment)](https://github.com/open-spaced-repetition/fsrs4anki/issues/300#issuecomment-1597198047))
> 
> ![image](https://user-images.githubusercontent.com/32575846/253528550-80820b6f-5a97-47cd-a160-a4d1f996e4c2.png)
> 
> It has been done.

The suggestion was related to the deck-specific options (the ones which appear on clicking the cogwheel icon next to a deck). So, it has not been done.
> > * Turn on features by default ([[Beta Testing] FSRS4Anki 4.0.0 Scheduler, Optimizer and Helper. fsrs4anki#348 (comment)](https://github.com/open-spaced-repetition/fsrs4anki/issues/348#issuecomment-1634541222))
> 
> I don't know why these options should be turn on by default.

If we recommend that all users should use these features (see README), then it makes sense to have these features turned on by default.
Well, now I that give it a thought again, I think that _only the auto-disperse feature_ should be enabled by default.

The load balance feature has a problem due to which I stopped using it just after a few days. Because it "pulls" reviews into the relatively free days, it tends to cause related cards to show up on the same day. In other words, it decreases the effectiveness of fuzz. (Siblings are spared from this effect because there is disperse_siblings.)

I am not telling you to fix this problem (because it is not fixable, in my opinion). But, this is the reason why Load balance shouldn't be enabled by default.
