### ISSUE TITLE
Tip: Submenu

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#17]
As it now has many new options, a submenu would make it better organized.

![image](https://user-images.githubusercontent.com/42243532/218146096-c7f11a61-65c6-4365-b8eb-d02cbaab6e26.png)

**Comment by L-M-Sherlock** [comment]
Could you provide some example codes/projects?

**Comment by cjdduarte** [comment]
> Could you provide some example codes/projects?

[Link](https://github.com/bewuwy/Neo-Anki-Leaderboard/blob/master/menu.py)

**Comment by L-M-Sherlock** [comment]
Thanks for sharing! I have to sleep (1:00 a.m. in China now). I will learn about it tomorrow.

**Comment by cjdduarte** [comment]
I realized that the changes made, change to other profiles.

![image](https://user-images.githubusercontent.com/42243532/218274795-336216d7-832d-4e85-a274-678cc4f8c71d.png)

**Comment by L-M-Sherlock** [comment]
> I realized that the changes made, change to other profiles.
> 
> 

The config.json seems to be shared among profiles.
