### ISSUE TITLE
[Feature Request] Display requested R and measured R in the stats window

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#170]
**Which module is related to your feature request?**
Helper add-on.

**Is your feature request related to a problem? Please describe.**
It would be great if users could know how well FSRS is delivering on its promise, in other words, how close requested R is to measured R.

**Describe the solution you'd like**
Currently these stats can be seen using True Retention add-on:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/19d887a0-ff94-436a-be3e-01f54ed3e019)
But I believe FSRS should implement it natively so that users won't have to rely on True Retention. Basically, stats window should display requested R and measured R over some time period.

**Additional context**
The problem is that we already have a stat called "Average retention", so this can be confusing if we add more stats with similar names.

**Comment by Expertium** [comment]
Also, perhaps allow the user to choose requested R in the helper add-on too? That way the user doesn't have to dig into the code.

**Comment by L-M-Sherlock** [comment]
What's the difference between measured R and `average retention` in FSRS stats?

**Comment by Expertium** [comment]
Measured R should be calculated without including undue cards. It's just the proportion of cards that the user got right. For example, if the user reviewed 100 cards and pressed Again 10 times, measured R is 90%.

**Comment by L-M-Sherlock** [comment]
Oh, so that has been implemented in `true retention` add-on. The measured R is not relied on FSRS states. I don't want that FSRS has more and more duplicated features with other add-ons.

**Comment by Expertium** [comment]
But it would be good  because we could see how much measured R deviates from requested R.

**Comment by L-M-Sherlock** [comment]
To my knowledge, there are three different `true retention` add-on: 

[True Retention - AnkiWeb](https://ankiweb.net/shared/info/613684242)

[True Retention by Card Maturity - AnkiWeb](https://ankiweb.net/shared/info/923360400)

[True Retention by Card Maturity Simplified - AnkiWeb](https://ankiweb.net/shared/info/1779060522)

Which one should we integrate into the helper add-on? Or do you have another design for measured R?

**Comment by Expertium** [comment]
The first one.

**Comment by L-M-Sherlock** [comment]
Why not just recommend users to install the first one?

**Comment by Expertium** [comment]
Because it's more convenient to use one add-on than two.

**Comment by user1823** [comment]
In my opinion, the third one is better because it is useful to know if the performance is equally good on young and mature cards or not.

**Comment by Expertium** [comment]
Ok, so now that all the stuff regarding benchmarking is finished, and the stuff regarding formulas is mostly finished (aside from covering edge cases when calculating S0), let's focus on quality-of-life features like this one.
So @L-M-Sherlock, how do you think this should be done?

**Comment by L-M-Sherlock** [comment]
I prefer the third one, too. I will implement the stats based on [True Retention by Card Maturity Simplified - AnkiWeb](https://ankiweb.net/shared/info/1779060522).

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12304608/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/fb3b7a2e61424ad42f97594a724e29e1666415da

**Comment by L-M-Sherlock** [comment]
OK. I will implement it later.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12304784/fsrs4anki-helper.zip)

**Comment by user1823** [comment]
Some cosmetic suggestions:
- Remove the italics
- Add some padding to each cell of the table
- Remove the colors (subject to discussion)

Another idea:
The original true retention add-on decides whether to include a card in the stats or not based on whether it is a learning card or a review card. But, in my opinion, there is no difference between a learning card having a 3-day interval and a review card having a 3-day interval.

So, wouldn't it be better to filter cards based on their interval (such that all cards with intervals more than or equal to 1 day are included) rather than filtering them based on whether they are learning cards or review cards.

**Comment by user1823** [comment]
> I think the reason the original add-on doesn't include learning cards is because it can lead to "double counting"

But, if we include only those reviews where the new interval > 1 day, this "double counting" would not occur, would it?

> And besides, FSRS only affects "review" cards, so it makes perfect sense to only include those.

I get it. But, if expanding the scope of the stats without introducing any adverse effects is possible, we should try to do it. Isn't it?

**Comment by Expertium** [comment]
@L-M-Sherlock what do you think?

**Comment by L-M-Sherlock** [comment]
> The original true retention add-on decides whether to include a card in the stats or not based on whether it is a learning card or a review card. But, in my opinion, there is no difference between a learning card having a 3-day interval and a review card having a 3-day interval.

In fact, the calculation of retention doesn't involve the review log in learning stage. You read the code:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/45a7a0bbff3521b3d371be75c100a007af5625f3/stats.py#L209-L217

`type == 1` means the review log is recorded when the card is in review stage. Here are more details about the meaning in  Anki database: https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#review-log

**Comment by L-M-Sherlock** [comment]
> * Remove the italics
> * Add some padding to each cell of the table
> * Remove the colors (subject to discussion)

I remove the italics and add padding to the table. But I prefer keep the colors.
