### ISSUE TITLE
Helper is always rescheduling cards after study sessions. Should not

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#173]
I remember right at the launch of FSRS4 that the add-on HELPER would only need to be activated when we changed the weights of fsrs4anki_scheduler.js and HELPER "adjusted" the cards for the new weights

Without changing the parameters, in **version 3.x** even after a week of study, if I activated HELPER, nothing would happen, because as I didn't change the weights, fsrs4anki_scheduler.js already left the cards in their correct places. And the helper would schedule them where they already are (correctly scheduled by fsrs4anki_scheduler.js).
That is, if I am not using LOAD BALANCE there would be no need to activate the helper because it is well aligned with the javascript.

But in this **new version 4.x** I realize that there is something strange. after a week of studies, if I call the helper, he ALWAYS reschedules the cards.

It seems that the schedules made by javascript are not aligned with HELPER.
Just today there were 52 cards due to study. however, when activating the helper, there were only 32.
20 went to the "future"

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/66bf74d3-a60f-4471-862b-05baa568e5fa)

**Comment by Alexandrefac** [comment]
Agree

**Comment by user1823** [comment]
In my opinion, the reason is that the helper add-on now disperses the siblings after review of each card by default.

So, if you click "Reschedule", the dispersed siblings come back to their actual places, which you would see as a change in the number of due cards.

To test this, you can click "Reschedule all cards" and then "Disperse all siblings". Ideally, the due count should return back to what it was before rescheduling (if ALL the siblings were previously well dispersed.)

Also, @L-M-Sherlock, I think that disperse siblings should be automatically called after reschedule (if they didn't disable it in the config). We have tested it extensively and I don't think it would cause any problem with the majority of the users.

**Comment by cjdduarte** [comment]
I don't use cards with siblings (Cloze)

**Comment by user1823** [comment]
Just confirming. Not even Basic (and reversed card), Basic (optional reversed card) or Image Occlusion?

**Comment by cjdduarte** [comment]
> Just confirming. Not even Basic (and reversed card), Basic (optional reversed card) or Image Occlusion?

No. 100% of my cards are standard "Question/Answer". Only with layout changes.
And I also don't use Image Occlusion

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/001f0c8b-9ec0-4f41-9113-18ccbbd8936a)

**Comment by cjdduarte** [comment]
And I'm using the latest versions

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/63c0a6f3-c03a-4cea-bebf-529ce97e380f)

**Comment by L-M-Sherlock** [comment]
> Just today there were 52 cards due to study. however, when activating the helper, there were only 32.

Could you compare the stats graph and card info? I need more details to locate the problem.

**Comment by L-M-Sherlock** [comment]
Are those rescheduled cards reviewed with FSRSv3 before?

**Comment by cjdduarte** [comment]
> Are those rescheduled cards reviewed with FSRSv3 before?

I do not remember. It's a deck that I started anew. I do not think so.
As I already studied today, I'll wait until tomorrow and generate a base to send.

**Comment by L-M-Sherlock** [comment]
There is an potential cause. The helper add-on use its own fuzz factor:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/9d89ec0b1d20d639da50f290457e94da72d826d9/reschedule.py#L96-L99

which is different from the fuzz factor in the scheduler. I will fix it.

**Comment by cjdduarte** [comment]
It's a big possibility and it would make sense.

Thanks.

**Comment by L-M-Sherlock** [comment]
Another potential cause: in learning/relearning review, the scheduler would not update the memory state. But the helper will update the memory state if the learning/relearning review elapsed one or more days since the last review.

**Comment by cjdduarte** [comment]
> Another potential cause: in learning/relearning review, the scheduler would not update the memory state. But the helper will update the memory state if the learning/relearning review elapsed one or more days since the last review.

But in this case, would that necessarily be a bug or a limitation?
In my case I also have many cards in learning

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/b5b1335d-e694-4470-b80b-19991db47190)

**Comment by cjdduarte** [comment]
I ask, because in the case of fuzz, it could be a small "error".
My concern is the "Helper" and the "scheduler" not being aligned.
But if it's just a temporary limitation of learning cards, I don't see much of a problem.

**Comment by L-M-Sherlock** [comment]
> But in this case, would that necessarily be a bug or a limitation?

It's a limitation. When your (re)learning steps are shorter than one day, the helper and the scheduler is aligned. That's why I recommend not using steps longer than one day.

**Comment by cjdduarte** [comment]
I updated the helper here and the cards changed.
But now it makes sense, because I noticed that they were going "forward". Now it seems that they "returned" to their places.

I believe it was the fuzz itself.

I'll follow up here in the next few days and report back if it's resolved.

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/f9359459-9731-45fa-a453-44b14f946b09)

**That card went back to the 28th. It was on the 31st (today)**
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/bbc217a4-8e78-45e0-a65e-977d1ef28011)

**Comment by Alexandrefac** [comment]
> Are those rescheduled cards reviewed with FSRSv3 before?
Hello, I usually use the reeschedule feature every day since v3 and out of 4k cards, very few were changed. Now, the reeschedule is modifying a lot of cards. Something seems to have changed.

**Comment by L-M-Sherlock** [comment]
> Now, the reschedule is modifying a lot of cards.

Does it happen every day? When you update from v3 to v4, the first rescheduling would modify a lot. But it should not happen after the first rescheduling.

**Comment by cjdduarte** [comment]
> > Are those rescheduled cards reviewed with FSRSv3 before?
> > Hello, I usually use the reeschedule feature every day since v3 and out of 4k cards, very few were changed. Now, the reeschedule is modifying a lot of cards. Something seems to have changed.

helper fuzz was a little different from scheduler.js

What I understood was that as we were studying, scheduler.js used a fuzz and HELPER rescheduled using another fuzz.
In your case, which had more than 3k, this was accumulating.
Now fixed everything to what it should always be.
Take a test tomorrow. should no longer change anything.

**Comment by cjdduarte** [comment]
that's right? @L-M-Sherlock

**Comment by Alexandrefac** [comment]
> > Now, the reschedule is modifying a lot of cards.
> 
> Does it happen every day? When you update from v3 to v4, the first rescheduling would modify a lot. But it should not happen after the first rescheduling.

Yes, every day.

**Comment by Alexandrefac** [comment]
With the new update just now, it seems to have returned to normal. Out of 4k cards, only 1 was changed.
Congratulations!
