### ISSUE TITLE
Use disperse siblings by default after reschedule

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#174]
I think that disperse siblings should be automatically called after reschedule (if the user didn't disable it in the config). We have tested it extensively and I don't think it would cause any problem with the majority of the users.

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/173#issuecomment-1658204186_

**Comment by L-M-Sherlock** [comment]
There still is a problem: `disperse siblings`will break load balance.

**Comment by user1823** [comment]
But if someone wants to use `disperse siblings`, he would use it manually if dispersion doesn't occur automatically after reschedule.

So, I don't think that this is valid reason to not bind `disperse siblings` to reschedule.

Coming back to the problem you highlighted, it might be desirable to make disperse siblings work with load balance if the user chose to enable both. But, I am not telling you to implement this now, considering that it would probably require a lot of work. You can implement it whenever you find the time to do so.

**Comment by Expertium** [comment]
I agree that disperse siblings should be used after rescheduling.

**Comment by L-M-Sherlock** [comment]
The current implementation of `disperse siblings` is based on a random allocation. So it would be impossible to work compatibly with `load balance` and `no anki`. I have try to alleviate it in #87, but it doesn't solve the problem completely.

**Comment by L-M-Sherlock** [comment]
I find that I have set it by default in #165.

**Comment by user1823** [comment]
> I find that I have set it by default in #165.

I don't think so. When I click disperse all siblings after clicking reschedule all cards, there is always a reduction in the number of due cards.

**Comment by Expertium** [comment]
https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/194#issuecomment-1689166653
I'm using that version. I just tried dispersing siblings and saw no change in the number of due cards.

**Comment by L-M-Sherlock** [comment]
Yeah, auto dispersing siblings only works after the auto rescheduling after sync and reviews. For manual rescheduling, I need to solve these problems:

> The current implementation of `disperse siblings` is based on a random allocation. So it would be impossible to work compatibly with `load balance` and `no anki`. I have tried to alleviate it in #87, but it doesn't solve the problem completely.

**Comment by L-M-Sherlock** [comment]
I'm afraid that #438 is caused by dispersing siblings.

**Comment by L-M-Sherlock** [comment]
> > So, I don't think that the incompatibility of disperse_siblings with load balancer is a valid reason to not bind `disperse siblings` to `reschedule`.

I think it is a valid reason. Or we should warning the user that disperse siblings and load balancer are mutually exclusive.

**Comment by user1823** [comment]
> Or we should warning the user that disperse siblings and load balancer are mutually exclusive.

I think informing the user is the best approach. However, I don't see any moment where we can warn the user in the form of a popup. So, I think that this advice should be added to the README and the add-on page. Write it like this:

> When both auto disperse siblings and load balance are enabled, auto disperse takes a higher priority. So, the daily review load would not be as smooth. If you want your daily review load to be as smooth as possible, you can disable auto disperse.

**Comment by L-M-Sherlock** [comment]
I'm re-considering this feature. Here is my initial design:

1. merge disperse sibling into reschedule
2. add a global setting named "Disperse sibling when rescheduling (it breaks load balance)" (enable by default)
3. remove "Auto disperse siblings reviewed on other devices after sync" (because it will be executed if users enable "Auto disperse siblings reviewed on other devices after sync" and "Disperse sibling when rescheduling".)

What do you think of?

**Comment by Expertium** [comment]
Hard no. I rarely use rescheduling, this would make Disperse Siblings nearly useless for me.

**Comment by L-M-Sherlock** [comment]
> I'm suggesting to run Disperse Siblings after rescheduling.

Are they the same? Running Disperse Sibling after rescheduling is just putting the disperse_sibling function in the end of reschedule function.

**Comment by Expertium** [comment]
Right now I'm using "Auto disperse siblings when review". I'm suggesting to keep that option but also automatically disperse all siblings when rescheduling happens.
1) "Auto disperse siblings when review" is activated after each review
2) **Additionally**, ALL siblings all dispersed after rescheduling

**Comment by L-M-Sherlock** [comment]
I won't remove "Auto disperse siblings when review". As I mention before, Auto disperse siblings reviewed on other devices after sync" will be removed.

**Comment by Expertium** [comment]
> * "Auto disperse siblings when review" is activated after each review
> * **Additionally**, ALL siblings will be dispersed after rescheduling

If your plan matches what I wrote here, then sure.

**Comment by L-M-Sherlock** [comment]
@user1823, what about you? I plan to implement it in the next week.

**Comment by user1823** [comment]
> remove "Auto disperse siblings reviewed on other devices after sync" (because it will be executed if users enable "Auto disperse siblings reviewed on other devices after sync" and "Disperse sibling when rescheduling".)

I assume that you mean "it will be executed if users enable "Auto **reschedule cards** reviewed on other devices after sync"".

This approach wastes CPU and network resources unnecessarily because, in this case, the users would have to enable "Auto reschedule after sync" and, as a result,
1. ALL the synced reviews would be rescheduled, not only those which have siblings (In my case, only about 20% of the notes have siblings).
2. the memory states of the cards would be recalculated.

But, to prevent this issue, we would have to create a new option without removing any of the current options, which can increase clutter / confusion.

**Comment by L-M-Sherlock** [comment]
Fine. So I need to keep "Auto disperse siblings reviewed on other devices after sync", and add an extra option "Disperse sibling when rescheduling". 

But in this case, if the user enable auto reschedule after sync and auto disperse after sync, the disperse function will be called twice.

**Comment by user1823** [comment]
> if the user enable auto reschedule after sync and auto disperse after sync, the disperse function will be called twice.

You can easily prevent that by adding a simple condition.
