### ISSUE TITLE
[Feature request] Dilute, an alternative to Postpone

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#184]
I think we may need a new feature similar to Postpone, but targeting a specific number of reviews/day.
@L-M-Sherlock here is my idea: call the new feature "Dilute" (yes, stolen from SuperMemo again). It should change intervals in a way that makes the number of reviews/day for the next several days equal to or lower than the current value of Burden.
Say, currently burden=100, but the user has 500 due cards. Dilute should change their intervals in such a way that today (and for n more days) the number of due cards will be 100 or less. Note that it should be able to affect cards that aren't due today, but will become due within the next n days. In other words, Postpone only postpones cards that are due today, but Dilute postpones other cards too, cards that would be due tomorrow or the day after tomorrow. Sorry, but I don't have a precise step-by-step description of an algorithm that will actually do this.
Unfortunately, this can be even more detrimental to the schedule than Postpone, if used too often. Also, I think it's time we implement per-deck priority. That way low priority material will be postponed more, and high priority material will be postponed less.

_Originally posted by @Expertium in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/175#issuecomment-1676068001_

**Comment by L-M-Sherlock** [comment]
If `Dilute` allow to postpone cards that would be due tomorrow or the day after tomorrow, it will be very complex. It could even not be finished in one loop.

I have a simple solution:

1. Calculate the number of cards which should be diluted. In your case, it is 500 - 100 = 400.
2. Count the cards due in X days.
3. Calculate the free quotas for X days. Formula is `quota = burden - due` per day.
4. Sum these quotas until the total quotas reach the number of cards need dilute.
5. Sort the cards by interval. Dilute the card with longest interval to today + X.
6. Dilute the cards in queue one by one.

**Comment by Expertium** [comment]
I don't quite understand your algorithm, but if you think it will produce similar results to what I want, let's implement it.
I assume you're not planning to implement priority just yet?

**Comment by Expertium** [comment]
Ah, thank you. Though this could lead to a problem if due cards > Burden is true for many many days.

**Comment by L-M-Sherlock** [comment]
I have another problem. What if the user dilute cards in the same day with multiple times? Every time the user uses it, the current value of Burden decreases, and more cards will need to dilute.

**Comment by user1823** [comment]
@Expertium, but why do you want to implement this? I think that we should refrain from adding too many complicated features.

Also, don't you think that the solution proposed by me (https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/175#issuecomment-1675936970) would be sufficient to deal with the issue?

**Comment by L-M-Sherlock** [comment]
OK. I close this issue as not planned. Let's focus on #175.
