### ISSUE TITLE
No Anki on Free Days doesn't work

### ISSUE THREAD

**Issue by dontknow123gh** [open-spaced-repetition/fsrs4anki-helper#185]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/132260185/d170663b-a108-4d27-9340-d2e773c12909)
I have set "no anki on free days" for monday
It always shows in the statistic that there will be no review on that day at first.
However, as the free day becomes more and more near, the card due will increases.
In the above photo, it increases to 78.
[JLPT (N1~N5)_.csv](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12329564/JLPT.N1.N5._.csv)
attached is the *.apkg, I renamed it as *.csv, as *.apkg is not allowed to be uploaded.

**Comment by L-M-Sherlock** [comment]
The potential explanation is when the free day becomes more and more near, you will forget some cards in these days. And these cards have a very short interval. Free Days should respect the fuzz range (original interval +- 5%). So for these cards, Free Days couldn't modify their interval.

**Comment by dontknow123gh** [comment]
I see, thanks for the explanation

**Comment by L-M-Sherlock** [comment]
By the way, could you share your configuration for FSRS?

**Comment by dontknow123gh** [comment]
[fsrs4anki - 2023.08.10-2000.txt](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12329705/fsrs4anki.-.2023.08.10-2000.txt)
![Untitled](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/132260185/051cff2c-50e9-4aca-8377-e08a24a42652)
Attached also the deck option, this is the parent deck setting, the actual new cards limited by the sub decks(they have same setting but only with less new cards limit) will become 12 only.

**Comment by L-M-Sherlock** [comment]
I checked your custom scheduling. Please remove these parameters:

```
    "easyBonus": 1.3,
    "hardInterval": 1.2,
```

There parameters are unused in FSRS v4. They could induce problems.
