### ISSUE TITLE
[BUG] Get cards with R much higher than requested R

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#186]
By the way, I noticed that after rescheduling I get cards with R much higher than my requested R, which is 0.8 for all my decks.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/d7957350-9045-4d4e-8048-cfb457fcd5fb)

_Originally posted by @Expertium in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/175#issuecomment-1671208781_

**Comment by L-M-Sherlock** [comment]
@Expertium, could you provide more details? Such as, card info, FSRS configuration, and so on.

**Comment by Expertium** [comment]
Deck: https://drive.google.com/file/d/1hTtd6jjOInu3hvubDp-cZ0WZotZD9kHn/view?usp=sharing
```
"deckName": "Main::Science",
    "w": [1.75, 0.34, 1.05, 25.12, 4.3769, 0.999, 0.9592, 0.0, 1.5168, 0.1063, 0.9033, 2.1476, 0.1321, 0.3643, 0.9035, 0.2433, 3.2814],
    "requestRetention": 0.8,
    "maximumInterval": 365,
```

**Comment by L-M-Sherlock** [comment]
> "maximumInterval": 365,

It limited the interval of your card. So the R is much higher than requested R.

**Comment by Expertium** [comment]
Ah, my bad.
