### ISSUE TITLE
[Feature Request] Make "fuzz" a little smarter

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#187]
Currently fuzz just adds a random number to the interval. However, there is a better way of doing this. Look ahead n days, choose the day with the lowest number of due cards, and schedule the card that has been just reviewed to appear on that day.
Sherlock, if you remember our conversation about "Dilute", this is conceptually similar. The idea is that scheduling the review to happen on the day with the lowest workload should make the workload more consistent than just adding a random number to the interval.

**Comment by Expertium** [comment]
Ooops, wrong repo. This was meant for the scheduler, not the helper add-on.

**Comment by L-M-Sherlock** [comment]
> Look ahead n days, choose the day with the lowest number of due cards, and schedule the card that has been just reviewed to appear on that day.

The scheduler doesn't have the access to these information. So it's impossible in technology.
