### ISSUE TITLE
[Feature Request] A graph of the user's retention

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#188]
The True Retention functionality is nice, but it's not the most intuitive way to present data. I suggest adding another graph to "Stats", similar to this one from the simulator, but with only one curve.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/21d510c4-3847-4322-b5f1-44b9c15397f7)
On the x axis will be days since the user did their first review. Retention will be on the y axis. For smoothing I guess we can use either a 14-days moving average or a 7-days moving average.
This will give users an idea of how their retention has changed over time. And it would be cool to see how the graph changed once they switched to FSRS!

**Comment by Expertium** [comment]
@L-M-Sherlock I know you are busy making a Rust version of the optimizer, but it would be nice if you started working on this feature.

**Comment by L-M-Sherlock** [comment]
Save for Scratch code

```sqlite
SELECT DATE(id/1000, 'unixepoch', 'localtime') AS date,
SUM(CASE WHEN  ease == 1 THEN 0.0 ELSE 1.0 END) / COUNT(*) AS retention
FROM revlog
WHERE type = 1
GROUP BY date
;
```

date | retention
-- | --
2018-12-10 | 0.844660194174757
2018-12-11 | 0.863192182410424
2018-12-12 | 0.900900900900901
2018-12-13 | 0.885993485342019
2018-12-14 | 0.886627906976744
2018-12-15 | 0.828169014084507
2018-12-16 | 0.83625730994152
2018-12-17 | 0.955555555555556
2018-12-18 | 0.935483870967742
2018-12-19 | 0.973544973544973

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/abab67b0-7b5d-426b-a7c9-442f71e37c71)

How about that?

**Comment by Expertium** [comment]
The y axis should have more numbers than just 0 and 1, that's for sure.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12385928/fsrs4anki-helper.zip)
Preview: 
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/af8d3c1c-5eea-4411-80db-051228c14559)



> Also, instead of using monthly retention, I recommend using weekly retention.

It depends on the period. I keep it consistent with this graph:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/80a1c791-3f62-4412-bd12-bd87d9564425)

**Comment by Expertium** [comment]
It would be great to have average retention too (god damn, we really need a better naming convention), but the problem is that it would be too computationally expensive, I think.

**Comment by L-M-Sherlock** [comment]
> It would be great to have average retention too

What's that?

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/9e9a383e-6576-4591-863c-e9c421a02b2e)

**Comment by Expertium** [comment]
Unrelated, but I'm pretty sure "Burden" also includes cards in the "(re)learning" stage, so you should probably add that to the description of Burden. Right now it might make the users think that Burden is calculated using only cards in the "review" stage.

**Comment by L-M-Sherlock** [comment]
Do you mean the average retention over time? It's impossible to calculate. Because it requires to store cards' memory states perday. Anki doesn't store them.

**Comment by L-M-Sherlock** [comment]
> I'm pretty sure "Burden" also includes cards in the "(re)learning" stage

The subtitle has said that "calculated for cards with custom data (affected by FSRS)". It is unrelated to stage.

**Comment by Expertium** [comment]
> The subtitle has said that "calculated for cards with custom data (affected by FSRS)". It is unrelated to stage.

It is though. Average Retention and Average Stability can be calculated only for cards in the "review" stage, but Burden can be calculated for any card that has been reviewed at least once.

**Comment by L-M-Sherlock** [comment]
> Average Retention and Average Stability can be calculated only for cards in the "review" stage

The current implementation has calculated the stability and retention for learning cards.

**Comment by Expertium** [comment]
Interesting, I didn't know that. Anyway, I think the retention graph is fine, so you can close this issue.
