### ISSUE TITLE
[Bug] True Retention table is empty under certain condition

### ISSUE THREAD

**Issue by nb9618** [open-spaced-repetition/fsrs4anki-helper#190]
### Steps to reproduce

Launch Anki. Without doing anything else, Shift-click on Stats to bring up the old stats window for the current deck.

### Expected result

True Retention table would display relevant stats.

### Actual result

The table displays `0`'s and `N/A`'s. Note: FSRS Stats section above is filled properly.

### Additional info

This bug is present in the original add-on as well.

It would appear as if the add-on keeps its own notion of what is the current deck, which is null at start-up and gets updated once the deck is changed or the user enters the study screen.

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/137687989/18f1d8fc-e457-464c-859a-ec44943e0df7)

**Comment by L-M-Sherlock** [comment]
Could you share your collection with me?

**Comment by nb9618** [comment]
I have sent it to you by e-mail. Could you check that it was delivered? On my first attempt it was refused because it was suspected as spam.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/461f162e-0ef5-4d9d-b0f1-3df72003703e)

**Comment by nb9618** [comment]
I didn't attach the file on the second try, sorry. It seems that the message is rejected when a file is attached. I'll try to upload it somewhere and will send you a link.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12385565/fsrs4anki-helper.zip)

Have a try.

**Comment by nb9618** [comment]
It works, many thanks!
