### ISSUE TITLE
[Feature request] Change layout of the stats for easier readability

### ISSUE THREAD

**Issue by nb9618** [open-spaced-repetition/fsrs4anki-helper#191]
I suggest to re-arrange the data presented in the Stats window.

Currently, True Retention table is below FSRS Stats and their interpretation. On smaller displays, it requires scrolling to see it. However, I personally find it the single most useful piece of information on the entire old Stats window (other built-in statistics are better presented on the new window, which is unfortunately not available for modification by add-ons).

I think it would be better to move the table to the top, above FSRS Stats. Incidentally, this was the arrangement when I had the original True Retention add-on installed, although I don't know what defines the order for different add-ons.

Additionally, I think that the Interpretation section is better to be collapsed by default and displayed after the user clicks on it's heading (or some other kind of link or button), since it occupies significant space and is not really necessary once the user gets used to meanings.

**Comment by L-M-Sherlock** [comment]
OK. I will put True Retention table above FSRS Stats.

But I don't know how to collapse the Interpretation section. Do you have any example?

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/e70e594d-7b63-4eb0-8ca5-5221fca193ba)

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12385432/fsrs4anki-helper.zip)

**Comment by nb9618** [comment]
I was going to suggest something like this
```python
    interpretation = "<h3 onclick=\"document.getElementById('interpretation').style.display='block';\">Interpretation</h3>" \
        + "<ul id=\"interpretation\" style=\"display: none;\">" \
        ....
```
but your solution is better.
The patch is just as I hoped, thank you!
