### ISSUE TITLE
[Enhancement] Consider (re)learning cards in retention stats

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#198]
> The original true retention add-on decides whether to include a card in the stats or not based on whether it is a learning card or a review card. But, in my opinion, there is no difference between a learning card having a 3-day interval and a review card having a 3-day interval.
> 
> So, wouldn't it be better to filter cards based on their interval (such that all cards with intervals more than or equal to 1 day are included) rather than filtering them based on whether they are learning cards or review cards.

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/170#issuecomment-1671779335_

The importance of the implementing the above suggestion is evident in the following screenshots.

<img width="460" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/c2c77a78-8276-4144-ab98-36d91589f61f"><img width="506" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/8f382715-9e58-466b-94a3-251fec7d0a50">

Before I switched to FSRS, a majority of my daily reviews consisted of (re)learning cards because I used long (re)learning steps. If the helper add-on doesn't show these reviews, the result obtained is misleading.

By the way, there is a typo in the word "Retention" at three places in the above screenshot.

**Comment by L-M-Sherlock** [comment]
How about only considering the (re)learning cards with interval longer or equal to one day?

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12395262/fsrs4anki-helper.zip)

Have a try.

**Comment by user1823** [comment]
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12395262/fsrs4anki-helper.zip)

This patch didn't fix the problem completely. The result:
<img width="499" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/92206575/38652491-08a9-4f10-a87b-842cf33bbb3e">

Then, I made a further change, which seems to fix the problem. The result:
<img width="504" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/1f13190f-a9db-46fc-be75-da006f6ead38">

I have made a PR with the above change. Please review.

Also, can a similar approach be used in the following table? I tried but couldn't understand how to do it.
<img width="576" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/b9fc5f0b-e5f1-406b-886b-f3ccb799b8fe">

**Comment by user1823** [comment]
> How about only considering the (re)learning cards with interval longer or equal to one day?

By the way, this is exactly what I advised you to do in my original post. I think that you misunderstood it.

**Comment by user1823** [comment]
Also, the reason your solution didn't work was that the interval is negative and in seconds for (re)learning cards only in the v2 scheduler. In the v3 scheduler, it is in days and positive. I first mentioned this here: https://github.com/open-spaced-repetition/fsrs4anki/issues/326#issuecomment-1613486663

**Comment by user1823** [comment]
> Also, can a similar approach be used in the following table? I tried but couldn't understand how to do it.
> <img width="576" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/b9fc5f0b-e5f1-406b-886b-f3ccb799b8fe">

@L-M-Sherlock, this question still requires your attention.

**Comment by L-M-Sherlock** [comment]
Here is the related code, which is copied from true retention add-on:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/e5a107791343a18f8641f62d7e036771bd0fbfb8/stats.py#L272-L286

**Comment by user1823** [comment]
> Also, can a similar approach be used in the following table?

So, I fixed this too.

Before:
<img width="576" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/b9fc5f0b-e5f1-406b-886b-f3ccb799b8fe">

After changing the counts for pass/fail only:
<img width="572" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/fc52cd19-1408-48ba-b619-2bcf1774ca5a">

After changing the graduated/relearned counts too:
<img width="848" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/21c3aea7-544a-4b5c-875a-8107a747da47">

PR: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/200
