### ISSUE TITLE
Rescheduling cards which were marked "easy" during the learning stage

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#20]
Sometimes, I use the "easy" button to push some learning cards far off when I think I know them well enough. But the helper decreases their interval back to a small value. Two such cards (one affected, one unaffected) are shared below. Can something be done for this?

<img width="50%" src="https://user-images.githubusercontent.com/92206575/218262255-3f34bdcb-2046-4a22-95fe-24f94d9efb5a.jpg">
<img width="50%" src="https://user-images.githubusercontent.com/92206575/218262646-df717475-fe56-4184-963a-61a7673dbb03.jpg">

**Comment by L-M-Sherlock** [comment]
> Sometimes, I use the "easy" button to push some learning cards far off when I think I know them well enough. But the helper decreases their interval back to a small value. Two such cards (one affected, one unaffected) are shared below. Can something be done for this?

Could you give me your parameters to evaluate the interval? It would be great if you could provide the analysis results in the optimizer.

**Comment by user1823** [comment]
My settings are as follows:

- w = [1.0813, 1.5326, 5.0874, -1.1416, -1.1778, 0.0161, 1.6118, -0.0405, 0.992, 1.7511, -0.4642, 0.9, 0.6785]
- requestRetention = 0.94
- FSRS4Anki v3.13.4

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/218267878-1e5b9711-95a3-4579-9b29-934674d420f4.png)

Its stability is 6.2 (which means the interval for 90% retention is 6.2 days).

**Comment by L-M-Sherlock** [comment]
If you want to let the `easy` has a large effect on the interval, you could modify the easyBonus:

![image](https://user-images.githubusercontent.com/32575846/218268016-c7700db7-be71-4f61-8a52-15ed3938981f.png)

1.5 or more

**Comment by user1823** [comment]
> If you want to let the `easy` has a large effect on the interval, you could modify the easyBonus:

I get your point. But, this would work for new cards I start doing with FSRS. I am talking about the cards I did earlier and I am now rescheduling with the Helper.

**Comment by L-M-Sherlock** [comment]
> But, this would work for new cards I start doing with FSRS.

It also works for cards whose latest rating is `easy` when you reschedule them with Helper.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/fc28dcee61fd6d1580078da05aca609e37d94e7e/reschedule.py#L191
