### ISSUE TITLE
[BUG] Cards are being reschedule to a freeday 

### ISSUE THREAD

**Issue by pedrohtbrum** [open-spaced-repetition/fsrs4anki-helper#206]
I'm using this addon to free my sundays from ankis, but there area card being schedule to this day. I don't know if I am doing something wrong, but as long as I love this addon, i felt i should tell you that this is happening. 

<img width="632" alt="Captura de Tela 2023-08-26 às 13 17 23" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/6110e6d7-e14a-456b-b4c2-4fec78150143">
<img width="800" alt="Captura de Tela 2023-08-26 às 13 17 15" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/e92ad5ec-b9a1-4262-b2cf-26679ea1de15">

i'm sending my screenshots, but if you need more thing, please let me know. 

Thank you for your time and dedication!

have a great week.

**Comment by L-M-Sherlock** [comment]
Could you share some cards' info due in that day?

**Comment by pedrohtbrum** [comment]
Sure. I sent you some screenshots from some cards that are due tomorrow. I already sent some cards with including scheduling information. If i could help with anything else, please let me know.

PS: the cards are in portuguese, but i don't think thats changes somethintg...

<img width="707" alt="Captura de Tela 2023-08-26 às 15 12 50" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/005dc900-1d44-4121-b319-f2ca25ae6cd0">
<img width="874" alt="Captura de Tela 2023-08-26 às 15 12 35" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/a
[Selected Notes.apkg.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12446481/Selected.Notes.apkg.zip)
ssets/143281489/f2f64ee3-a77e-4d07-a8f1-0213072db7e4">
<img width="865" alt="Captura de Tela 2023-08-26 às 15 12 09" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/12e2224c-ef40-4fe0-b69d-b8e314524f99">
<img width="870" alt="Captura de Tela 2023-08-26 às 15 12 00" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/7d2a4959-6b5f-4dd8-882f-cb736076f915">
<img width="880" alt="Captura de Tela 2023-08-26 às 15 11 46" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/11d03c97-7c47-41a5-93cb-8daaa3540654">
<img width="872" alt="Captura de Tela 2023-08-26 às 15 11 38" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/de97cae1-af94-41f1-ad89-b55cf3104470">
<img width="872" alt="Captura de Tela 2023-08-26 às 15 11 26" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/e007ce07-4e81-4f01-9047-0ca2be6d173b">
<img width="879" alt="Captura de Tela 2023-08-26 às 15 11 13" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/143281489/8de90721-e0e7-4f37-b6d8-e632c1122c1e">

**Comment by L-M-Sherlock** [comment]
`Free days` only works for review cards. Your cards are in learning/relearning stages.

**Comment by pedrohtbrum** [comment]
Ok, thank you

**Comment by user1823** [comment]
> `Free days` only works for review cards. Your cards are in learning/relearning stages.

@L-M-Sherlock, please add this to the README to prevent similar questions from other users.
