### ISSUE TITLE
[BUG] Reschedule has become slower

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#211]
Scheduler has slowed down:

Before this latest update, when I ran HELPER, it would complete the rescheduling instantly.
Now it's taking between 2 to 3 seconds. It may seem small, but it's noticeable that something has changed.

**Comment by L-M-Sherlock** [comment]
Scheduler? Do you mean reschedule or disperse siblings?

**Comment by cjdduarte** [comment]
Sorry for my translation. My language is PT-BR.
It's when I reschedule.

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/2834b05e-575c-4d70-b4da-546a9b44f5d7)

**Comment by cjdduarte** [comment]
Actually, I believe you have released 2 or 3 updates since the last time I ran the rescheduler.
So it could have been caused by one of the last 3 updates.

**Comment by L-M-Sherlock** [comment]
Recent changes didn't affect the main process of rescheduling. Do you enable load balance?

**Comment by cjdduarte** [comment]
No. The test I did was exactly like this:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/42243532/a2a8915d-6d8c-4f2b-ae4f-b3b5d489d361)

**Comment by wagewarsgetrichdiegoncharov** [comment]
I did update FSRS Helper yesterday, and I'm also noticing that the Rescheduler seems much slower. Unfortunately, I'm not sure when I last updated, so I might have been a couple updates behind.

But, on my large (70k card) collection, Reschedule All used to take ~10 minutes, and this morning it's been running for 25 minutes and only 18k cards rescheduled so far.

**Comment by L-M-Sherlock** [comment]
> Reschedule All used to take ~10 minutes,

Do you enable load balance?

**Comment by L-M-Sherlock** [comment]
@cjdduarte, I have reverted to the first version of helper which supported FSRS v4. But the performance is the same as the latest version. Could you share your collection for test?

**Comment by L-M-Sherlock** [comment]
@wagewarsgetrichdiegoncharov, could you send your collection file to me? I can compare the performance in your large collection.

**Comment by cjdduarte** [comment]
> @cjdduarte, I have reverted to the first version of helper which supported FSRS v4. But the performance is the same as the latest version. Could you share your collection for test?

Sorry, I just saw your comment now.
When you say you reverted the code, do you mean in the production environment?

**Comment by L-M-Sherlock** [comment]
I checkout different commits in my local device.

**Comment by cjdduarte** [comment]
For my part, with the change to version 23.10, it no longer makes sense to investigate this.
