### ISSUE TITLE
[BUG] New search query parameters (D, S, R) don't work with the OR operator

### ISSUE THREAD

**Issue by foxness** [open-spaced-repetition/fsrs4anki-helper#212]
**Bug description**
Trying to use any of the new search query parameters (D, S, R) in the browser search box with the **OR operator** produces the **Invalid Search** error. For example, I want to find cards that either have more than 4 lapses or a stability of less than 5 days, so I search for `prop:lapses>4 OR s<5` which results in an error. If I change the **OR** to an **AND operator** (aka `prop:lapses>4 s<5`), everything works fine but that's not what I want to find.

Full text of the error: 

> Invalid search: ⁨an or was found but it is not connecting two search terms. If you want to search for the word itself, wrap it in double quotes: "or".⁩

Another form of this bug does not even produce an error but still results in erroneous search results. For example, the search query `prop:lapses>4 (s<5 OR prop:ease>2.5)` **does not** produce an error but still displays incorrect cards. I have cards that have more than 4 lapses, less than 5 days of stability and less than 2.5 ease (I know Ease is irrelevant/obsolete when you have FSRS but just to demonstrate the point) but they don't come up with this query, effectively making the results of this query the same as `prop:lapses>4 prop:ease>2.5` which is definitely a bug.

**To Reproduce**
1. Go to Anki Browser
2. Type `prop:lapses>4 OR s<5` in the search box
3. Press Enter
4. Observe an annoying error

**Expected behavior**
The search query with the new parameters and an OR operator **does not** produce an error.

**Screenshots**
<img width="718" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/13183626/6fada8d0-5a44-46cb-b6ab-7f4b0f33bd12">

<img width="755" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/13183626/482bd356-c033-4518-9104-750845ccb45f">

<img width="730" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/13183626/98becfb5-3fdc-4f44-9cab-2cf2fac0f397">

<img width="496" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/13183626/bb4852c0-953c-422c-b4ba-80c1f1604083">

**Environment**
 - Anki version: 2.1.65 (aa9a734f)⁩
 - OS: macOS 13.4
 - FSRS4Anki Helper: newest (as of 2023-08-29)
 - Scheduler version: v4.5.6
 - Optimizer version: v.4.5.6
 - Simulator version: not used

**Additional context**
Disabling BetterSearch and Advanced Browser addons does not help.

p.s. I am aware that **Straight Reward** is incompatible with FSRS but I still have it for my decks that do not use FSRS. I also leave it on even for FSRS decks to see what my ease values would look like had I never switched to FSRS (basically I leave it on for fun and looking at pointless stats). It doesn't break anything, right?

**Comment by L-M-Sherlock** [comment]
Please use prop:cdn:s>5, which is supported by Anki's built-in query.

**Comment by foxness** [comment]
Thanks, `prop:cdn:s>5` seems to be working. Is there any difference between that and `s>5`? Also I noticed that `prop:cdn:r>0.8` does not work at all.

**Comment by L-M-Sherlock** [comment]
s>5 is implemented by the add-on, which is not tested enough. prop:can:s>5 is implemented by Anki itself.

**Comment by user1823** [comment]
> Also I noticed that prop:cdn:r>0.8 does not work at all

The reason is that Anki doesn't know the formulas of FSRS. So, it shows the cards with r > 0.8 when it was last reviewed. But, obviously, this is not helpful at all.

**Comment by L-M-Sherlock** [comment]
The current search query of FSRS doesn't support `OR` and `AND`, because the add-on couldn't hack into the Rust code of Anki. So the helper add-on only could apply its query based on the search result of Anki built-in query. So it could only filter the result (equal to `AND` operator).
