### ISSUE TITLE
[Feature Request] Estimation total knowledge based on notes

### ISSUE THREAD

**Issue by filipenanclarez** [open-spaced-repetition/fsrs4anki-helper#214]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
In open-spaced-repetition/fsrs4anki#202 you create some useful stats. I want to request to add one more. The "Estimation total knowledge based on notes". 

**Describe the solution you'd like**
A note based stats to help user know how many notes he know today.

**Describe alternatives you've considered**
Currently I divide the value in "Estimated knowledge cards" by the total number of cards

**Additional context**
My vocabulary decks have 6 cards per note, at the beginning I ask:
- Ideogram (the user must know what it means)
- Audio (user must hear and understand the meaning)
- Word in native language (user must know how to say it in target language)
- Phrase in ideogram (same word)
- Phrase audio (the same as the word)
- Phrase in the original language (even of the word)
After that, the user effectively knows this vocabulary, as he knows the 6 aspects of this word.
So how can I know how many vocabularies I know completely?
I currently divide the value in “Estimated Known Cards” by the total number of cards
But if the number of decks has a different number of cards per grade, then this math seems to be difficult.

**Comment by L-M-Sherlock** [comment]
I have a question. If a note has two cards, there are two different case:

1. One of them is new card, and the other is a review card with R = 90%.
2. Both are review cards with R = 90%

What's the total knowledge based on note in these cases?

**Comment by filipenanclarez** [comment]
> 

How is the total shown on the stats screen currently being calculated for this case? 90%?

Is the same here...

**Comment by L-M-Sherlock** [comment]
In the first case, the current implementation will output 0.9. In the second, it will output 1.8.

**Comment by filipenanclarez** [comment]
> In the first case, the current implementation will output 0.9. In the second, it will output 1.8.

I'm confuse now... whats is the second case?

**Comment by L-M-Sherlock** [comment]
> 1.8 means 180% of R ?

Estimation total knowledge based on cards is the summation of retrievability of all cards in collection.

**Comment by filipenanclarez** [comment]
> 

Yes, so, how you know i have 82 cards in this?

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/27212546/60527e6f-55dd-4671-b05b-2ed15426fa8c)

**Comment by filipenanclarez** [comment]
> > 
> 
> Yes, so, how you know i have 82 cards in this?
> 
> ![image](https://user-images.githubusercontent.com/27212546/265566794-60527e6f-55dd-4671-b05b-2ed15426fa8c.png)

Witch R make the card is counted ?

**Comment by L-M-Sherlock** [comment]
Here is the related code:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/465bd4c3fae06da1a0650f6430ffff1850c620ec/stats.py#L18-L46

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/465bd4c3fae06da1a0650f6430ffff1850c620ec/stats.py#L53-L66

**Comment by user1823** [comment]
> I have a question. If a note has two cards, there are two different case:
> 
> 1. One of them is new card, and the other is a review card with R = 90%.
> 2. Both are review cards with R = 90%
> 
> What's the total knowledge based on note in these cases?

I think that @filipenanclarez has given a reasonable answer. His answer:

> If you have a 3 cards, in a note. One with 90%, another with 80% and another with 70%. So the average of "Average retention" of this note is 80%.

For the specific question asked by you (one card is a new card, and the other has R = 90%), the average R can be taken as 45% (i.e., assume that new cards have 0 R).

Regarding the presentation of the results, I think that you can present it something like this:

- Count: 100 cards (50 notes)
- Estimated total knowledge: 96 cards (42 notes)

**Comment by user1823** [comment]
@L-M-Sherlock, do you plan to implement it? In my opinion, the requested stat is useful.

Also, I wanted to share my idea for implementing this.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/a85b906e594076c8c936a3c6bb8b1ffa0007c400/stats.py#L18-L46

Here, after line 30, add the `number of cards in the same note`, which would become x[3].

Then,
```py
estimated_total_knowledge_notes = sum(item[0]/item[3] for item in retention_stability_burden_list)
```

Obviously, you will need to add `x[3]` after `1/max(1, x[2])` in `retention_stability_burden_list`.

By the way, also move the following line to the above function
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/a85b906e594076c8c936a3c6bb8b1ffa0007c400/stats.py#L59
as
```py
    return recall_sum / cnt, stability_sum / cnt, burden_sum, cnt, round(recall_sum)
```

**Comment by L-M-Sherlock** [comment]
> Here, after line 30, add the `number of cards in the same note`, which would become x[3]. By the way, if you can tell me how to do this, I will do all the rest on my own.

I need to do some research here.

**Comment by L-M-Sherlock** [comment]
patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12565518/fsrs4anki-helper.zip)

**Comment by user1823** [comment]
It seems to work well. Thanks!

<img width="345" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/f140569c-69ba-4e2a-84ad-c84c8d74a240">

It would be better if you can add notes to the "Count" also.

To do this, you can use `nid` as `x[4]`.

Then, count_notes = len_distinct(item[4] for item in retention_stability_burden_list)

len_distinct is not an actual function but you get the idea. Replace it with the actual function.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12565582/fsrs4anki-helper.zip)

**Comment by user1823** [comment]
Perfect!

<img width="337" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/effc3c09-5547-4982-adaf-700ec087eb19">

**Comment by filipenanclarez** [comment]
Can you make a little improvement on output format? 

By Cards: 
Count: 100
Estimated Knowkedge: 90 (90%)

By Notes: 
Count: 50
Estimated Knowkedge: 25 (50%)

**Comment by L-M-Sherlock** [comment]
I have updated the add-on three times in the same day. It's annoying for users. Please provide a final version. And PR is welcomed.

**Comment by user1823** [comment]
> I have updated the add-on three times in the same day. It's annoying for users.

Well, for the same reason, I advised you long ago to not update the add-on on AnkiWeb as soon as a commit is added to the repo.
- If it is a bug fix, it makes sense to update immediately.
- But, if it is something minor (such as the PR linked with this issue), you can let commits accumulate and update, say, once a week.

**Comment by filipenanclarez** [comment]
> I have updated the add-on three times in the same day. It's annoying for users. Please provide a final version. And PR is welcomed.

Sorry for that, it’s only a little suggestion.

Thank you so much for your effort to do this and spend your time in this project.

**Comment by user1823** [comment]
> Can you make a little improvement on output format?

@filipenanclarez, from your GitHub profile, it appears that you are a developer. So, it would be great if you could make a PR for the requested improvement.

@L-M-Sherlock is somewhat busy these days because he is involved in integrating FSRS into vanilla Anki.

**Comment by filipenanclarez** [comment]
> > Can you make a little improvement on output format?
> 
> @filipenanclarez, from your GitHub profile, it appears that you are a developer. So, it would be great if you could make a PR for the requested improvement.
> 
> @L-M-Sherlock is somewhat busy these days because he is involved in integrating FSRS into vanilla Anki.

Yep, 

I'm in a travel in this weekend, without my computer. After this, I'll look this code and try to do this change and submit as PR 

Thank you too for your help in this thread 

Regards

**Comment by filipenanclarez** [comment]
> > Can you make a little improvement on output format?
> 
> @filipenanclarez, from your GitHub profile, it appears that you are a developer. So, it would be great if you could make a PR for the requested improvement.
> 
> @L-M-Sherlock is somewhat busy these days because he is involved in integrating FSRS into vanilla Anki.

Here the PR: #232 

[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12590982/fsrs4anki-helper.zip)

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/27212546/d642e162-ac1d-4aa0-a8ab-c6fd228dea2b)
