### ISSUE TITLE
[Feature Request] Possibility to turn off all of the fsrs stats

### ISSUE THREAD

**Issue by estherkl** [open-spaced-repetition/fsrs4anki-helper#224]
First of all I really love fsrs Anki. It helps a lot when learning and I really appreciate the work you put into it!

**Which module is related to your feature request?**
Helper

**Is your feature request related to a problem? Please describe.**
The helper Add-on adds a lot of graphs, tables and other stats to the stats window. I know that some really love the stats the helper add on adds but for me there is to much going on in the stats window.

**Describe the solution you'd like**
Add the possibility to turn off the stats that the helper adds.

Thank you for considering my feature request :)

**Comment by user1823** [comment]
The FSRS stats are only shown when Shift clicking the Stats button.

If you don't want to see the FSRS stats, you can just click the Stats button without holding the Shift key.

**Comment by estherkl** [comment]
Yesss, there is another add on for the Stats which I use which also uses the old Stats window. That is why I always hold the Shift key when I click the stats button :)

**Comment by L-M-Sherlock** [comment]
OK. I can add an option in the config of add-on to enable/disable FSRS stats.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12575603/fsrs4anki-helper.zip)

You can disable FSRS stats in the config:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/4426cdad-1006-4b6d-b62a-8484e084042b)

**Comment by estherkl** [comment]
yess, it works. Thank you so much!
