### ISSUE TITLE
[BUG] stacktrace on next card

### ISSUE THREAD

**Issue by ilya-rusyanov** [open-spaced-repetition/fsrs4anki-helper#225]
**Describe the bug**
Once a week or two I get the following stacktrace when rating a card. 'Auto reschedule the card after each review' is on.

**To Reproduce**
1. Repeat cards as usual
2. Reveal backward of a card
3. Rate it and get stacktrace. I possibly accidentally press left ctrl button of keyboard along with rating(1-4), still could not figure if that is the case and actually happening or not :( Card rating is performed form keyboard as well

Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.1.0-0.deb11.11-amd64-x86_64-with-glibc2.31
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-11 09:51:39
Причиной могли послужить: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 465, in after_answer
  File "aqt.reviewer", line 478, in _after_answering
  File "_aqt.hooks", line 4078, in __call__
  File "/home/rusyanov/.local/share/Anki2/addons21/759844606/schedule/__init__.py", line 7, in reschedule_and_disperse_siblings_when_review
    undo_entry = reschedule_when_review(reviewer, card, ease)
  File "/home/rusyanov/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 546, in reschedule_when_review
    mw.col.update_card(card)
  File "anki.collection", line 529, in update_card
  File "anki.collection", line 523, in update_cards
  File "anki.collection", line 523, in <listcomp>
AttributeError: 'NoneType' object has no attribute '_to_backend_card'

**Expected behavior**

**Screenshots**

![изображение](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1244545/e47a7700-da09-4051-9cd2-8ae144dde18d)

**Environment**
 - Anki version: 2.1.66
 - OS: Debian 11.7
 - Scheduler version: 4.3.0
 - Helper version: most recent, but also happened to previous versions as well
 - Optimizer version: don't remember
 - Simulator version: does not matter

**Additional context**

**Comment by L-M-Sherlock** [comment]
Could you share the affected card with me?

**Comment by L-M-Sherlock** [comment]
Why the first review log's type is review? It should be learning. I guess this induce the error.

**Comment by ilya-rusyanov** [comment]
To be honest, I do not remember :( Never used any special plugins for scheduling or something like that. Possibly I've manually scheduled it without learning process. But in that case it should have been 'manual' first entry in the log.

**Comment by L-M-Sherlock** [comment]
OK. I will fix it tonight. You can disable `Auto reschedule the card after each review` before I fixed it.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12575653/fsrs4anki-helper.zip)

It would solve your problem.

**Comment by ilya-rusyanov** [comment]
Thank you but I have no idea how to test it. Since rescheduling that card does not give the stacktrace anymore even without the update. I think that's because manual rescheduling appears in the card history

**Comment by L-M-Sherlock** [comment]
OK. I merge it now. If you still meet this problem, please report here.
