### ISSUE TITLE
[BUG]Using the helper's own update scheduler will overwrite the original personalization parameters.

### ISSUE THREAD

**Issue by Azazel177** [open-spaced-repetition/fsrs4anki-helper#233]
**Describe the bug**
使用helper自带update scheduler会覆盖原有的个性化参数

**Environment**
 - Anki version: 2.1.65 (aa9a734f)⁩
 - OS: MacOS 12.6.5
 - Scheduler version: v4.5.6

**Comment by L-M-Sherlock** [comment]
你之前是什么版本？

**Comment by Azazel177** [comment]
> 你之前是什么版本？如果是从 v3 升上来的，那旧参数是不兼容的，所以会替换成 v4 默认参数。

之前是4.3.0，现在已经重新生成了下参数

**Comment by L-M-Sherlock** [comment]
如果可以的话，希望提供一下升级前的 custom scheduling 代码，我研究复现一下

**Comment by Azazel177** [comment]
是这个吗
[0.2454, 2.1302, 2.2698, 2.2698, 5.1781, 1.1899, 0.7309, 0.0, 1.2324, 0.1, 0.6794, 2.1249, 0.0993, 0.2741, 1.2742, 0.1167, 2.3511]

**Comment by L-M-Sherlock** [comment]
我是说完整的所有代码

**Comment by Azazel177** [comment]
我重新用了4.3.0的代码和之前个性化参数进行升级,问题没有复现,应该是我之前操作不当

**Comment by L-M-Sherlock** [comment]
好的，那我先关闭这个问题了。
