### ISSUE TITLE
[Question] Why is estimated total knowledge so much lower for notes than for cards?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#236]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
Why are these percentages so different for notes and cards? I thought that R for a note was just the average of R for its cards.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/cc8d41f7-2a9d-4339-a6bd-b77b75cb8a2c)

**Comment by user1823** [comment]
It likely means that you have several notes where one card is a review card and the other card is a new card. (Average of 0.9 & 0 is 0.45)
