### ISSUE TITLE
[Enhancement] Add option to not increase today's review count after rescheduling

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#24]
Every day, I run FSRS helper to reschedule my cards after I have finished reviewing them (because I do most of my reviews on AnkiDroid).

Since at that time, the number of cards due on that day is 0, the helper increases the number of cards due (possibly because I have also enabled load balancer).

Please add an option (or make it default) to prevent the helper from adding more due cards that day.

**Comment by L-M-Sherlock** [comment]
Do you mean that today could be skipped when rescheduling with load balance?

**Comment by user1823** [comment]
> Do you mean that today could be skipped when rescheduling with load balance?

I am not sure what you mean by this.

What I want to say is as follows:
The number of cards that are due today (or any day in the past) should not increase.

The rationale behind this is as follows:
I have already reviewed the cards due on those days. With the current code, the helper is bringing the cards that due in the future to today, yesterday or to other days in the past. This is because the number of cards due on those days is 0 and the number of cards due on future days > 0. So, the helper tries to move the cards from the future to the past to make the curves smoother.

Note that I have not studied the code extensively and the some of the above rationale is based on assumptions. Please correct me if I am wrong anywhere.

**Comment by ag163** [comment]
我开了负载平衡和自由周末，但它在那一天还是有安排卡片，请问这是怎么回事？

**Comment by L-M-Sherlock** [comment]
> 我开了负载平衡和自由周末，但它在那一天还是有安排卡片，请问这是怎么回事？

你使用 reschedule 了吗？

**Comment by L-M-Sherlock** [comment]
Could you update the helper add-on and give it a try? I hope the latest version solves this issue.

**Comment by user1823** [comment]
I did a test by rescheduling all cards using the latest version of the helper add-on. I got the following results:
![image](https://user-images.githubusercontent.com/92206575/222965117-d8e51d41-fae2-49ae-b347-1d7680888f54.png)

Now, my question is **why there is one card due on the day --**? Shouldn't that card be rescheduled to some other day? Its interval is close to a month. So, it could be easily shifted to yesterday or today.
Here is the card info of that card:
![Untitled](https://user-images.githubusercontent.com/92206575/222965495-7bd9a3f7-dcac-4a4d-99b7-36c0fa757c21.jpg)

**Comment by L-M-Sherlock** [comment]
Could you reschedule all cards again? The rescheduling doesn't guarantee the perfect load balance at one time.

**Comment by user1823** [comment]
I rescheduled my cards again. The result is as follows:
<img src="https://user-images.githubusercontent.com/92206575/222967299-800c5946-a7a7-4441-b605-7b73d643ae2c.png">

**Comment by L-M-Sherlock** [comment]
😂so weird. Debugging the code per line with the same collection could be helpful to find out the problem. Do you accept the current behavior of the load balance? If not, I will do more research on this problem.

**Comment by user1823** [comment]
I accept the current behavior of the load balance because I won't be rescheduling all the cards very frequently (because the option to only reschedule the recently studied cards has been implemented).

So, I am closing this issue.

**Comment by user1823** [comment]
But, if you still want to investigate this issue, here is a copy of my deck: [Default.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10892239/Default.zip)

Note 1: Before using, rename it to change `.zip` to `.apkg`
Note 2: I have deliberately blanked out the fields but the scheduling information is preserved.

**Comment by ThisIsntTheWay** [comment]
I am sorry for writing in a closed issue, but I would still welcome this sort of enhancement.  
Right now, if I reschedule cards (with load balancer and fuzz active), I get ~1'000 cards due, kind of defeating its purpose.  

I remember the rescheduling function not doing that in an earlier version (I think with FSRS v3.9.6).
