### ISSUE TITLE
[Question] Is the helper compatible with new Anki build-in FSRS support?

### ISSUE THREAD

**Issue by szalejot** [open-spaced-repetition/fsrs4anki-helper#245]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
The new version of Anki, 23.10 Beta 1, has built-in FSRS support.
Is the helper compatible with the new Anki built-in FSRS support? I am most interested if the "Auto reschedule cards reviewed on other devices after sync" will still work, as I am doing a majority of my reviews on Ankidroid.

**Comment by L-M-Sherlock** [comment]
Yeah, it is compatible. Please check updates for the helper add-on.

**Comment by szalejot** [comment]
Great! Should I remove the custom scheduling code before turning on the built-in FSRS?

**Comment by L-M-Sherlock** [comment]
Yap. Please follow the instructions on the Anki's release page.

**Comment by szalejot** [comment]
Well, it seems like it doesn't work.
I just updated to Anki 23.10 Beta 1. Checked updates for helper and it said, that the version I have is the newest one.
I've done some reviews on Ankidroid. Opened Anki and was greeted by the error message: "Please paste the code of FSRS4Anki into custom scheduling at the bottom of the deck options screen."

**Comment by szalejot** [comment]
The same error when reviewing with the option "Auto reschedule the card you just reviewed" turned on.

**Comment by L-M-Sherlock** [comment]
Could you give me the screenshot of your add-on windows?

**Comment by szalejot** [comment]
Here it is:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/3840404/9d996611-ee97-461d-a6f4-5b7a68d29841)

**Comment by szalejot** [comment]
I've disabled all add-ons except the Helper and restarted Anki. Still not working.

**Comment by L-M-Sherlock** [comment]
It seems a problem of AnkiWeb. @dae, I find that the user could update FSRS4Anki Helper add-on to the latest version.

**Comment by L-M-Sherlock** [comment]
> I've disabled all add-ons except the Helper and restarted Anki. Still not working.

An temporary solution: uninstall FSRS4Anki Helper add-on and reinstall it.

**Comment by szalejot** [comment]
After reinstalling it throws an error during review:

Debug info:
Anki 23.10 (1f6938d7) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-24 11:01:45
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "aqt.taskman", line 102, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 463, in after_answer
  File "aqt.reviewer", line 476, in _after_answering
  File "_aqt.hooks", line 4111, in __call__
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\__init__.py", line 6, in reschedule_and_disperse_siblings_when_review
    disperse_siblings_when_review(reviewer, card, ease)
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 339, in disperse_siblings_when_review
    "r": deck_config["desiredRetention"],
KeyError: 'desiredRetention'

**Comment by dae** [comment]
Re not updating: sounds like a bug - will look into this tomorrow.

**Comment by szalejot** [comment]
I don't know if this is related, but in the browser I see, that some cards have in the "Target R" field the following value: `'NoneType' object has no attribute 'stability'`
These could be the cards I reviewed in Ankidroid. I am using 2.17alpha1 version - the only 2.17 version I've found on the releases page.

**Comment by L-M-Sherlock** [comment]
@szalejot, could you share your collection file with me? It would be helpful for debugging.

**Comment by szalejot** [comment]
My collection export, without media: https://drive.google.com/file/d/1I_FlEjkSbMk3XQ5dmZIUeD2PNoBPzq1_/view?usp=sharing

**Comment by L-M-Sherlock** [comment]
```
id: 1694525402509
name: "langotalk::langotalk plus"
{
    "id": 1694525402509,
    "mod": 1694812616,
    "name": "langotalk::langotalk plus",
    "usn": 33500,
    "lrnToday": [0, 0],
    "revToday": [0, 0],
    "newToday": [0, 0],
    "timeToday": [0, 0],
    "collapsed": True,
    "browserCollapsed": True,
    "desc": "",
    "dyn": 1,
    "resched": True,
    "terms": [["deck:langotalk", 1, 0]],
    "separate": True,
    "delays": None,
    "previewDelay": 10,
}
```

I find that this deck's config doesn't contain the keys `desiredRetention` and `fsrsWeights`. @dae, is it valid?

**Comment by L-M-Sherlock** [comment]
Oh, it's a filtered deck.

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/8ac9273d-5396-46b5-8930-ec5b1fdfd1b4)

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/a74e1563-7321-4d10-96a6-5a1eaa55915d)

This card doesn't have memory state. @dae

**Comment by szalejot** [comment]
I am 90% certain, that this card last review was on Ankidroid.

**Comment by L-M-Sherlock** [comment]
Please check updates. I submit a patch for fixing it.

**Comment by szalejot** [comment]
It worked now :-)

**Comment by Expertium** [comment]
> Yap. Please follow the instructions on the Anki's release page.

It doesn't say that you have to remove the scheduler code, but ok, I removed it.

**Comment by L-M-Sherlock** [comment]
It said that if you have previously used FSRS, please delete the text in the custom scheduling section before enabling FSRS.

<img width="899" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/c007d63b-6455-469c-ad96-f9e49211175a">

**Comment by Expertium** [comment]
Ok, my bad. Question: will Advance and Postpone be supported natively?

**Comment by L-M-Sherlock** [comment]
I guess so. Advance and Postpone are easier than load balance and disperse siblings to integrate.

**Comment by Expertium** [comment]
So Load balance and Disperse siblings are unlikely to be integrated into Anki?

**Comment by L-M-Sherlock** [comment]
In the long term, they all will be integrated into Anki. But it requires more works. I only maintain this project in my available time.

**Comment by dae** [comment]
- I didn't get to the update issue today; will try to look into it tomorrow.
- PRs that add more useful stats are welcome
- Re the bulk-rescheduling options: my main concern is not creating more work for AnkiWeb than is necessary. Such actions should be conservative about modifying cards; I don't want them to be marking every card in the collection modified when not strictly necessary, as that makes the sync burden heavier.

**Comment by dae** [comment]
> I am 90% certain, that this card last review was on Ankidroid.

The built-in FSRS support expects all of your clients to support FSRS. If you're using AnkiDroid and don't want to use the helper, please wait until a 2.17 beta comes out.

**Comment by szalejot** [comment]
@dae I can use helper, that's not an issue for me.
If I use helper with "Auto reschedule cards reviewed on other devices after sync" option am I good to go? Or should I disable built-in FSRS for now and wait for AnkiDroid 2.17 beta?

**Comment by dae** [comment]
Will defer to @L-M-Sherlock on that

**Comment by L-M-Sherlock** [comment]
> If I use helper with "Auto reschedule cards reviewed on other devices after sync" option am I good to go?

Yes. It still works on 23.10. It will re-compute the memory-state for cards reviewed on other devices after sync.

**Comment by szalejot** [comment]
Great. I just wanted to contribute to new features beta testing without damaging my collection.
