### ISSUE TITLE
[BUG] "Auto disperse siblings" replaces "Undo Answer Card" with "Undo Disperse" that does not undo answer

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#249]
**Describe the bug**
If the "Auto disperse siblings" option is checked, instead of "Undo Answer Card" there is "Undo Disperse" (like https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/154) that does not undo answer.

However, **I can only reproduce it with my profile**. I disabled all the other add-ons.

**To Reproduce**
1. check Tools → FSRS4Anki Helper → [x] Auto disperse siblings
2. Answer a card.
3. Look at the undo item in the Edit menu and try to use it.

**Expected behavior**
There is "Undo Answer Card".
The undo item undoes the answer.

**Environment**
 - Anki version: 2.1.66 Qt6
 - OS: GNU/Linux
 - Scheduler version: 4.5.6
 - Helper version: https://ankiweb.net/shared/info/759844606 2023-09-25

**Comment by Expertium** [comment]
Can you try pressing "Ctrl + Z" twice? Maybe that will help.

**Comment by aleksejrs** [comment]
It works!

**Comment by L-M-Sherlock** [comment]
Due to a bug in Anki, I can't merge the undo operation of disperse into undo answer. I will fix it in Anki 23.10.
