### ISSUE TITLE
[BUG] "Auto reschedule the card you just reviewed" introduces a separate "undoable event"

### ISSUE THREAD

**Issue by brubsby** [open-spaced-repetition/fsrs4anki-helper#255]
**Describe the bug**
If "Auto reschedule the card you just reviewed" is enabled, after answering a card, it requires two undo key presses to actually undo answering the card if you answered incorrectly. I can't imagine a user would ever want to undo just an automatic reschedule, and not the answering of the card. So I feel it would be a better user experience to bundle these two events into a single "undo/redo" event, if at all possible.

**To Reproduce**
1. Enable "Auto reschedule the card you just reviewed"
2. Study a deck
3. Answer a card (incorrectly)
4. Press `ctrl+z` (or your undo hotkey) to attempt to go back and fix the answer
5. Observe that it undoes the "auto rescheduling" instead of the answering of the question and rescheduling both

**Expected behavior**
`ctrl+z` undoes the answer and the auto reschedule at the same time.

**Screenshots**
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/57653502/4e676416-c71e-4e84-a884-dbc109de2cdc)

**Environment**
 - Anki version: 2.1.63
 - OS: Windows 11
 - Scheduler version: v4.5.6
 - Helper version:  v4.5.6

**Additional context**
I realize this may not be possible to change with the limitation of the addons system, but I wanted to at least ask on the off chance that I might be the most bothered person by this, and nobody else has made an issue for it yet. 

Worse yet, if you have two a video media cards in a row, and you answer one incorrectly, you have to hit `q` to close the video, `ctrl-z` to undo the reschedule, `q` to close the video that popped up again, `ctrl-z` to undo the incorrect answer, `q` to close the video on the one you answered incorrectly, and `1-4` on the card to answer it again. and if you ever accidentally hit `ctrl-q` throughout all that, it accidentally closes anki, which also syncs your decks and can take a long time, and deletes the "undo context" that you needed to fix, and the card's incorrect answer lives on indefinitely, polluting FSRS learning data and affecting retention of the card.

**Comment by L-M-Sherlock** [comment]
> So I feel it would be a better user experience to bundle these two events into a single "undo/redo" event, if at all possible.

It's implemented as you said initially. But due to a bug of Anki, it doesn't work when you use other add-on that also modify the card after reviews. For more details, please see: https://forums.ankiweb.net/t/target-undo-op-not-found/33622

**Comment by brubsby** [comment]
> > So I feel it would be a better user experience to bundle these two events into a single "undo/redo" event, if at all possible.
> 
> It's implemented as you said initially. But due to a bug of Anki, it doesn't work when you use other add-on that also modify the card after reviews. For more details, please see: https://forums.ankiweb.net/t/target-undo-op-not-found/33622

Hmmm, good to know! Though I'm not certain which addon could possibly be responsible:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/57653502/1bb26488-7bb9-4012-b09f-c228adc17f59)
as I wouldn't think any modify the card every time.

**Comment by L-M-Sherlock** [comment]
This add-on will cause the bug: https://ankiweb.net/shared/info/1255924302. Some users report it in the discord channel, so I have to fix it.

**Comment by brubsby** [comment]
> This add-on will cause the bug: https://ankiweb.net/shared/info/1255924302. Some users report it in the discord channel, so I have to fix it.

Oh I misunderstood, I thought you meant that one of my currently installed addons was causing this behavior, because I thought this:
> It's implemented as you said initially.

meant: "It is currently implemented as you have initially described", rather than "It was initially implemented as you have described (but I had to change it)" which seems to be what happened.

Tracing the linked issue, it seems a fix for the underlying Anki issue has been implemented in https://github.com/ankitects/anki/releases/tag/23.10beta3
But I assume that if I use this beta version of anki with the current version of the fsrs4anki-helper addon, it will still produce the same undo behavior?

Although it looks as if that version of Anki has builtin FSRS, do you recommend that I try out using the builtin version of FSRS on the beta version of Anki as my main Anki version? And if so, are there any special steps I need to take to "migrate" my decks?

**Comment by L-M-Sherlock** [comment]
> But I assume that if I use this beta version of anki with the current version of the fsrs4anki-helper addon, it will still produce the same undo behavior?

I remove the auto reschedule feature for 23.10, because it's unnecessary when the built-in FSRS re-compute the memory states automatically.

**Comment by L-M-Sherlock** [comment]
And I don't think "a separate undoable event" is a bug. It's just a workaround to avoid the bug I mentioned above.

**Comment by brubsby** [comment]
> And I don't think "a separate undoable event" is a bug. It's just a workaround to avoid the bug I mentioned above.

I don't disagree, I just figured it was on the line between enhancement and bug, as it seemed like moderately incorrect (or at least undesirable) behavior, which felt more like "bug" than "enhancement" to me. Certainly a low priority bug, if at all. But it sounds like this will get fixed in the next version of Anki, which seems sufficient to call this issue fixed, whenever 23.10 can be deemed "released" (if not already)

**Comment by L-M-Sherlock** [comment]
`Auto reschedule the card you just reviewed` is disable by default, so it doesn't affect too many users. And I will record this undesirable behavior in the README.
