### ISSUE TITLE
[Feature Request] do something with related cards that are not siblings

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#256]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Some cards are not siblings, but they are so related, they shouldn't be reviewed on the same day. FSRS doesn't seem to do anything about them.

**Describe the solution you'd like**

Burying related cards when one of them is reviewed is implemented in other addons (see below).
I would like to have
* the related cards spaced
* maybe (new) cards buried when they are related to due ones
  * maybe also (new) buried until their siblings etc reach a certain interval or something), but I guess that's a separate issue.

There are two ways used to determine related cards.

The way to consider: grouping using a tag. You group notes by giving them the same `relation_*` tag (the prefix is customizable, and it would be `relation::*` now).
Implemented in “[Bury related notes](https://ankiweb.net/shared/info/413416269)" (“[anki-relation](https://github.com/Arthur-Milchior/anki-relation)”): “In addition to burying cards according to these rules, you can also use the rules in the "detect duplicates" tool in the card browser.”
The “[Copy notes](https://ankiweb.net/shared/info/1566928056)” addon (“[anki-copy-note](https://github.com/Arthur-Milchior/anki-copy-note)”) is supposed to add relation tags to both copies.

The flexible, but slow and complex way: field comparison as in “[Bury Cousins (related cards that aren't siblings)](https://ankiweb.net/shared/info/1072815885)”.
IIRC, [MorphMan](https://github.com/kaegi/MorphMan) can also bury cards with the same value in the `MorphMan_FocusMorph` field, or search with it (or even edit cards automatically).
“[Related flashcards by keyword](https://ankiweb.net/shared/info/634122010)” promises something like that, too.

**Comment by L-M-Sherlock** [comment]
So why not use those add-ons you mentioned?

**Comment by aleksejrs** [comment]
They do only what Anki does to siblings. If that was enough, you wouldn't have written "When should I use it: Always." about Disperse.

**Comment by L-M-Sherlock** [comment]
OK. Though it's not written by myself, but I will consider these case in the disperse siblings in the new version. But I wouldn't add new feature to the old version (<= 2.1.66).

**Comment by L-M-Sherlock** [comment]
@Expertium, what do you think of this feature?

**Comment by Expertium** [comment]
I think the first approach (tags) should work well. Ideally, in the future we should implement something more like the second approach, with automatic detection of similar cards, so that the user won't have to manually tag cards.

Also, I believe the Anki manual says that Anki devs didn't add a feature to mark any arbitrary cards as siblings on purpose, so this may conflict with the devs' vision.

**Comment by user1823** [comment]
Theoretically, I like the idea. I have even thought of suggesting it multiple times.

But, implementing it can be very impractical.
- Firstly, deciding whether a card is "related" or not can be difficult.
- Secondly, even after the user decides that some cards are related, they will need to

**Comment by aleksejrs** [comment]
> Secondly, even after the user decides that some cards are related, they will need to mark them as related one-by-one. This can be quite tedious.

Tagging in general is more tedious. Random `relation-` tags are added to selected or copied cards using addons.

Because of MorphMan ([this modified version](https://github.com/aleksejrs/myankiaddoncustomizations21/tree/trunk) for Anki 2.1.22), I stopped making many cards from a separate note, so MorphMan does not consider all the words in a sentence known. I also split notes into multiple ones sometimes (that's much easier and more efficient with the new Anki, except for [that bug](https://github.com/Arthur-Milchior/anki-copy-note/issues/46), but maybe I can fix it).

> Thirdly, if a large number of cards are marked as related to each other, the disperse siblings function would be unable to effectively separate them.

How is that different from notes with many cards generated from them, like cloze, especially Cloze Overlapper notes?

**Comment by aleksejrs** [comment]
> So why not use those add-ons you mentioned?
They are for the V2 scheduler, so apparently I have to review with V2 for them to be useful.

**Comment by cameronj86** [comment]
Came here re: the occlusion note type myself. Specifically the 'hide one guess one' cards being seemingly unaffected from dispersion. Not a dealbreaker but would further optimize study

**Comment by L-M-Sherlock** [comment]
This paper proposed a method to predict the memory state of a card based on its top-k most semantically relevant cards' review histories: https://arxiv.org/abs/2402.12291

But it's very complex. I have no plan to implement it.
