### ISSUE TITLE
[Question] Columns in browser

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki-helper#258]
I'm seeing a few columns in browse that I don't understand. 
How is the Target R different from Retrievability? I also have a column called "Add-on (retention)". Is that from the FSRS addon? what is that?
Also, do these values change every day or only after the card is reviewed?

I think the addon description might be in need of an update.

<img width="940" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/55925875/e891c427-867a-4bf8-bea8-8e9a6eacc823">

**Comment by L-M-Sherlock** [comment]
> How is the Target R different from Retrievability?

Target R is the Retrievability of the card when it's due. Retrievability is the Retrievability of the card today.

> I also have a column called "Add-on (retention)"

It's a bug of Anki. You can disable this column and restart Anki to remove it.

> Also, do these values change every day or only after the card is reviewed?

Retrievability changes every day, and Target R only changes after the card is reviewed.

**Comment by akavi1** [comment]
How is retention different from retrievability?
I have my target retention set to 0.85. Doesn't that mean the Target R should be 85% or at least close to 85% ?

**Comment by L-M-Sherlock** [comment]
> How is retention different from retrievability?

The difference between retrievability and retention is that the former refers to the probability of recalling a singular memory, whereas the latter refers to the average recall probability for a population of memories.

> I have my target retention set to 0.85. Doesn't that mean the Target R should be 85% or at least close to 85% ?

At least close to 85%. Due to fuzz and maximum_interval, it could not be equal to 85% exactly.
