### ISSUE TITLE
[BUG] Stats don't work after rescheduling cards in 23.10beta4

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#261]
**Describe the bug**
Here are the stats of one of my decks before rescheduling: 
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/38b20e66-38ec-411b-beec-e5706a77c9e3)
After rescheduling:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/f73f2692-7a29-4336-84c0-bef39c3489be)

**To Reproduce**
1. Use Anki 23.10beta4 and enable built-in FSRS
2. Find optimal parameters for built-in FSRS for your preset
3. Click on the cog icon of a deck affected by that preset and press "reschedule all cards"
4. Check the stats

**Expected behavior**
The stats shouldn't all be zeros.

**Environment**
 - Anki version: 23.10beta4
 - OS: Windows 10
 - Scheduler version: not applicable here

**Comment by L-M-Sherlock** [comment]
Please check update and try again.

**Comment by Expertium** [comment]
It works now, thank you.
I have a question - is this button necessary in beta?
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/f8044e1a-bb0e-45eb-9f6a-2b98bcd7dd62)

I mean, there is already a "Reschedule cards on change" option.
