### ISSUE TITLE
[BUG] 'FSRS' object has no attribute 'fuzz_factor'

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#263]
**To Reproduce**
1. Undo reschedulings in all cards (or use a collection in which cards don't have custom data)
2. Reschedule all cards
3. See error

**Error message**

> Caught exception:
> Traceback (most recent call last):
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "C:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 256, in on_done
>     tooltip(f"{future.result()} in {time.time() - start_time:.2f} seconds")
>   File "concurrent.futures._base", line 439, in result
>   File "concurrent.futures._base", line 391, in __get_result
>   File "concurrent.futures.thread", line 58, in run
>   File "C:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 277, in <lambda>
>     lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
>   File "C:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 354, in reschedule_background
>     card = reschedule_card(cid, fsrs, rollover, cur_deck_param)
>   File "C:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 503, in reschedule_card
>     again_ivl = fsrs.next_interval(again_s, retention, max_ivl)
>   File "C:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 225, in next_interval
>     new_interval = self.apply_fuzz(9 * stability * (1 / retention - 1))
>   File "C:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 217, in apply_fuzz
>     return int(self.fuzz_factor * (max_ivl - min_ivl + 1) + min_ivl)
> AttributeError: 'FSRS' object has no attribute 'fuzz_factor'

**Environment**
 - Anki version: 2.1.66
 - OS: Windows 11
 - Add-on version: Latest

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12840772/fsrs4anki-helper.zip)

Could you help me test it?
