### ISSUE TITLE
[BUG] Message Popping up 'NoneType:None'

### ISSUE THREAD

**Issue by Ankilli** [open-spaced-repetition/fsrs4anki-helper#267]
Hey there!

I noticed that FRS4Anki Helper is not working well with another addon called 'Leech Toolkit'.
When using both a window pops up while doing reviews. It says "Leech Toolkit has run into an error! NoneType: None" (shown below).
When disabling the Helper it runs smooth.
I would like to keep both because the Toolkit is an advanced way of handling leeches.

Maybe you can help?

I reached out to the author of the addon as well.

However thank you for an amazing addon :)

![grafik](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/89978096/64b5ea35-790e-487f-ad12-37efef4e024c)

**Comment by L-M-Sherlock** [comment]
Could you provide your environment info about Anki and the add-ons?

**Comment by Ankilli** [comment]
Sure 😊 have to mention that it has been happening since Dec 8, 2022. Back then I opened an issue on the other addon's page. Since then I've been updating everything every now and then without anything changing for the better. But since I've been using filtered Decks alot for the past months (to get rid of a huge backlog) I wasn't noticing the issue -> The Leech Toolkit isn't working on filtered decks.
Yesterday I tried out deactivating chunks of my addon list to see if it makes any changes and in the end only the FSRS4Anki was left.

**Environment**
 - Anki version: 2.1.66
 - OS: iOS
 - Scheduler version: v4.5.6
 - Optimizer version: tried it, wasn't working I guess, deleted it again
 - Simulator version: not using

**Comment by Ankilli** [comment]
my bad, closed it  😅

**Comment by L-M-Sherlock** [comment]
> I reached out to the author of the addon as well.

Could you open an issue in https://github.com/iamjustkoi/LeechToolkit/issues? And I will read the source code of that add-on.

**Comment by L-M-Sherlock** [comment]
Which features of FSRS4Anki Helper and LeechToolkit add-on did you enable when you meet this error?

**Comment by L-M-Sherlock** [comment]
I guess it's due to a bug of Anki: https://forums.ankiweb.net/t/target-undo-op-not-found/33622

To solve it, you need to update to Anki 23.10.

**Comment by Ankilli** [comment]
I see..
I just noticed when I turn off auto_disperse it goes away, that'd be a strong indicator that you're right.
