### ISSUE TITLE
[Documentation] Average retention vs True retention

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#274]
They are causing quite a lot of confusion. Just today I answered two questions about them; one on github, one on Reddit.
Here's what I suggest:
1) Don't collapse "Interpretation" in "Stats", make it always visible. Right now the user has to click on it, I think it's better if the user literally can't **NOT** notice it.
2) I don't know where exactly to put this, but the following message would be helpful:
"Average retention can be interpreted as the probability of recalling any card today. True retention refers to how many cards you got correctly when they were due. Not all cards are due, in fact, most aren't. That's why these two values are different. Average retention is higher than true retention because it includes cards that are not due. Also, average retention depends on FSRS parameters since it's an algorithmic prediction, while true retention doesn't depend on parameters."

@user1823, maybe you have some good ideas on how to make all of this more clear.
EDIT: this should probably be moved to fsrs4anki-helper repo.

**Comment by L-M-Sherlock** [comment]
> 1. Don't collapse "Interpretation" in "Stats", make it always visible. Right now the user has to click on it, I think it's better if the user literally can't **NOT** notice it.

I collapsed Interpretation is due to https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/191#issue-1857613977

**Comment by Expertium** [comment]
Hm. I wonder how to make this convenient while at the same time make sure that new users will notice and read the interpretation.

**Comment by user1823** [comment]
Currently, I have two suggestions:
- Rename "Average retention" to "Average predicted retention" to indicate that it is an algorithmic prediction, not a measured value.
- Just above the interpretation section, write:

    > Note: In most cases, the average predicted retention is expected to be higher than your requested retention. For details, read the interpretation section.

**Comment by Expertium** [comment]
@L-M-Sherlock so here's my final suggestion, combined with what user1823 suggested:
1) Rename "Average retention" to "Average predicted retention"
2) Above the "Interpretation" and below "Retention by notes" add:
"In most cases, the average predicted retention is higher than your requested retention. For details, read the interpretation section."
3) Slightly change the description of average predicted retention to the following:
"**Average predicted retention**: the average probability of recalling a card today. In most cases, it is higher than requested retention because requested retention refers to retention at the time of a review, whereas average retention is calculated based on all cards, including undue cards. Not all cards are due, that's why these two values are different. **The average predicted retention is calculated using FSRS formulas and depends on your parameters**. True retention is not an algorithmic prediction, so changing FSRS parameters won't affect it."
