### ISSUE TITLE
[BUG] addon got disabled after switching to anki 23.10 and back

### ISSUE THREAD

**Issue by ilya-rusyanov** [open-spaced-repetition/fsrs4anki-helper#277]
**Describe the bug**
I tried anki 23.10-rc1 and returned to version 2.1.66. Helper menu options have disappeared as well as stats (shift+t). Also rescheduling notification does not pop when syncing.

**To Reproduce**
1. Have anki 2.1.66
2. Shut it down
3. Install anki 23.10-rc1
4. Launch it
5. Go to deck options, enable FSRS for parent deck
6. Quit
7. Install anki 2.1.66 back
8. Notice that addon looks like disabled. The presence of it cannot be noticed elsewhere except for list of installed addons, it is still there.

**Expected behavior**
Addon works as it was before the manipulation with anki versions.

**Environment**
 - Anki version: 2.1.66, 23.10-rc1
 - OS: Debian 12.2
 - Scheduler version: 4.5.6
 - Helper version: latest

**Comment by ilya-rusyanov** [comment]
Manual enable-disable of the addon and then anki restart solved the issue.

**Comment by user1823** [comment]
There are different versions of the add-on for Anki 2.1.66 and Anki 23.10. So, I think that the add-on won't work until the correct version of the add-on is installed.

**Comment by ilya-rusyanov** [comment]
> There are different versions of the add-on for Anki 2.1.66 and Anki 23.10. So, I think that the add-on won't work until the correct version of the add-on is installed.

I don't think that's the case, because I didn't switch versions of the addon

**Comment by user1823** [comment]
Anki should update it automatically when checking for updates.

**Comment by L-M-Sherlock** [comment]
> I tried anki 23.10-rc1 and returned to version 2.1.66. Helper menu options have disappeared as well as stats (shift+t). Also rescheduling notification does not pop when syncing.

Please reinstall the add-on.
