### ISSUE TITLE
[BUG] Error when reviewing a card

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#278]
**Describe the bug**
```
Debug info:
Anki 23.10 (3394ab02) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-21 13:40:47
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "aqt.taskman", line 102, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 434, in after_answer
  File "aqt.reviewer", line 444, in _after_answering
  File "_aqt.hooks", line 4134, in __call__
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 365, in disperse_siblings_when_review
    mw.col.update_card(card)
  File "anki.collection", line 491, in update_card
  File "anki.collection", line 486, in update_cards
  File "anki.collection", line 486, in <listcomp>
  File "anki.cards", line 106, in _to_backend_card
ValueError: Value out of range: -1
```

**To Reproduce**
I don't know how to reproduce this.

**Environment**
 - Anki version: [23.10rc1](https://github.com/ankitects/anki/releases/tag/23.10rc1)

**Comment by dae** [comment]
Maybe interval is being set to -1 for some reason?

**Comment by dae** [comment]
If you edit the addon and add a line above 365: 'print(card)', the console should reveal what card property is erroneously being set to a negative value.

**Comment by L-M-Sherlock** [comment]
I need a collection to reproduce this error.

**Comment by Blauelf** [comment]
That one reproduces the issue for me. One note, two cards, both due.
Though there is a catch: If you trigger the issue, then import the collection again, it won't trigger the issue. Seems like something does not get reset on collection import. Had to restart Anki before I could see the error message again.
[broken_one_note.colpkg.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13126979/broken_one_note.colpkg.zip)

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/ff8bfcf2-7752-4010-a941-ae7dbbca60d4)

The main problem is the last review date is earlier than the due date. @dae, I guess it's caused by rescheduling cards on change.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13161085/fsrs4anki-helper.zip)
Commit: cdedaa79c1eac606bac0220e6a744bd19f22ccb6

@Blauelf @Expertium

**Comment by Expertium** [comment]
I don't know how to test it since I don't know how to reproduce this error.

**Comment by L-M-Sherlock** [comment]
The commit has solved this issue.
