### ISSUE TITLE
Review with native FSRS doesn't update "v" in the custom data

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#279]
When a card is reviewed using the native FSRS, the value of "v" in the custom data is not updated.

This is obviously not a problem for the user. However, this behavior decreases the usefulness of saving "v" in the custom data. Even if the card was last scheduled by Anki, the custom data still says v=disperse or v=reschedule, making it difficult to debug.

**Comment by L-M-Sherlock** [comment]
Because they are separate module. The native FSRS stores the rescheduling as revlog entry.

**Comment by user1823** [comment]
My point is that if native FSRS doesn't update the entry in the custom data, we can't know whether the module mentioned in "v" of custom data was actually the one that last scheduled the card or not.

In other words, we can't trust the "v" entry in the custom data.

**Comment by L-M-Sherlock** [comment]
Yeah. That's a problem. But the the native FSRS is standalone, it doesn't assume the user installs any add-on that could store some info in the custom data.
