### ISSUE TITLE
[BUG] problem with rescheduling in Anki 23.10

### ISSUE THREAD

**Issue by estherkl** [open-spaced-repetition/fsrs4anki-helper#284]
**Describe the bug**
in Anki 23.10 the helper doesn’t reschedule cards rescheduled by anki

**To Reproduce**
1. Reschedule when changing the parameters in the deck options
2. turn of „reschedule cards on change“
3. change the desired retention
4. reschedule all cards with the helper
5. after the last step the interval of the cards hasn’t changed.

**Screenshots**
Before rescheduling with the helper (desired retention: 0.9)
![Screenshot 2023-10-26 095626](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/127582792/f15d098c-21f5-4e8c-9319-f6e59a59f05e)

After rescheduling (desired retention: 0.95)
![Screenshot 2023-10-26 095721](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/127582792/29aaa625-dc16-4e38-a0cd-f51814ad9a76)

**Additional context**
The reason of this behavior might be that there is a manual entry each time you manually reschedule the cards with anki but the helper does not reschedule cards where the last entry is manual.

**Comment by L-M-Sherlock** [comment]
Please update the add-on.

**Comment by estherkl** [comment]
It works now! Thank you and sorry for this unnecessary Bug report!
