### ISSUE TITLE
[BUG] After sync, the tooltip is sometimes not displayed

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#289]
However, the tooltip is not reliably displayed. That is, after sync, the tooltip is sometimes not displayed. This issue is not specific to this patch, and I have been experiencing it since many days (probably started after updating to 23.10).

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/271#issuecomment-1784102465_

**Comment by szalejot** [comment]
From my side, I can add, that on my end tooltip is either not displayed or is displayed for literally few frames - it blinks so fast that it is not possible to tell, what the message is.
I am using 23.12 beta3 on Windows, OpenGL video driver.
