### ISSUE TITLE
[Feature Request] Clear custom data when using the add-on with Anki 23.10

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#293]
**Is your feature request related to a problem? Please describe.**
If I understand it correctly, the values of D and S in the card's custom data are useless when using the built-in FSRS.

**Describe the solution you'd like**
If built-in FSRS is used, the add-on should clear custom data, making it empty.

**Comment by L-M-Sherlock** [comment]
I plan to remove this feature and replace it with the cutsom date clear feature:

<img width="421" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/a6415831-4775-4149-a85a-7c8f900a2454">

I'm busy in this week. I will implement it soon if I'm available.

**Comment by L-M-Sherlock** [comment]
Patch: 
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13237279/fsrs4anki-helper.zip)

**Comment by Expertium** [comment]
I think rather than making it an option in the menu, it should be a pop-up.
1) Add-on checks whether there are any cards with custom data
2) If there are, it displays a pop-up that says:
"The custom scheduling of FSRS4Anki stored memory state information in Anki's custom data. It is no longer used once you enable the built-in FSRS. Do you want to clear custom data of your cards?
(if you have built-in FSRS enabled, this action will have no negative consequences)"
Yes/No
3) If there are no cards with custom data, don't do anything

**Comment by L-M-Sherlock** [comment]
But I'm not sure whether other add-ons also use custom data. I don't want to make this feature too active.

**Comment by L-M-Sherlock** [comment]
If this patch doesn't cause errors, I will merge it at first.
