### ISSUE TITLE
[BUG] Anki 23.10 - critical error

### ISSUE THREAD

**Issue by Exponent4806** [open-spaced-repetition/fsrs4anki-helper#294]
**Describe the bug**
There appears to be an error with the latest version of the add-on. After updating Anki and the Add-on I get the following error on Manjaro KDE:

Debug Info:
Anki 23.10 (51a10f09) Python 3.11.5 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.1.60-1-MANJARO-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-11-01 12:28:39
Möglicherweise ursächliche Erweiterungen: ⁨**FSRS4Anki Helper⁩**

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 138, in _on_closures_pending
    closure()
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 82, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 102, in wrapped_done
    on_done(fut)
  File "/usr/lib/python3.11/site-packages/aqt/sync.py", line 119, in on_future_done
    return on_done()
           ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 1050, in on_collection_sync_finished
    gui_hooks.sync_did_finish()
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 5038, in __call__
    hook()
  File "/home/m/.local/share/Anki2/addons21/759844606/sync_hook.py", line 82, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids, texts))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/.local/share/Anki2/addons21/759844606/sync_hook.py", line 42, in auto_reschedule
    texts.append(fut.result())
                 ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'result'

**Comment by Exponent4806** [comment]
> Could you reproduce this error?

No. This might be an uncommon issue and I cannot reproduce it. I updated from Anki 2.1.66 to Anki 23.10. Then, this issue appeared. Afterwards, I am not able to reproduce it.  I will close this issue because it might be a random error related to the Anki upgrade. If I reproduce it, I will reopen the issue.

**Comment by matejdro** [comment]
I started getting this yesterday. It shows up on one of my machines:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the [add-ons section](https://forums.ankiweb.net/c/add-ons/11) of our support site. 
Debug info:
Anki 23.10 (51a10f09) Python 3.11.5 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-10-31 13:10:39
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 138, in _on_closures_pending
    closure()
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 82, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 102, in wrapped_done
    on_done(fut)
  File "/usr/lib/python3.11/site-packages/aqt/sync.py", line 119, in on_future_done
    return on_done()
           ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 1050, in on_collection_sync_finished
    gui_hooks.sync_did_finish()
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 5038, in __call__
    hook()
  File "/home/matej/.local/share/Anki2/addons21/759844606/sync_hook.py", line 82, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids, texts))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/.local/share/Anki2/addons21/759844606/sync_hook.py", line 42, in auto_reschedule
    texts.append(fut.result())
                 ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'result'
```

Enabled features:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/507922/35d35b59-86ff-47cd-8111-4f3ebfe45cbc)

**Comment by L-M-Sherlock** [comment]
@matejdro, could you uninstall the add-on and re-install it?

**Comment by matejdro** [comment]
Error at first disappears when reinstalling, but then when I enable "Auto reschedule cards..." option back, it comes back.

**Comment by L-M-Sherlock** [comment]
Do you enable FSRS in the deck options?

**Comment by matejdro** [comment]
Ah that could be it. I have FSRS enabled, but "the old way" (with Custom scheduling) and the machine that's experiencing the error is the only machine that has new Anki installed. I've now updated Anki on another machine and it is also experiencing this error.

I've migrated from custom scheduling to the new setting now and the error is gone. Maybe you could improve the error message? Because at the moment, this error is completely unhelpful.

**Comment by Exponent4806** [comment]
@L-M-Sherlock  This was precisely my problem! I upgraded to Anki 23.10 and "Custom Scheduling" was active. Then, the error appeared! You found the root of the problem! You are a genious! :D

**Comment by Konotorious** [comment]
> Do you enable FSRS in the deck options?
> 
> ![image](https://private-user-images.githubusercontent.com/32575846/279889748-4fe09d0d-ff81-440a-a0d2-8a9f4e96e604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTA2OTAsIm5iZiI6MTcwMTM1MDM5MCwicGF0aCI6Ii8zMjU3NTg0Ni8yNzk4ODk3NDgtNGZlMDlkMGQtZmY4MS00NDBhLWEwZDItOGE5ZjRlOTZlNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDEzMTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMzEyOTBhNTM5MjE3NWU2NGYwNzJkZDI1NWQ1MTNjOWE3NDk2MjA5NTUzYzUwNjBiMmQ2MjMzYmRlYzNiZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5b45h25jeEOv8_TZUqC68Gf0_GIXvgl_F9nbVlHLcyk)

To not open a new issue I reply here. The screenshot, as does my Anki client, advises that one's Ankidroid should be version 2.17+, but the latest released version is 2.16.5. Is this an error or does it really refer to the future release of Ankidroid?

**Comment by L-M-Sherlock** [comment]
> Is this an error or does it really refer to the future release of Ankidroid?

It refers to 2.17+. The alpha version has been released: https://github.com/ankidroid/Anki-Android/releases

**Comment by Konotorious** [comment]
Thank you.
So if I've updated my desktop Anki to the latest stable release, I cannot use the FSRS addon in conjunction with the Android app unless I install the alpha release of AnkiDroid?

**Comment by Exponent4806** [comment]
> Thank you. So if I've updated my desktop Anki to the latest stable release, I cannot use the FSRS addon in conjunction with the Android app unless I install the alpha release of AnkiDroid?

Uninstall the version from Google Play / F-Droid and use only the alpha versions. Only then can you use FSRS.

Stop doubting! Life is entirely different with FSRS.... lol

**Comment by Konotorious** [comment]
Just to be clear, I had been using the addon until I updated my desktop Anki today. On the first sync it prompted me to "enable FSRS". I found the toggle in the advanced settings of the decks, together with the warning "FSRS will not work correctly if one of your clients is older."
(I also now notice that the manner by which one lets the algorithm calculate the weights, and by which one inputs them back to the addon, have changed?)

**Comment by L-M-Sherlock** [comment]
Please read the new tutorial: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md
