### ISSUE TITLE
[Question] Why "Sync reschedule" takes 3 times longer than "Reschedule cards in the last X Days"?

### ISSUE THREAD

**Issue by DerDemystifier** [open-spaced-repetition/fsrs4anki-helper#295]
When I sync:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/124774256/7271ff1e-d999-451a-877e-f7cd41ce307a)

When I use "Reschedule cards in the last 1 Days" (I have it set to 1 day because I use it often and sync reschedule is slow)
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/124774256/1ab39a5b-e56c-4dc7-b1ce-0bda73e7a0a8)

So I have three questions:
- Why does the first case take 3 times longer even though it found 0 cards to reschedule? While it took less time to search for all cards in the last 1 day and reschedule them all?
- Most people sync frequently, more than once a day. So for us it would be a lot faster to just trigger the second option when we sync.
- Can you add another hook to call the "Reschedule cards in the last X Days" function before Anki is closed? That would be a lot of help and a great alternative to a reschedule after each sync feature.

*Enter an [x] character to confirm the points below:*

- [ x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x ] I have searched for similar existing questions here

**Comment by L-M-Sherlock** [comment]
In `Sync reschedule`, FSRS uses `IN` condition to query the cards to reschedule. It takes more time.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/08ddb9b4e3879a972b56e3cbe52254697026fb47/schedule/reschedule.py#L168-L169
