### ISSUE TITLE
[BUG] Clear custom data can affect the "Reschedule all cards" behavior

### ISSUE THREAD

**Issue by gugutu** [open-spaced-repetition/fsrs4anki-helper#298]
**Describe the bug**

Clear custom data can affect the "Reschedule all cards" behavior.

I am using Anki's built-in FSRS, and clear custom data should not affect the "Reschedule all cards" behavior.

This is the prediction graph after I performed "Reschedule all cards" before using "Clear custom data in all cards":

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59798823/a8cd189e-fbb6-4216-b02b-6e9527ac7781)

This is the prediction graph after I use "Clear custom data in all cards" and then perform "Reschedule all cards":

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59798823/7b690012-25bd-497a-901b-6647aeeb8a49)

The result of using "Reschedule cards on change" in Anki deck options is not affected by clear custom data, and its result is different from the result of using add-on to reschedule:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59798823/7a5df1a0-d0ce-4877-a509-4461b83790cd)

This is my configuration status:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59798823/8e30697a-425f-4951-b4dd-f1f1316dc249)

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59798823/5d714824-290e-4e3f-95d5-dd442629b9f9)

**Environment**
 - Anki version: [23.10 (51a10f09)⁩]
 - OS: [Windows 11 22621.2428]

**Comment by L-M-Sherlock** [comment]
> The result of using "Reschedule cards on change" in Anki deck options is not affected by clear custom data, and its result is different from the result of using add-on to reschedule:

The helper add-on use different random generator, so the behavior is different. In old FSRS, the custom scheduling code saved the real seed generated by Anki in the custom data. So `clear custom data` can affect the "Reschedule all cards" behavior. I don't have any good solution to solve it, unless Anki exposes its fuzz factor to the add-on. @dae would be helpful here.
