### ISSUE TITLE
built in fsrs different behavior than helper

### ISSUE THREAD

**Issue by kieranlblack** [open-spaced-repetition/fsrs4anki-helper#299]
**Describe the bug**
I recently updated to Anki 23.10 with fsrs built in (congrats btw!). I have been using fsrs for 9 or so months now and my usual routine is to use the helper to reschedule my deck fully every morning to ensure recently reviewed cards are rescheduled with their full history accounted for. I rescheduled everything this morning then decided to upgrade to 23.10 and play around with it. To my surprise, when I entered my old model weights I was using with the custom scheduling code and selected to reschedule cards on change, the amount of cards I have due today changed by around 200 cards for a ~20% increase in due cards.

I feel like there is probably some implementation difference between what the helper was doing and what is now implemented in Anki and wanted to point this out to you guys.

Also, should I maybe stick to using the helper for the time being, is one implementation more "correct" than the other?

**To Reproduce**
1. Reschedule using fsrs-helper
2. Reschedule using built-in reschedule cards on change
3. Compare

**Expected behavior**
I would expect the implementations to be identical.

**Screenshots**
Using fsrs-helper:
<img width="476" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/48463323/0d07d9b7-83af-49ce-8015-0ab9d3a25d85">
Using built-in rescheduler
<img width="476" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/48463323/c99f56b5-1f0b-4faa-bc70-7dcadb0707d6">

**Environment**
 - Anki version: 23.10
 - OS: Windows 11 Pro 10.0.22621 Build 22621
 - Scheduler version: v4.5.6 Scheduler Qt6
 - Optimizer version:
 - Simulator version:

**Comment by kieranlblack** [comment]
Okay, that makes sense. I feel like I generally do not see cards getting fuzzed so far backwards with the helper, but I'm not sure why that is.

Also, I was just checking out one of the cards which was moved backwards and the interval checks out but it looks like every time the built in fsrs has rescheduled the card it gets counted as a Manual review, is this intended?

<img width="692" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/48463323/663b0b4e-97bc-4781-aabd-6683ddec287e">

**Comment by L-M-Sherlock** [comment]
It's intended, because dae added this feature. I don't recommend to reschedule your cards with the built-in FSRS too often.

**Comment by L-M-Sherlock** [comment]
It's fixed in Anki 23.10.1.

**Comment by gugutu** [comment]
At present, there are still slight differences between the two:

Rescheduling with the helper:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59798823/e77e559d-56f9-4960-93c2-bfe06256ca4e)

Rescheduling using anki built in implementation:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59798823/dc194748-2ba1-424d-b8ea-f706ae08aa1d)

It may not have a significant impact, but it is best to fix it to ensure consistency. @L-M-Sherlock
