### ISSUE TITLE
New card interval after personalising in optimiser is 2.7 months?!

### ISSUE THREAD

**Issue by ajnol** [open-spaced-repetition/fsrs4anki-helper#302]
Hi I've just started using FSRS and used the interval optimiser. Having posted the new paramaters, it is setting the new card interval to 2.7m. Why is this? does this show my optimisation is unreliable and I should use default paramaters?

More generally if I want to put in my own custom new card paramaters how can I do so? I had steps etc set up before adding FSRS and it seems to ignore these

**Comment by L-M-Sherlock** [comment]
Please provide your training data for analysis. And what's your previous true retention?

**Comment by Expertium** [comment]
Do you mean the "Easy" interval? Have you used the "Easy" button often before switching to FSRS? 
If you rarely used it, it could lead to the interval being overestimated. That being said, FSRS with personalized parameters should still be better for you than the default parameters.
If you used "Easy" a lot, then FSRS has adapted and you actually _under_estimate your retention when you press "Easy".

**Comment by L-M-Sherlock** [comment]
Inactive
