### ISSUE TITLE
[Feature Request] Make Free Days apply immediately once the user selects a day

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#305]
**Is your feature request related to a problem? Please describe.**
I've seen a few users saying that Free Days is broken and being surprised that when they select a day to make it free, they don't see any immediate changes.

**Describe the solution you'd like**
Make it so that when the user selects a day to make it free, rescheduling occurs. The only issue is that this will require doing the opposite once the user un-checks the day, which may be difficult.

**Comment by L-M-Sherlock** [comment]
A possible solution: query cards due in free days and reschedule them when users set the free days.

Potential problem: if they have a very large collection, this process might take some time. And cards will still be due in free days over time if they don't reschedule all cards.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13345788/fsrs4anki-helper.zip)

<img width="209" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/9e726bed-00ae-4bd9-aee7-d11e7e688566">

Now you can apply free days immediately via clicking that button. It will query cards due in free days and reschedule them.

**Comment by L-M-Sherlock** [comment]
@user1823, maybe you are also interested in this feature. Could you help me test the patch?

**Comment by Expertium** [comment]
Today is Tuesday, but when I selected Tuesday and rescheduled cards, it only rescheduled some of them, not all.

**Comment by L-M-Sherlock** [comment]
> it only rescheduled some of them, not all.

I guess those non-rescheduled cards are in learning stage or their intervals are too short.

**Comment by L-M-Sherlock** [comment]
OK. But it requires to enlarge the fuzz range.

**Comment by L-M-Sherlock** [comment]
@Expertium, I still think it's important to protect those cards with short intervals. If the stability is very low, the retrievability will decrease quickly when we increase the interval due to free days.

**Comment by Expertium** [comment]
I understand, but I also don't think that renaming "Free Days" to "Almost Free Days" or "Slightly More Free Days" would be a good idea, lol.
In all seriousness, we need to decide whether we want this feature to do _exactly_ what the user expects from the name or not.

**Comment by user1823** [comment]
I am not interested in this feature because I do my reviews every day.

However, I think that the current approach is better; it doesn't atleast affect the retention. We can probably mention somewhere that this feature doesn't make the day "completely" free.

**Comment by L-M-Sherlock** [comment]
Maybe it's better to add an extra option to loosen the fuzz range. I will implement it tomorrow.

**Comment by Expertium** [comment]
That's another settign that will make the user think "What does this do?". Let's keep things simple.

**Comment by L-M-Sherlock** [comment]
Fine. Then I just want to keep the current implementation.

**Comment by user1823** [comment]
One suggestion: Replace "immediately" in the name of the option with "now" so that it reads "Apply free days now".

Also, I don't think that "apply" is the right word here but I am not sure what is the best word/phrase to express it.
