### ISSUE TITLE
What is the syntax to create a filtered deck based on advanced search criteria like retrievability or difficulty?

### ISSUE THREAD

**Issue by wadid** [open-spaced-repetition/fsrs4anki-helper#307]
I am trying to create a filtered deck but its not working for me.

Tools -> Create filtered deck... 

"deck:DeckName" prop:r<0.7

This gives me error that I gave a wrong argument to prop.

Writing it in this fashion:
"deck:DeckName" r<0.7
gives me always 0 results (no matter the r value)

**Comment by L-M-Sherlock** [comment]
What's your Anki version?

**Comment by L-M-Sherlock** [comment]
Did you read this manual? I think it is helpful for you.

https://docs.ankiweb.net/searching.html#card-properties

**Comment by wadid** [comment]
hmmm ... if I would want to learn before a test in a filtered deck a selection of card (in case I cannot or dont want to learn all cards) would I use the "difficulty" metric for filtering? Or would "lapses" or maybe "stability" be most suited?
