### ISSUE TITLE
Are all these "Manual" info necessary?

### ISSUE THREAD

**Issue by BEST8OY** [open-spaced-repetition/fsrs4anki-helper#312]
Hello
Are all these "Manual" info necessary?
If not, an option to remove the unnecessary ones can make the collection size smaller.
If it goes on like this, it can cause syncing problem in long run!
**Screenshots**
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/70865987/b538435c-a31b-467a-9334-f08a6352cfcc)

**Comment by BEST8OY** [comment]
> They're generated by Anki rather than the add-on. You need to ask @dae.

Should I wait for his answer here or ...?
If not, please close the issue and I'll ask somewhere else!

**Comment by L-M-Sherlock** [comment]
I recommend reporting this issue at: https://forums.ankiweb.net/
