### ISSUE TITLE
Enhancing FSRS Helper: A Request for a Dashboard to Monitor Enabled Deck Groups [Feature Request]

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#313]
I propose the development of a dashboard feature for FSRS Helper to easily display which groups of decks have FSRS enabled. This dashboard would not list individual decks but rather the groups they are categorized under, assisting users in managing and understanding the application of FSRS across their study material. Such a tool could prove invaluable for optimizing study routines and evaluating the effectiveness of different group settings.

**Comment by L-M-Sherlock** [comment]
The built-in FSRS is a global setting.
