### ISSUE TITLE
[BUG] Card Error Preventing Reviews

### ISSUE THREAD

**Issue by vinnymew** [open-spaced-repetition/fsrs4anki-helper#314]
**Describe the bug**
I installed FSRS4Anki last night and it was working fine on new cards. However, when marking a card as again/hard/good/easy, I have gotten a couple errors for some older cards. I can't get rid of the error and I can't move forward with studying any review cards. Anki freezes. I do have Anki for iPhone but haven't used it since installing FSRS. I synched everything, restarted Anki, cleared custom scheduling, and rescheduled all cards and still get this error. I had to turn off FSRS to continue studying. 

**To Reproduce**
1. Clicked "study now" in a deck
2. Clicked the space bar to answer a review card (note: NOT a new or learning card)
3. Clicked "good" to move on to the next card
4. Error in screenshot appears

**Expected behavior**
I expected to be able to mark the review card as again/hard/good/easy and move on with studying the next cards in line. 

**Screenshots**
<img width="799" alt="Screenshot 2023-11-26 at 1 21 32 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/152093845/97569ce9-0e50-48cc-ba8d-51a0f2a2bc4a">
<img width="518" alt="Screenshot 2023-11-26 at 1 11 52 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/152093845/e5be1fbf-95a9-4a0d-991c-9e35cafefe0c">

**Environment**
 - Anki version: 23.10.1 (fac9e0ee)⁩
 - OS: MacOS 13.3.1 (a) (22E772610a)
 - Scheduler version: Unsure? I turned on FSRS in the Anki options
 - Optimizer version: 4.10.2
 - Simulator version: [e.g. v1.1.0]

**Comment by L-M-Sherlock** [comment]
Did you enable other add-ons that affect the scheduling? And did you try to reschedule the card with the helper's reschedule feature?

**Comment by vinnymew** [comment]
> Did you enable other add-ons that affect the scheduling? And did you try to reschedule the card with the helper's reschedule feature?

I have no other add-ons, and yes I did try to reschedule everything.

**Comment by L-M-Sherlock** [comment]
> did try to reschedule everything.

Does the rescheduling solve it error?

**Comment by vinnymew** [comment]
Sure, how should I share the file? I can't attach the .apkg file here

**Comment by dae** [comment]
Are you the same person who posted on https://forums.ankiweb.net/t/ankiweb-bad-request/37556?

If you're unable to upload the file after putting it in a .zip, you could also try sharing it with something like Google Drive's 'share a link' feature.

**Comment by vinnymew** [comment]
The good ol' Google Drive. Forgot that existed for a minute. Here you go: https://drive.google.com/file/d/12SmBhhlpBIc99WNEHvJ1hONwiouXyuOY/view?usp=sharing 

@dae Not the same person - this is the only thread I have going. Thank you!

**Comment by dae** [comment]
Using the 23.12 beta and no add-ons active, I imported that file, enabled FSRS in the deck options (which updates stability/difficulty) on all cards, and checked the card in your screenshot - and did not see NaN there. So first things to try would be updating to the beta, disabling add-ons, and making a minor change to the parameters as suggested in the link I posted above.
