### ISSUE TITLE
[BUG] Add-on update downloads extra files

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#319]
When updating the add-on, Anki downloads some files that are not present in the repo: 
<img width="537" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/14f13566-e8ad-4b06-8020-2531656d69cb">

**Comment by L-M-Sherlock** [comment]
I will remove it in the next update.
