### ISSUE TITLE
[Feature Request] Apply maxInterval update on reschedule

### ISSUE THREAD

**Issue by patrickellis** [open-spaced-repetition/fsrs4anki-helper#32]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
In order to apply changes to maximumInterval deck options, I need to create a custom study session to study all the cards I want to apply the new settings for. It's time consuming!

**Describe the solution you'd like**
**Reschedule** from FSRS Helper Addon to reschedule if current interval > maximumInterval

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by patrickellis** [comment]
Ah I've discovered what's happened here
[On these lines](https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/b92054e27e02c5c55062cc5c82a556fba33e0d8a/reschedule.py#L128-L131) your code checks `if deck['name'].startswith(name):` however I actually [modified this](https://github.com/patrickellis/fsrs4anki/blob/main/fsrs4anki_scheduler.js#L91) in my fork of fsrs4anki_scheduler.js to check for **includes** instead (I nest decks within each other, and change their names often, so this requires less maintenance)

**Comment by patrickellis** [comment]
Closing this issue as it's not a bug, but this does force me to use startsWith - I wonder if anybody agrees that includes is also useful?

If I have a deck like: 
Deck 1 :: Deck 2 :: Deck 3 :: Deck 4 
Every time Deck 1, 2, or 3 change their name - my custom parameters for deck 4 need to be updated

**Comment by L-M-Sherlock** [comment]
`includes` would cause a problem: 

If I have a deck named "A::B" and a deck named "B", `startsWith("B")` only matches the second but `includes("B")` will also match the first.

**Comment by patrickellis** [comment]
I wouldn't call that a problem, as long as your deck names are descriptive. Also - if people are concerned about ambiguous matching in cases like that one ^ they can continue to reference all decks using **"A::B"**!

**Comment by patrickellis** [comment]
@L-M-Sherlock Sorry, I see your point now. You cannot have custom deck options for both A a child deck of A using that setup, the parent deck will always match first.
