### ISSUE TITLE
Incorporate simulator into fsrs4anki helper addon

### ISSUE THREAD

**Issue by salmanuc** [open-spaced-repetition/fsrs4anki-helper#322]
**Which module is related to your feature request?**
Scheduler, Optimizer, or Simulator?
Simulator
**Is your feature request related to a problem? Please describe.**
The simulator addon for anki that is currently available simulates sm2 afaik. It would be nice to have a simulator for fsrs as well that works offline. 

**Describe the solution you'd like**
Incorporation of simulator into the helper addon or a separate addon to simulate fsrs offline. 

**Describe alternatives you've considered**
Only google colab option available right now. 

**Additional context**

**Comment by L-M-Sherlock** [comment]
The built-in FSRS crate has provided function to simulate the learning process with FSRS.

https://github.com/open-spaced-repetition/fsrs-rs

So I recommend submitting a request in https://forums.ankiweb.net/

**Comment by salmanuc** [comment]
I have requested for the already available simulator for anki to be updated for fsrs
https://github.com/giovannihenriksen/Anki-Simulator/issues/75#issuecomment-2009716558

Lets hope the authors accept the request.
Thank you @L-M-Sherlock.

Btw the simulator that is already available in google colab can it not be incorporated natively into anki?

**Comment by L-M-Sherlock** [comment]
> Btw the simulator that is already available in google colab can it not be incorporated natively into anki?

It cannot because the colab version is based on PyTorch, which is a huge package in Python. It's very hard to use it in a simple anki add-on.
