### ISSUE TITLE
[Feature Request] Auto "apply easy days now"

### ISSUE THREAD

**Issue by jonahspear-toast** [open-spaced-repetition/fsrs4anki-helper#327]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
I'm often frustrated to see that I have a significant amount of reviews scheduled on "Easy Days", especially when learning lots of new material. I understand that this is due to the current implementation of the "Easy Days" scheduling algorithm. I often end up clicking "Apply easy days now" to get it to correctly schedule a low amount of reviews on easy days. It's rather annoying to have to press this button every week.

**Describe the solution you'd like**
I should not have to click "Apply easy days now", can't we just schedule using the logic that "Apply easy days now" runs? 

**Describe alternatives you've considered**
Alternatively, could we have an option to always "apply easy days now"

**Comment by L-M-Sherlock** [comment]
> I should not have to click "Apply easy days now", can't we just schedule using the logic that "Apply easy days now" runs?

Due to technical limitation, it is problematic to modify the schedule when reviewing.

**Comment by Joboman555** [comment]
Can we reschedule easy days at startup or closing?

**Comment by L-M-Sherlock** [comment]
<img width="688" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/93693209-268d-4dba-afc2-2fdbc717ebb6">

This feature would be helpful. Here is the patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13699038/fsrs4anki-helper.ankiaddon.zip)

**Comment by jonahspear-toast** [comment]
Thank you!!!
