### ISSUE TITLE
[BUG] Some cards are not rescheduled

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#329]
**Reproduction Steps**

1. Enable FSRS in Anki.
2. Import [Default.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13706696/Default.zip) (change extension to .apkg).
3. Click on 'Reschedule all cards'

**Expected behavior**
Rescheduled 3 cards

**Actual behavior**
Rescheduled 1 card

The two cards don't have memory states, though they are not new. The add-on doesn't calculate their memory states on clicking "Reschedule all cards", though Anki does calculate them after changing the FSRS parameters and clicking "Save". 

**Environment**
 - Anki version: 23.10.1

**Comment by user1823** [comment]
I have not tested whether this happens with all cards without memory states or only with these cards. But, if it happens with all cards lacking memory states, it means that the option in the add-on can't be used when switching from SM-2 to FSRS.

**Comment by L-M-Sherlock** [comment]
The current implementation doesn't recompute the memory state. Only the auto rescheduling after sync recomputes the memory state.

**Comment by user1823** [comment]
> The current implementation doesn't recompute the memory state, because it's time-consuming. 

Ok, it makes sense.

My use case is quite rare because all non-new cards are expected to have memory states in Anki if FSRS is enabled. So, I can just use the "change a parameter slightly and click the Save button" approach.
