### ISSUE TITLE
[BUG] Python plugin should not extract `w` from JavaScript comments

### ISSUE THREAD

**Issue by kylegoetz** [open-spaced-repetition/fsrs4anki-helper#33]
See open-spaced-repetition/fsrs4anki-helper#34

**Comment by L-M-Sherlock** [comment]
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10888075/fsrs4anki-helper.zip)

I developed a patch. Could you give it a test?

**Comment by kylegoetz** [comment]
@L-M-Sherlock I had a look at the code, and there's still other variables extracted using the same method. I think it would be good to write a function that takes the JS and immediately strips it of all comments before doing anything else. I've written tree sitter algorithms before that tokenizes code, and that's often how one does things: highest priority in parsing goes to comments, and only if some code is not a comment do you proceed.

Generally speaking, you shouldn't parse code using regex, but since it's just extracting comments, and the alternative is not parsing at all and running into these bugs, probably something like this would be fine:

```python
'\n'.join([re.sub('^//..*$', '', _) for _ in input_text.split('\n')]) # removes all `// .....` from input_string
```

In the ideal case, you'd use a JavaScript parser to extract the data, though. Since it's possible to include libs from PyPl in your plugins (by bundling them in the plugin), you could use `pyparsing` and have it strip out single-line and multi-line comments, and it'd be more trustworthy than my regex above. Something like would likely work perfectly:

```python
import pyparsing

text_without_js_comments = pyparsing.cppStyleComment.suppress().transformString(input_text)
```

Would you be open to a PR that uses pyparsing to do this and to extract the desired data rather than relying on brittle regex?

**Comment by L-M-Sherlock** [comment]
> Would you be open to a PR that uses pyparsing to do this and to extract the desired data rather than relying on brittle regex?

Of course, it could solve this issue permanently. And I hope it can also extract the parameters in the new version of the scheduler. 3.9.6 is too old.

**Comment by MNastri** [comment]
Isn't the idea for the GUI supposed to solve this and many similar problems?
It should output the code correctly and users won't have to touch the code avoiding this and other errors entirely.

The regex in the helper already works if users don't mess with the code, so I think we don't need to add dependencies for an already solved problem, but instead focus on getting the GUI ready.

If you think we should remove comments until the GUI is ready, I think that to add a dependency instead of a few lines of code (which could be run first and once in the code) is not the better approach.

**Comment by L-M-Sherlock** [comment]
> I think that to add a dependency instead of a few lines of code (which could be run first and once in the code) is not the better approach.

I agree with you. I'm worried that introducing a new dependency would induce some cross-platform-related problems.

**Comment by kylegoetz** [comment]
"if users don't mess with the code" is a risky assumption to make (it is, after all, the assumption that resulted in the bug that motivated me opening this ticket; there are probably a lot of users of Anki who didn't even know how to report a similar issue so just silently never got to use this software), but if work on this GUI y'all mention is already underway, then I imagine it's a fine tradeoff to accept a less-than-optimal fix that will be obviated in the short to medium term by what sounds like a plugin GUI that maintains the JS itself and users never touch it.

Is the GUI underway? I don't see a branch on the repo for it. If no one is working on it, I might take a crack at writing one and investigating whether it's possible to not even have the JS, or have it stored somewhere that is read-only to prevent a user from accidentally modifying something that is auto-generated by the plugin GUI. I'm kind of just sitting around learning F# and could take on an enhancement of some open source software, especially something I use myself :)

**Comment by user1823** [comment]
I am in favor of developing a GUI to create the JS code for the user. However, making the JS read-only is not the way to go for two reasons:
- It would snatch from the users the ability to add additional custom scheduling rules (in addition to FSRS).
- It seems to be something that we can't do independently, and we would probably require some changes to the main Anki app.

**Comment by MNastri** [comment]
> "if users don't mess with the code" is a risky assumption to make ...

If the user wants to play with the code, the user is free to do that.
But the unintended effects caused by users playing with the code shouldn't be our concern because the regex in the helper already works if users don't mess with the code. 

> ... wouldn't surprise me if other users were hit by this bug but didn't know how to open a ticket to report it

I think we're all in agreement here. People often make silly mistakes that could break how the code works. A GUI that auto-generated the config for the users would be beneficial by having standard output.

> ... what sounds like a plugin GUI that maintains the JS itself and users never touch it.

The GUI should simply abstract the creation of the custom scheduler code so that users don't mess up.
The user inputs the global and per deck parameters (weights, retention, maxinterval, etc) and get the custom scheduler code via clipboard or in a textbox(?). After that the user can paste the code in the custom scheduler field inside Anki.

> Is the GUI underway? I don't see a branch on the repo for it. If no one is working on it, I might take a crack at writing one and investigating whether it's possible to not even have the JS, or have it stored somewhere that is read-only to prevent a user from accidentally modifying something that is auto-generated by the plugin GUI. I'm kind of just sitting around learning F# and could take on an enhancement of some open source software, especially something I use myself :)

I developed some small examples and am waiting for review from L-M-Sherlock but you're free make your own too.

**Comment by kylegoetz** [comment]
@MNastri but the nature of the Javascript *requires* the user to "play around with" (read: modify) the JavaScript code. You can't even use it properly without modifying the code.

And once you instruct the user to insert their own `w` value, then a single space will break the whole thing. Let alone the fact that users can accidentally hit other keys (Anki on Mac, for example, doesn't allow Cmd+F in that box, meaning if you try to quickly "ctrl+f w" to find the `w` to edit it, wherever your cursor is will insert `fw`. Yes, a user will hopefully see this has happened, but that's exactly why I'm saying this method is brittle.

The use of FSRS *requires* the user to mess around with the JS code. (Or they could use the defaults, but that defeats the whole purpose of FSRS, right?)

**Comment by MNastri** [comment]
I agree with this point: people do make silly mistakes, but that's easilly fixable (or it should be, right?); and disagree that JS requires anything of its users. 
Most users just want to use FSRS and following the instructions (copy and pasting) gets them what they want. 
The fact that it is written in JS doesn't influence anything for the regular user, but feel free to play with the code if you feel thats a requirement as a JS dev.
