### ISSUE TITLE
FSRS Helper for Holidays

### ISSUE THREAD

**Issue by Reanox24** [open-spaced-repetition/fsrs4anki-helper#336]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Cards due on Holidays

**Describe the solution you'd like**
Hello. This is a request for an add-on to be incorporated where certain days of the year can be blocked out (comes from a not so happy wife watching me do cards on Christmas), and preferably the option to keep young cards scheduled for those days. I would do this, but I do not have the technical prowess to create such an add-on. Thank you very much

**Describe alternatives you've considered**
Skipping the cards on that day, but that impairs learning

**Comment by L-M-Sherlock** [comment]
I also don't know how to add a calendar GUI to select the holiday in Anki.

**Comment by glutanimate** [comment]
@L-M-Sherlock for Qt, the Countdown to Events add-on would probably be a good example to look at, as it includes a widget that allows adding an arbitrary number of dates, cf. https://github.com/sam1penny/countdown-to-events/blob/main/src/__init__.py#L86-L169

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13793814/fsrs4anki-helper.ankiaddon.zip)

<img width="187" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/01780f51-15b2-4af0-94dd-d1fea4a6393b">

@Reanox24, I hope it could help you.

**Comment by Reanox24** [comment]
Y'all are the best, thank you all so much! Wifey is now very happy
