### ISSUE TITLE
[Feature Request] Faster Anki Load (after rescheduling easy days on startup)

### ISSUE THREAD

**Issue by jonahspear-toast** [open-spaced-repetition/fsrs4anki-helper#338]
**Which module is related to your feature request?**
Scheduler

**Is your feature request related to a problem? Please describe.**
Since [this PR](https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/88f10adb952bb1f0dd659f42c666cab27c12ad48), opening Anki is now very slow. It is common to take more than 5 seconds for my anki to open. I have some system macros that open anki and do specified behavior (for example, add a card to a specific deck), and they are now broken.

**Describe the solution you'd like**
I'd like scheduling of easy days to happen on close AND for the scheduling of easy days to be applied for a shorter interval (so that it's faster). I think 1 month is a reasonable default.

**Describe alternatives you've considered**
It might also make sense to have the reschedule period be a config, but I think that it's not necessary currently.

**Comment by L-M-Sherlock** [comment]
> I'd like scheduling of easy days to happen on close

I couldn't find out the hook called on closing. If you know any add-ons could automatically execute some tasks when closing Anki, please tell me.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13796808/fsrs4anki-helper.ankiaddon.zip)

Have a try.

**Comment by Joboman555** [comment]
Thanks! This is great!
