### ISSUE TITLE
[Feature Request] Options to reschedule & recalculate memory states of selected cards in the Browser

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#340]
**Is your feature request related to a problem? Please describe.**

There are certain situations where I want to reschedule or recalculate memory states for only a few cards.

For rescheduling, I could previously move them to another deck and reschedule all cards in that deck. But, in Anki 23.12+, this process is cumbersome because changing decks clears the memory states.

Also, the reschedule option doesn't recalculate the memory states. So, I have to use the "change a parameter slightly and click the Save button" approach. However, it involves multiple steps and it marks all cards as changed, wasting the network resources when syncing.

**Describe the solution you'd like**

The issue can be solved by adding `Reschedule` and `Recalculate memory states` to the menu in the Browser (the menu in the image below).

<img width="235" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/80f1cc43-df98-42ba-9b28-52dd8c360330">

If you think that it would be better to add only one option, then clicking that option should both recalculate the memory states as well as reschedule the card.

If you want an example of an add-on that adds options to that menu, here is an example: https://ankiweb.net/shared/info/94685914

**Describe alternatives you've considered**

**Additional context**

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13848260/fsrs4anki-helper.ankiaddon.zip)

Have a try.
