### ISSUE TITLE
[Bug] Inconsistent fuzz between the scheduler and the rescheduler 

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#343]
If I perform my reviews and then press `Reschedule all cards` option in the add-on without changing any settings, the intervals of all the cards change slightly. But, if the add-on's fuzz was exactly the same as Anki's, then rescheduling should not change the intervals in this case.

One possible reason is that fuzz during review is calculated before the rating but fuzz during reschedule is calculated after all ratings. So, if this is the only reason, it can be corrected by subtracting 1 from `reps` while rescheduling.

**Environment**
 - Anki version: 23.12.1

**Comment by L-M-Sherlock** [comment]
Did you enable `load balance`?

**Comment by user1823** [comment]
No

**Comment by L-M-Sherlock** [comment]
The add-on has used Anki's built-in fuzz function. The only possible cause is the stability is changed. Could you provide a case of the affected cards?

**Comment by L-M-Sherlock** [comment]
> the intervals of all the cards change slightly

How slight are these changes? Within one day?

**Comment by user1823** [comment]
Example card: [Default.apkg.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13848448/Default.apkg.zip) (Remove .zip at end)

Rescheduling changed due date from 6 Feb to 9 Feb

**Comment by L-M-Sherlock** [comment]
It doesn't contain the preset, so I can't reschedule the card to the same date without your parameters.

**Comment by user1823** [comment]
I think that I exported the preset. Anyway, here are the parameters:
1.2502, 3.9521, 22.2139, 35.3634, 5.1795, 1.3051, 1.3681, 0.0108, 1.7835, 0.1059, 1.0901, 2.1143, 0.1215, 0.5364, 0.3711, 0.0060, 4.0000

**Comment by L-M-Sherlock** [comment]
What's your desired retention?

**Comment by user1823** [comment]
0.94

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/bfd5b2f7-b5a8-4baa-9489-320929c0bbaf)

The built-in reschedule feature also scheduled the card to 9 Feb.

**Comment by L-M-Sherlock** [comment]
So this consistency is caused by the scheduler during review. Could you give me this card which hasn't been reviewed today?

**Comment by user1823** [comment]
> So this consistency is caused by the scheduler during review. 

Yes, I am talking about the inconsistency between the scheduler and the rescheduler.

> Could you give me this card's backup which hasn't been reviewed today?

[Default_old.apkg.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13848622/Default_old.apkg.zip)

**Comment by L-M-Sherlock** [comment]
Weird. The scheduler is consistent with the rescheduler in my test:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/6859c604-0dd9-4110-8f4d-9ebe0a68ca43)

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/2280de9f-6a87-4d17-aa9d-6dec221faedd)

**Comment by user1823** [comment]
> Weird. The scheduler is consistent with the rescheduler in my test:

Oops. Actually, I didn't restore the card from backup because it was too much work. I simply deleted the last revlog using the Console. So, the reps count was left unchanged.

But anyway, you have just confirmed that my hypothesis was correct:

> One possible reason is that fuzz during review is calculated before the rating but fuzz during reschedule is calculated after all ratings. So, if this is the only reason, it can be corrected by subtracting 1 from reps while rescheduling.

**Comment by L-M-Sherlock** [comment]
You are right:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/68c43416-66ac-49c6-b631-002e5653eb38)

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/4dce74c0-f3b4-4a07-a737-71979dc45ca0)

@dae, please log it.
