### ISSUE TITLE
[BUG] Auto-reschedule not turned off?

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#344]
I disabled auto_reschedule_after_sync in the config file today and restarted Anki multiple times. However, I still get a tooltip saying "x cards rescheduled, y cards in z notes dispersed in b seconds." after sync.

(I have used the variables x, y, z and b to indicate that the numbers are not fixed and do change as the no. of synced reviews changes.)

So, is auto-reschedule still enabled? Or is the tooltip bugged?

**Environment**
 - Anki version: 23.12.1

**My add-on config**
```json
{
    "load_balance": false,
    "easy_days": [],
    "days_to_reschedule": 7,
    "auto_reschedule_after_sync": false,
    "auto_disperse_after_sync": true,
    "auto_disperse": true,
    "mature_ivl": 40,
    "debug_notify": false,
    "fsrs_stats": true,
    "display_memory_state": false,
    "auto_easy_days": false
}
```

Update: I just checked the add-on settings in the menu and it shows that auto reschedule is still enabled:

<img width="279" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/b90626dc-5f93-41b0-93d2-f583769912e9">

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13855779/fsrs4anki-helper.ankiaddon.zip)

**Comment by user1823** [comment]
I don't think that this is the correct solution.

As the screenshot shows, the auto-reschedule option is enabled even after I have set it to False in the config and restarted Anki.

**Comment by L-M-Sherlock** [comment]
I can't reproduce this bug.

**Comment by user1823** [comment]
I can't try to reproduce this now because I am not on my computer.

But, I think that I enabled the auto-reschedule option using the menu a few days earlier and then disabled it using the config yesterday.

So, maybe it is an inconsistency between the menu and the config?

**Comment by L-M-Sherlock** [comment]
Did you edit the raw config file? I tested it and the menu kept synced with the file.

**Comment by user1823** [comment]
> Did you edit the raw config file?

Yes

> I tested it and the menu kept synced with the file.

If you are unable to reproduce it, then maybe we can close the issue. I will comment if I see it happening again.

**Comment by user1823** [comment]
I have seen that happen on other days too.

I have also noted that selecting the Easy Days in the GUI doesn't modify the config.json file in the add-on folder, but modifies the config seen in Anki.

This seems to be an Anki bug. Can you confirm?

**Comment by L-M-Sherlock** [comment]
> This seems to be an Anki bug. Can you confirm?

I don't know how to reproduce it.

**Comment by user1823** [comment]
I guess that it is a Windows-specific bug.

<img width="624" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/a1e253c3-15fc-4902-8ba8-3703386ebfec">

The changes made within Anki (through GUI checkboxes or by editing config) are not reflected in the config.json file in the add-on folder even after restarting Anki.

**Comment by L-M-Sherlock** [comment]
I recommend reporting this bug in https://forums.ankiweb.net/
