### ISSUE TITLE
[Feature Request] load balancer settings, more uniformity/customizability

### ISSUE THREAD

**Issue by wadid** [open-spaced-repetition/fsrs4anki-helper#346]
Anki version ⁨23.12.1 with newest FSRS4Anki Helper

I have a deck with cards that are rather complex, so they are much more time consuming to answer than vocabulary cards. 

I have the helper with load balancing enabled. But is the following deck correctly  load balanced?

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/3696388/454193b1-94c4-4500-b353-ca63cd3049b9)

I enabled "reschedule on change" and changed the deck settings to see if I get  more uniform load but it didnt get better than what is shown on the picture.

Is there any way to set load balancer settings to customize the load more e.g. make the load more uniform? Or could that somehow be implemented? I think that would be really cool.

**Comment by L-M-Sherlock** [comment]
The load balance only works with the rescheduling of helper add-on. It doesn't take effects in the built-in rescheduling.

**Comment by wadid** [comment]
ah this means there normally isnt any load balancing without the helper, or does the helper more aggressive loadbalancing? The helper you can only reshedule the whole collection?

**Comment by L-M-Sherlock** [comment]
> ah this means there normally isnt any load balancing without the helper

Yes. Because this feature hasn't been integrated into Anki.

> The load balancing helper is "only" applicable to the whole collection?

Yes.

**Comment by wadid** [comment]
very nice. happy that its load balanced now.
So that means I can just click on reschedule in the helper with (load
balancing activated) every day? or might there be unwanted effects doing
that every day?

Btw is this manual rescheduling with the helper also needed after using
anki droid (not the newest version)?

Am Sa., 13. Jan. 2024 um 05:47 Uhr schrieb Jarrett Ye <
***@***.***>:

**Comment by L-M-Sherlock** [comment]
Yeah. By the way, you can click `reschedule cards reviewed in last 7 days` for better performance.

If you enable `auto reschedule cards reviewed in other devices`, you will not need to manually reschedule those cards.

**Comment by wadid** [comment]
So I did reschedule all cards. Then right away I worked off some reviews and some new cards. then something strange unexpected happened: for example there was a deck that had some cards to review  maybe 35 and maybe also 40 new cards. I reviewed  and learned them. After I was done I clicked on reschedule all cards again but then suddenly this deck was filled again with something like 40 or 50 cards to review.

This was not the effect i had hoped for. How does it come that after, first rescheduling and then doing review or learn new cards and then reschedule again (both on same day), I got another workload scheduled on that day?

> > ah this means there normally isnt any load balancing without the helper
> 
> Yes. Because this feature hasn't been integrated into Anki.
> 

But does the helper reschedule a single card automatically after review if that setting is activated? or is that feature not working at the moment? because I had this setting activated all the time since doing reviews. but only when clicking on 'reschedule all cards' I got a really balanced distribution (which suggests without manual rescheduling from time to time you will not get the full load balancing)

> Yeah. By the way, you can click `reschedule cards reviewed in last 7 days` for better performance.

Performance in what regards? You mean speed of rescheduling (I think it takes only 2 seconds for me if I reschedule all cards)? Or do you mean better result?

**Comment by L-M-Sherlock** [comment]
> I got another workload scheduled on that day?

My guess is they were reviewed in the past 7 days without load balance. So FSRS rescheduled them into today. You can click `reschedule cards reviewed in last 7 day` before you begin to work in your reviews today.

**Comment by L-M-Sherlock** [comment]
> But does the helper reschedule a single card automatically after review if that setting is activated? or is that feature not working at the moment?

Load balance only works when you reschedule cards.

**Comment by wadid** [comment]
> > I got another workload scheduled on that day?
> 
> My guess is they were reviewed in the past 7 days without load balance. So FSRS rescheduled them into today. You can click `reschedule cards reviewed in last 7 day` before you begin to work in your reviews today.

hmm as I remember it I did reschedule all cards before reviewing and then after reviewing again (that's when all these cards reappeared). All on same day. So you think it shouldn't happen in that case?

**Comment by L-M-Sherlock** [comment]
If so, the problem is  `load balance`. It would increase today's reviews if the workload is lower than average.

**Comment by wadid** [comment]
I think there are two features I would be very interested in:
- a checkbox/option that you can click that would prevent that your reviews for this day will increase if you load balance.
- an option where you can load balance in a way that all your current open reviews will disappear and be load balanced in the future

Regarding the second option: I would favour after some time when I couldnt do anki to not have to deal with a pile of reviews which will mess with my time management and also give me the psychological effect of a huge amount of work piling up. I would rather have the option to just load balance it one time into the future and thats it. No daily postponing, no figuring out how many extra cards I can do per day, no daily seeing of unfinished review. For me the advantages would be worth efficiency losses.

Is that possible, maybe as an experimential option?

**Comment by L-M-Sherlock** [comment]
> I would favour after some time when I couldnt do anki to not have to deal with a pile of reviews which will mess with my time management and also give me the psychological effect of a huge amount of work piling up.

I recommend using postpone in this case.

**Comment by wadid** [comment]
why would you suggest so? I mean as I understood it postpone needs to be done and decided daily and doesnt do any load balancing.

The functionality I would be interested in is decide once and then just load balance it all in the future. And if you want to do more you would just use the advance feature. Would that be complicated to implement?

**Comment by L-M-Sherlock** [comment]
> Would that be complicated to implement?

Yeah. It's complicated to prevent reviews from increase in load balance. 

1. It doesn't allow change the schedules of due cards.
2. It doesn't allow the due of undue cards to be earlier than tomorrow.

To implement above two limitation, I need to refactor the load balancer.

**Comment by wadid** [comment]
> 2. It doesn't allow the due of undue cards to be earlier than tomorrow.

why would this functionality be needed?

So theoretically if I would customize something on the code myself , then I would need to download the sources or make a fork but I would not be able to do any updates anymore? or how does it work?

**Comment by L-M-Sherlock** [comment]
> why would this functionality be needed?

If not, the reviews in the future might be scheduled to the past and increase your workload in today.

**Comment by wadid** [comment]
So as described before when rescheduling directly after finishing my reviews I would get new cards from the next day(s). 

So instead now why I tried to do the rescheduling as first activity on a new day when no reviews are done:

This is how it looked before rescheduling. You can see on next day there is waiting a pile of cards.

![rescheduleBefore](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/3696388/5babc7f8-3752-468a-b538-8ec1db6c050a)

This it how it looks after rescheduling. The cards pile which was due tomorrow is suddenly due today.

![rescheduleAfter](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/3696388/9808a56f-2595-4bed-82dd-e0fa4e9d699e)

I hoped I could load balance this pile a bit onto the next couple days so there wouldnt be such a pile tomorrow. But now after load balancing it just pulled the pile of cards for due today.

Wouldn't it be nice to be able to load balance such a pile on the next couple of days in the future instead?

**Comment by L-M-Sherlock** [comment]
> Wouldn't it be nice to be able to load balance such a pile on the next couple of days in the future instead?

Load balance is limited by the fuzz range. If the fuzz range is narrow, those reviews will haven't enough space to disperse. That why they are piled.

**Comment by wadid** [comment]
not sure if I understand but wouldnt it be possible to distribute the cards equally between today and tomorrow instead of pulling the an unequal amount to today?

**Comment by L-M-Sherlock** [comment]
> at least possible to distribute the cards equally between today and tomorrow instead of pulling the an unequal amount to today?

It depends on your cards' intervals.

> Can you explain me how fuzz works with load balancer?

Fuzz range is [interval * 0.95, interval * 1.05]. The interval is the interval corresponding to your desired retention.

**Comment by wadid** [comment]
ah, I just realized that in anki there is a "Set due date" function that also can take time ranges and randomizes distribution.
Seems like that does sufficiently what I wanted in the first place. If you first reschedule with load balance and then schedule the the due cards in the future with random distribution it give a good result.

But did I observe right, that if you reshedule then a second time all the initially due cards will be due again and you will have original state?

**Comment by L-M-Sherlock** [comment]
> But did I observe right, that if you reshedule then a second time all the initially due cards will be due again and you will have original state?

Of course. Rescheduler will re-calculate the interval based on the stability of your cards and your desired retention.
