### ISSUE TITLE
[Feature Request] Ability to apply Easy Days to more than one date

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#349]
**Is your feature request related to a problem? Please describe.**
On some days, I am busier than on other days. So, I will want to do lesser reviews on those days. The current implementation allows the user to select a single Easy day (specific date), but not multiple Easy days.

**Describe the solution you'd like**
An ability to choose more than one date would be great.

**Comment by L-M-Sherlock** [comment]
Do you know any other add-ons that you can select multiple Easy days? I'm not good at UI and interact design.

**Comment by user1823** [comment]
The add-on from which you originally copied the UI allows selecting more than one date.

<img src="https://raw.githubusercontent.com/sam1penny/countdown-to-events/main/screenshots/edit.png">

Link: https://ankiweb.net/shared/info/1143540799

Also, what about replacing the following box with a list to which the user can directly add the dates?

<img width=200 src="https://private-user-images.githubusercontent.com/32575846/293372682-01780f51-15b2-4af0-94dd-d1fea4a6393b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODYxMjIsIm5iZiI6MTcwNTQ4NTgyMiwicGF0aCI6Ii8zMjU3NTg0Ni8yOTMzNzI2ODItMDE3ODBmNTEtMTViMi00YWYwLTk0ZGQtZDFmZWE0YTYzOTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEwMDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZTBlYTFmNGYxZTE3YTAzZTI2NGU4MzNiZWY4NGRkODJhNDhlNTk5ZmE2NWZlZTNjYTZhZDI2YWFlZWM2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJ6BYoiyPkgtXW98Hdhq9bF-C3QeFyAKvqOh6KURY8Y">

For example, "2024-01-18, 2024-01-26"

Inspired from config of https://github.com/cjdduarte/Free_Weekend_Load_Balancer

**Comment by L-M-Sherlock** [comment]
It requires an extra database stored in the add-on directory.

**Comment by user1823** [comment]
> It requires an extra database stored in the add-on directory.

No, I mean that the box should contain such list as a temporary value saved in RAM only till the user exits that window.
