### ISSUE TITLE
[BUG] Load Balance ignores cards studied today

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#35]
Suppose I started the day and they had 80 cards to study today.

After finishing studying all the cards of the day, I activated the "Rescheduler all cards".

On average I have 100 cards in the next few days (tomorrow, the day after tomorrow, etc.)

He ignores that I already studied 80 cards today and plays another 100 cards on average because he saw that today I have ZERO cards to study, leaving a total of 180 cards (80 already studied and 100 new balanced).

**Suggestion: when balancing, he considers the cards already studied today.**

![image](https://user-images.githubusercontent.com/42243532/222914260-95806fa7-a2f1-4135-9e8d-5ff503d4a825.png)

In the example above, maybe he put 10 or 15 cards down for today instead of 100.

**Comment by L-M-Sherlock** [comment]
Same as https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/24

Related code: https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/b92054e27e02c5c55062cc5c82a556fba33e0d8a/reschedule.py#L67-L71

Maybe counting the cards rated on the given date in `num_cards` will solve this problem.

**Comment by L-M-Sherlock** [comment]
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/10889104/fsrs4anki-helper.zip)

I developed a patch. Have a try~

**Comment by cjdduarte** [comment]
WORKS !!!!!!

**Before**
![image](https://user-images.githubusercontent.com/42243532/222927461-c33c156d-d3d3-42f0-a1b5-31fb5335fe3b.png)
![image](https://user-images.githubusercontent.com/42243532/222927483-aa8a006f-ed75-453b-b401-4a558e6f1561.png)


**After**
![image](https://user-images.githubusercontent.com/42243532/222927526-15f757cc-b7da-40ef-a7fa-0320335938ea.png)
![image](https://user-images.githubusercontent.com/42243532/222927536-66f824ba-70f0-4483-8cdf-7a2666406d34.png)


Tomorrow I want to make a new one when the queue of those studied on the day is at zero.
But today it worked.

**Comment by cjdduarte** [comment]
I just don't understand (902 vs 947) why this number changed, but the rest is OK.

![image](https://user-images.githubusercontent.com/42243532/222928501-58f30952-116b-43a3-ba73-d64157e2a09e.png)

**Comment by cjdduarte** [comment]
Works !!!

Open Anki now.
![image](https://user-images.githubusercontent.com/42243532/222954595-6a21df08-a54e-4be8-b62b-1dc1140c9cce.png)

I clicked on "Schedule all cards". **Is correct.**
![image](https://user-images.githubusercontent.com/42243532/222954677-b8c048fd-13b1-416b-8b3a-af98f98bfeb9.png)

I studied today's cards.
![image](https://user-images.githubusercontent.com/42243532/222957246-93ee64a5-e58b-4bb9-aff9-b11b35cea137.png)

I clicked "Schedule all cards" again.
**Is correct.** He didn't bring cards for today again.

![image](https://user-images.githubusercontent.com/42243532/222957293-a50702aa-2228-47d8-bd83-4141f74d667f.png)

**You can move to production.**

**Comment by user1823** [comment]
@L-M-Sherlock, Could you link the commit also?

And does it consider the cards done yesterday (or other days) in the past in addition to considering the cards done today? This would be required when working through a backlog as I would not want cards to be added to the yesterday's due list just because I worked through some of them.

**Comment by L-M-Sherlock** [comment]
> @L-M-Sherlock, Could you link the commit also?

Here: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/8359dc008b609221b6fd1dcfd4f2e07a123327b6

**Comment by user1823** [comment]
> And does it consider the cards done yesterday (or other days in the past) in addition to considering the cards done today? This would be required when working through a backlog as I would not want cards to be added to the yesterday's due list just because I worked through some of them.

This question remains unanswered, but by looking at the code, I think that it doesn't consider the cards done on days in the past. Am I correct? If so, do you have any idea to solve this issue?

**Comment by L-M-Sherlock** [comment]
> This question remains unanswered, but by looking at the code, I think that it doesn't consider the cards done on days in the past. Am I correct? If so, do you have any idea to solve this issue?

It has considered the number of cards reviewed/learned in the past.

```
rated_cards = len(mw.col.find_cards(f"prop:rated={day_offset}")) if day_offset <= 0 else 0
```

**Comment by user1823** [comment]
Ok. Thanks.
