### ISSUE TITLE
[Feature Request] An option to override first rating while optimizing

### ISSUE THREAD

**Issue by BEST8OY** [open-spaced-repetition/fsrs4anki-helper#355]
**Is your feature request related to a problem? Please describe.**
If someone wants lower interval beside increasing retention this is a good way if they usually rated 3 (Good) as first rating.

**Describe the solution you'd like**
The option can be like this
- Override First Rating
    - None
    - 1
    - 2
    - 3
    - 4

**Comment by L-M-Sherlock** [comment]
> If someone wants lower interval beside increasing retention this is a good way if they usually rated 3 (Good) as first rating.

You can modify the parameters directly.

**Comment by BEST8OY** [comment]
> You can modify the parameters directly.

I assume you're talking about changing in this?
fsrs4anki_optimizer.ipynb
If not, How?
An in Anki way  would've been way nicer!

**Comment by L-M-Sherlock** [comment]
<img width="518" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/37153cc5-1dd1-4f12-a7e9-4fc0d9ab7aed">

You can modify these parameters to change the interval of new cards.

**Comment by L-M-Sherlock** [comment]
Or just use learning steps.

**Comment by BEST8OY** [comment]
> You can modify these parameters to change the interval of new cards.

I still deem the requested feature much more accurate than just randomly messing with those numbers with experimenting!
