### ISSUE TITLE
[BUG] Easy days moves cards to the past

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#356]
**To Reproduce**
1. Go to "Apply easy days for specific dates option."
2. Add today's date.
3. Click Apply.

**Expected behavior**
Cards are moved into the future, but not in the past.

**Actual behavior**
Some cards are moved into the past (in my case, yesterday).

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14150687/fsrs4anki-helper.ankiaddon.zip)

**Comment by user1823** [comment]
Didn't work. Still 1 card is due yesterday after applying Easy days.

**Comment by L-M-Sherlock** [comment]
> Still 1 card becomes due yesterday after applying Easy days.

Could you check that card's fuzz range?

**Comment by user1823** [comment]
How do I check the fuzz range?

Here is the card info:
<img width="573" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/830f7777-a8bf-4c66-b7dd-b928255ec719">

Desired retention = 0.94

**Comment by L-M-Sherlock** [comment]
69 * 1.05

Given the dr = 0.94, its interval is 69. So the fuzz range is [69 * 0.95, 69 * 1.05], i.e. [66, 72]. And 2023-11-22 plus 72 days is 2024-02-02.

**Comment by user1823** [comment]
According to the following, max_ivl = ivl * 1.05 + 1. So, it should be 73 days.
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/3a80df690e4d731e03c65ceda805f556c6a88e45/utils.py#L118

**Comment by L-M-Sherlock** [comment]
Maybe the stability is 121.5 and it's rounded up to 122 in the card info.

```
>>> DECAY = -0.5
>>> FACTOR = 0.9 ** (1 / DECAY) - 1
>>> def next_interval(s, r):
...     ivl = s / FACTOR * (r ** (1 / DECAY) - 1)
...     return max(1, int(round(ivl)))
...
>>> next_interval(122, 0.94)
69
>>> next_interval(121.5, 0.94)
68
>>> round(68 * 1.05 + 1)
72
```

**Comment by user1823** [comment]
But, how did the card then get a due date of 3rd Feb? I don't use Postpone or any other scheduling add-ons.

**Comment by L-M-Sherlock** [comment]
> But, how did the card then get a due date of 3rd Feb? I don't use Postpone or any other scheduling add-ons.

It's problem related to:
- https://github.com/ankitects/anki/pull/2873

**Comment by user1823** [comment]
Reason for my thinking: If I click `update memory state and reschedule` in the Browser, the due date is 3rd Feb.

**Comment by L-M-Sherlock** [comment]
Could you provide the accurate stability of that card? Like this:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/0b3b2f6e-b759-4bf1-af12-45deb72acaa5)

**Comment by user1823** [comment]
<img width="92" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/91d5397d-a9f5-4255-92df-3d8746c1f454">

**Comment by L-M-Sherlock** [comment]
```
>>> next_interval(121.63, 0.94)
68
```

That's weird. Seems a bug of Anki? I need to do some research here.

Except that, do you have any other problems of the patch?

**Comment by user1823** [comment]
Other than this issue, the patch seems to be fine.

**Comment by L-M-Sherlock** [comment]
```
[rslib/src/scheduler/states/fuzz.rs:179] fuzz_bounds(68.0) = (
    63,
    73,
)
```

Anki's new fuzz range seems work in a different way from my thought.

**Comment by L-M-Sherlock** [comment]
The delta is round(1 + 0.15 * (7 - 2.5) + 0.1 * (20 - 7) + 0.05 * (68 - 20)) = 5.375. So the fuzz range is [68-5, 68+5]. I will update the fuzz range implementation in the helper add-on in the next update.
