### ISSUE TITLE
[BUG] Inconsistency of fuzz range

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#358]
The delta is round(1 + 0.15 * (7 - 2.5) + 0.1 * (20 - 7) + 0.05 * (68 - 20)) = 5.375. So the fuzz range is [68-5, 68+5]. I will update the fuzz range implementation in the helper add-on in the next update.

_Originally posted by @L-M-Sherlock in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/356#issuecomment-1925253004_

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14151042/fsrs4anki-helper.ankiaddon.zip)

@user1823, could you help me test it?

**Comment by user1823** [comment]
That card is now scheduled today. So, this seems to be better. I have left a comment in the PR.
