### ISSUE TITLE
Error when enabling "auto apply easy days when closing collection"

### ISSUE THREAD

**Issue by abdmohrat** [open-spaced-repetition/fsrs4anki-helper#365]
**Describe the bug**
I get an error message when I try to enable "auto apply easy days when closing collection".
This is the debug info:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\abdal\AppData\Roaming\Anki2\addons21\759844606\__init__.py", line 43, in on_triggered
    on_click(checked, action)
TypeError: <lambda>() takes 1 positional argument but 2 were given

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T19:01, 'None', mod]
Add Table ['1237621971', 2023-06-18T14:37, 'None', mod]
Closet For Anki ['272311064', 2022-08-12T11:27, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T18:06, 'None', '']
Edit Field During Review ['1020366288', 2022-08-29T22:38, 'None', '']
FSRS4Anki Helper ['759844606', 2024-02-10T17:13, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
More Decks Stats and Time Left ['1556734708', 2023-09-24T17:08, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T04:43, 'None', '']
Special Fields ['1102281552', 2023-11-01T18:37, 'None', mod]
Statistics for Note Types Card Types and Tags ['16703369', 2022-03-14T23:14, 'None', '']
Symbols ['1461102936', 2024-02-10T18:53, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-01-27T12:19, 'None', '']
True Retention ['613684242', 2017-11-19T22:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1020366288 1102281552 1237621971 1374772155 1461102936 1556734708 16703369 1771074083 272311064 374005964 594329229 613684242 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Additional context**
It also seems that easy days is not working properly as well. Load balance is working, but when i try to apply easy days for any day it seems that only Sunday is considered an easy day (this is appearent after rescheduling, only Sundays get less cards). Additionally, since the last addon update and anki is suddenly crashing with no error message (tho i don't know if this is related)

**Comment by L-M-Sherlock** [comment]
Fixed. Please check update for the add-on.
