### ISSUE TITLE
Bug with "Less Anki on Easy Days" feature - won't make/save changes

### ISSUE THREAD

**Issue by laurencbrooker** [open-spaced-repetition/fsrs4anki-helper#367]
My apologies if I don't describe this well, a lot of this stuff is over my head. I have been using the "Less Anki on Easy Days" feature since I downloaded the FSRS add-on to schedule cards around the weekends. I recently went to add an easy day for a single Friday because I have a test that day. However, upon closing anki, that specific date is lost in the easy days schedule. I decided to set my easy days for Fridays and Saturdays (I previously had it set for Saturday and Sunday), but when rescheduling the cards those changes were not applied. I also found that when I closed anki, the add on showed my previously set schedule for Saturdays and Sundays being the easy days. Thanks for your help!

**Environment**
 - Anki version: [23.12.1]
 - OS: [macOS 13.6.3]
 - Scheduler version: unknown
 - Optimizer version: unknown
 - Simulator version: unknown

**Comment by L-M-Sherlock** [comment]
How did you set up the easy days? Could you take a screenshot for me?

**Comment by L-M-Sherlock** [comment]
Fixed in #370. Please check update.
