### ISSUE TITLE
[Feature Request] FSRS4Anki Helper Load Balance

### ISSUE THREAD

**Issue by tjbrn** [open-spaced-repetition/fsrs4anki-helper#368]
**Is your feature request related to a problem? Please describe.**
For example, the maximum interval for a specific deck is 1 month. FSRS4Anki Helper Load Balance is enabled. The problem is: Load Balance does nothing if card interval equals maximum interval, cards are always scheduled together to the same day.

**Describe the solution you'd like**
Load Balance could schedule beyond the maximum interval OR subtract from the current interval.
`New_Interval = Interval ± Couple of days.`

**How to reproduce**
1) Download and import deck:
https://drive.google.com/file/d/1lvv_6S4ocV4t1QZkQai068B0TuuEzMN8/view?usp=sharing

2) Enable FSRS and FSRS4Anki Helper Addon + Load Balance;

3) Study deck. Answer Good or Easy;

4) Due date is the same for all cards.

**Comment by L-M-Sherlock** [comment]
The load balance feature doesn't work with the scheduler. It only works when you reschedule cards with the helper add-on.

**Comment by L-M-Sherlock** [comment]
Anyway, I update the add-on to support load balance with short max interval when rescheduling. You can check the update of add-ons and reschedule all cards.
