### ISSUE TITLE
[Feature Request]
open-spaced-repetition/
 fsrs4anki_previewer in built into anki or the helper addon

### ISSUE THREAD

**Issue by salmanuc** [open-spaced-repetition/fsrs4anki-helper#369]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Be built into anki or the helper addon
**Describe alternatives you've considered**
Using this right now https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_previewer

**Additional context**

**Comment by L-M-Sherlock** [comment]
The problem is I don't know where to add it because it relies on the FSRS parameters from the specific preset.

**Comment by salmanuc** [comment]
Perhaps add this feature with the planned simulator to be built into anki https://github.com/open-spaced-repetition/fsrs-rs/pull/141
There can be provided an option to switch between preveiwer and simulator for a particular preset and deck.
