### ISSUE TITLE
[BUG] Attempting to advance cards in all decks causes: TypeError: '<' not supported between instances of 'complex' and 'float'

### ISSUE THREAD

**Issue by cbs-cbs** [open-spaced-repetition/fsrs4anki-helper#374]
**Describe the bug**
I click "Advance cards in all decks," then I get

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/157660944/3c408ffb-bdc3-4b89-acea-6ae3e32daf16)

Tried all the standard troubleshooting methods... still happening.

The debug info provided by Anki:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\759844606\__init__.py", line 54, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did))
  File "C:\Users\Chris\AppData\Roaming\Anki2\addons21\759844606\schedule\advance.py", line 73, in advance
    cards = sorted(cards, key=lambda x: (1 - (1 / x[6] - 1) / (1 / x[5] - 1), -x[2]))
TypeError: '<' not supported between instances of 'complex' and 'float'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Table ['1237621971', 2023-06-18T04:37, 'None', mod]
Add Tag and Move 21 ['1923996023', 2021-11-21T09:16, 'None', mod]
FSRS4Anki Helper ['759844606', 2024-02-18T01:32, 'None', mod]
Opening the same window multiple time ['354407385', 2023-11-04T18:59, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
True Retention ['613684242', 2017-11-19T12:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1237621971 1771074083 1923996023 354407385 613684242 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**To Reproduce**
[See above]

**Expected behavior**
Advancing cards...

**Screenshots**
[See above]

**Environment**
See debug info above; will provide any more info on request

**Additional context**

**Comment by L-M-Sherlock** [comment]
Could you share the collection file with me to reproduce this bug?

**Comment by cbs-cbs** [comment]
Sent link to collection to your email as provided in your profile.

**Comment by L-M-Sherlock** [comment]
> Sent link to collection to your email as provided in your profile.

It's too large. Could you exclude the media file? The network is slow in China.

**Comment by cbs-cbs** [comment]
Done

**Comment by L-M-Sherlock** [comment]
<img width="800" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/490ca07d-1046-4a74-bd88-88b111878c1c">

The problem is caused by this card. It's due in 2024-05-22, but its interval is 9 days. So its last review is done in the future, which cause the problem.

**Comment by cbs-cbs** [comment]
What!? But _how_??  I believe on that one I used Anki's native "Set Due Date..." function - does this break the algorithm, by somehow throwing the card in the future with its interval remaining the same?

**Comment by L-M-Sherlock** [comment]
I update the add-on on AnkiWeb. The patch solved this case by setting the elapsed days to zero when it's negative.
