### ISSUE TITLE
[Question] To use "Easy days" feature after Ankidroid 2.1.70

### ISSUE THREAD

**Issue by hsseek** [open-spaced-repetition/fsrs4anki-helper#376]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
As [Ankidroid](https://github.com/ankidroid/Anki-Android) 2.1.70 has adopted FSRS scheduler, I supposed the interval assigned from [Ankidroid](https://github.com/ankidroid/Anki-Android) with FSRS on should be the same as Anki on PC, which means `Auto reschedule cards reviewed on other devices after sync` would do nothing. But I found that FSRS4Anki Helper still reschedule intervals for some cards. So, I wondered:

1. Why do some cards still need reschedule even though they were scheduled by the same FSRS parameters on Ankidroid? Is it because of `Load Balnce when rescheduling`?
2. I really liked your `Easy days` feature. I understand it requires `Load Balance when rescheduling`. In order to have cards answered on [Ankidroid](https://github.com/ankidroid/Anki-Android) not assigned on the `Easy days`, do I have to keep `Auto reschedule cards reviewed on other devices after sync` and `Load Balance when rescheduling` on? (Otherwise, `Load Balance when rescheduling` and `Reschedule all cards` manually?)

**Comment by L-M-Sherlock** [comment]
Yeah. Load Balance may change the intervals for some cards.

Load Balance hasn't been integrated into Anki. So you need to keep them on with the helper add-on.
