### ISSUE TITLE
[BUG] Easy days percentage dialog not working

### ISSUE THREAD

**Issue by neonmei** [open-spaced-repetition/fsrs4anki-helper#379]
Hi team! before anything else thank you so much for your work on fsrs, such an amazing project :smile: 

the form questions  :point_down: 
__

**Describe the bug**
I try to change the easy days percentage and popup with slider never appears. I get the error show in the screenshot section.

**To Reproduce**

1. Went to Tools -> FSRS4Anki Helper -> Less Anki on Easy Days [...] -> Set Percentage
2. Set a value, for example 0% or 20% Easy days on Weekends and save. Maybe exit Anki or do something else.
3. Try opening the same dialog again to alter the percentage, no dialog opens and error shown above opens instead.

**Expected behavior**

change the easy days percentage inside Anki UI :D

Not a Python/Qt developer, but the error message relates to an invalid float type. What I've googled is that [QSlider.setValue()](https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QAbstractSlider.html#PySide6.QtWidgets.PySide6.QtWidgets.QAbstractSlider.setValue) seems to expect an integer and code seems to pass a float when building the main interface ... here:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/80ff3e7304f48b43d6eefbf9daff046198094494/schedule/easy_days.py#L194-L197

If I change this:

```python
  self.slider.setValue(self.config.easy_days_review_ratio * 10)
```
to this:

```python
  self.slider.setValue(int(self.config.easy_days_review_ratio * 10))
```

Dialog builds ok and value gets updated. I didn't open a PR because my yubikey just borked and can't find my backup one.

**Screenshots**

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/43313178/c051b76b-ea89-4c09-bee7-6a9d903e635d)

**Environment**
 - Anki version: ⁨23.12.1 (1a1d4d54)⁩
 - Python 3.11.8 Qt 6.6.2 PyQt 6.6.1
 - OS: Linux/NixOS 23.11
 
**Additional context**
Debug Info as provided by Anki dialog:

```
Anki 23.12.1 (1a1d4d54) (src) (ao)
Python 3.11.8 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.7.9-x86_64-with-glibc2.38

Traceback (most recent call last):
  File "/home/neonmei/.local/share/Anki2/addons21/759844606/__init__.py", line 54, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did))
                                                 ^^^^^^^^
  File "/home/neonmei/.local/share/Anki2/addons21/759844606/__init__.py", line 165, in <lambda>
    lambda did: easy_days_review_ratio(did, config), "Set Easy Days Review Percentage"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neonmei/.local/share/Anki2/addons21/759844606/schedule/easy_days.py", line 239, in easy_days_review_ratio
    mw.easyDaysReviewRatioSlider = EasyDaysReviewRatioSlider(config)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neonmei/.local/share/Anki2/addons21/759844606/schedule/easy_days.py", line 197, in __init__
    self.slider.setValue(self.config.easy_days_review_ratio * 10)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Simulator ['817108664', 2023-11-06T14:26, 'None', '']
AnkiDraw - Draw and write using mouse and stylus with pressure support ['1868980340', 2024-03-09T08:53, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T07:18, 'None', '']
Chinese Support 3 ['1752008591', 2024-02-25T06:37, 'None', mod]
FSRS4Anki Helper ['759844606', 2024-03-02T08:06, 'None', mod]
Hanzi Stats ['181243826', 2023-12-03T19:34, 'None', mod]
Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']
Study Time Stats ['1247171202', 2024-02-24T13:59, 'None', '']
True Retention ['613684242', 2019-04-22T00:29, 'None', '']

===IDs of active AnkiWeb add-ons===
1247171202 1752008591 1771074083 181243826 1868980340 2494384865 613684242 759844606 817108664

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Enhance main window ['877182321', 2023-10-22T17:28, 'None', mod]
Reset review log ['1345711295', 2020-06-05T04:03, 'None', '']
```

**Comment by L-M-Sherlock** [comment]
Thanks for your report! I commit a patch to fix it and update the add-on in AnkiWeb. Now you can check updates for the add-on to download the latest version.
