### ISSUE TITLE
不能重排

### ISSUE THREAD

**Issue by xjqm-tao** [open-spaced-repetition/fsrs4anki-helper#38]
Anki 版本⁨2.1.60 (76d88073) qt5⁩
插件版本2023-03-05
FSRS4Anki v3.14.3 Scheduler Qt5
用插件重新安排卡牌出现一个警告框：
The number of deckName, w, requestRetention, maximumInterval, easyBonus, or hardInterval unmatch.
Please confirm each item of deckParams have deckName, w, requestRetention, maximumInterval, easyBonus, and hardInterval.

我之前都没用过这插件，我的anki V3自定义排程FSRS代码已经设置好的

**Comment by L-M-Sherlock** [comment]
你的 FSRS4Anki 是否遗漏了什么配置？请把 deckParams 的内容贴出来让我看看。

**Comment by xjqm-tao** [comment]
> 你的 FSRS4Anki 是否遗漏了什么配置？请把 deckParams 的内容贴出来让我看看。

噢，我刚刚排查出来了，我的FSRS4Anki 顶部加了几行类似这样的
//全局参数备份"w": [0.7567, 0.693, 5.2113, -0.9961............
原来插件是正则匹配获取参数的，这些注释干扰了匹配。
建议直接匹配const deckParams = [...]这一块代码，然后转为对象，这样方便调用参数

**Comment by L-M-Sherlock** [comment]
注释问题未来会解决。
