### ISSUE TITLE
[Feature Request] Knowledge acquisition per hour stat

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#382]
**Is your feature request related to a problem? Please describe.**
A suggestion was made by this user: https://forums.ankiweb.net/t/clarify-what-optimal-retention-means/42803/39?u=expertium.

**Describe the solution you'd like**
We already have an "Estimated total knowledge" stat. All that's necessary is to divide it by the sum of review times (in seconds) for each card and multiply it by 3600. The final number can be interpreted as the average number of cards memorized per hour *of actively reviewing cards in Anki*.
Knowledge acquisition per hour = Estimated total knowledge*3600/sum(Total time),
where Total time is the amount of time spent per card. For example, if a card has been reviewed two times, the first review took 30 seconds, and the second review took 10 seconds, then the total time is 40 seconds. sum(Total time) sums all total times of all cards, except for (re)learning cards.

**Comment by Expertium** [comment]
@L-M-Sherlock is this really difficult? Anki stores the time for each review, so shouldn't that information be easy to fetch?

**Comment by L-M-Sherlock** [comment]
I think this feature is not urgent, right? I would be happy if someone could contribute to it. I'm busy in this month, because my coauthor and I need to write rebuttal for our paper.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14976918/fsrs4anki-helper.ankiaddon.zip)

**Comment by Expertium** [comment]
Nice! I suggest the following renaming change:
`_line_now(i, "Knowledge acquisition rate", f"{estimated_total_knowledge / (time_sum/3600):.2f} cards/hour")`

And then you can release it.
