### ISSUE TITLE
[BUG] Huge backlog of cards created when I try to apply easy days 

### ISSUE THREAD

**Issue by franceskoback** [open-spaced-repetition/fsrs4anki-helper#383]
**Describe the bug**
When I try to follow these instructions (https://www.reddit.com/r/Anki/comments/1attbo1/explaining_fsrs_helper_addon_features/ information ) 
and try to apply easy days, it for some reason just creates a huge backlog of cards that make it so I have over 15000 cards due today instead of 0. 
<img width="753" alt="Screenshot 2024-04-07 at 1 08 04 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/3d1f3322-65be-4c7b-84ba-bb12e464ec3c">

**To Reproduce**
1. Tools 
2. FRFS anki helper 
3. Less anki on easy days (requires load balancing) --> easy monday
4. Apply easy days now ----> it says "please enable load balance first" so I go to tools and click 
5. Aply load balance when rescheduling. 
6. I then try to click "apply easy days now". It then says "Please either enable FSRS in your deck options, or disable the FSRS helper add-on." so I 
7. go into my Anking deck and press options and then go down to advance and toggle FRFS and press save. It uploads to update all of my many, many cards. Scary. I press save. 
8. I also go into tools and set "easy days review percentage to 70%" !!! so its almost 100%-- shouldn't change the deck that much.  
9. I click "apply easy days now". It says 4380 cards updated in 1.08 seconds. And now I went from having 200 cards left for today to now having over 1800 cards due today.  I have done my anki every day in a row for months and never have more than 300 cards a day. 

**Expected behavior**
I wanted to just have slightly fewer cards on Mondays. 

**Screenshots**

**Environment**
 - Anki version: Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
 - OS: Mac OS Sonoma 14.2.1 
 - Scheduler version: [e.g. v1.0.0]
 - Optimizer version: [e.g. v1.0.3]
 - Simulator version: [e.g. v1.1.0]

<img width="763" alt="Screenshot 2024-04-07 at 1 16 59 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/6039fc3b-89fe-4d1a-b050-af54ef7b585c"> 

**Additional context**
Please assist! Would love to have this working, but it's buggy now.

**Comment by franceskoback** [comment]
<img width="778" alt="Screenshot 2024-04-07 at 1 25 22 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/2882546e-9827-4347-bff4-87588d63fa0b">
<img width="724" alt="Screenshot 2024-04-07 at 1 26 24 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/1f626ba0-c710-40f8-b213-1606f360d95d">

**Comment by L-M-Sherlock** [comment]
Could you share your collection file with me to reproduce this bug?

**Comment by franceskoback** [comment]
Yes, how would you like me to do that?

**Comment by L-M-Sherlock** [comment]
Google Drive is OK.

**Comment by aleksejrs** [comment]
> Yes, how would you like me to do that?

@franceskoback, there is a link under https://github.com/open-spaced-repetition/fsrs4anki?tab=readme-ov-file#contribute to send files to L-M-Sherlock without *outright* publishing them.

**Comment by franceskoback** [comment]
submitted, thank you

**Comment by L-M-Sherlock** [comment]
<img width="768" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/3f0f073f-97df-41f4-aa81-7c33da25a8a0">

I find that your true retention is ~80%. That explains that the huge backlog. Please set your desired retention to 80% to get a small backlog.

**Comment by user1823** [comment]
@L-M-Sherlock, to prevent this problem, we can do something like the following.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/068abedb178e63ba3d08f96ecac832c3447eb845/schedule/disperse_siblings.py#L104-L110

That is, when applying Easy Days, if `due > last_review + max_ivl + 2`, we can create a new fuzz range for the card.

**Comment by L-M-Sherlock** [comment]
> Easy Days should not reschedule the cards if the user doesn't want it.

The main problem here is the user changed "easy days review percentage“. FSRS helper needs to reschedule more cards to ensure it.

**Comment by user1823** [comment]
> FSRS helper needs to reschedule more cards to ensure it.

Yes, but we can still apply the above-mentioned rule so that the cards which are due beyond their `max due + 2` are not forcefully moved into the due range.

**Comment by franceskoback** [comment]
I'm still having issues with this. I follow all the directions to a T, yet when I go to apply an easy day for JUST the 27th of april and try to have 50% of cards on that day, it reschedules a ton of cards and I go from having 0 cards due today to now over a thousand. If I set "easy days review percentage“ to 0% to avoid rescheduling too many cards, it still messes everything up, saying I have 213 cards due today, but when I go into stats, it seems I should actually have only 20 more cars today and close to 400 tomorrow. 
<img width="359" alt="Screenshot 2024-04-25 at 11 17 36 AM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/0d8c05f7-de70-4d70-8d2c-e9123735a187">
<img width="625" alt="Screenshot 2024-04-25 at 11 17 42 AM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/066d4144-c02b-4ee7-8694-7dca591e99be">
<img width="685" alt="Screenshot 2024-04-25 at 11 17 48 AM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/f67c63ec-897a-4f4e-aefb-ec932ed55654">
<img width="635" alt="Screenshot 2024-04-25 at 11 21 07 AM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/59d2ed1d-f697-4c8c-bc44-0a387ff32331">
<img width="807" alt="Screenshot 2024-04-25 at 11 21 14 AM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/31418742/60f8061a-398b-453a-b5b4-de9ad158e093">

**Comment by L-M-Sherlock** [comment]
> Easy days review percentage should only reschedule that % of cards away from that day. Why is it instead making an entire week of reviews much less so now I have so many cards due today?

Because if you apply `Easy days review percentage` twice in the same day, the method only rescheduling that day will reduce the cards more than %.

**Comment by L-M-Sherlock** [comment]
> That is, when applying Easy Days, if `due > last_review + max_ivl + 2`, we can create a new fuzz range for the card.

I'm afraid it would postpone the card every time the easy days are applied. Do you have any idea to prevent this case?

**Comment by user1823** [comment]
The following code prevents an increase in interval if the card is already beyond its fuzz range + 2.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/068abedb178e63ba3d08f96ecac832c3447eb845/schedule/disperse_siblings.py#L109-L110

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/15131441/fsrs4anki-helper.ankiaddon.zip)

**Comment by user1823** [comment]
@L-M-Sherlock, see this:

> To clarify, this rule should be applied ONLY when using Easy Days, NOT when rescheduling all cards or the cards studied in last x days.

In the above patch, it seems that a new fuzz range is created even when rescheduling all cards.

**Comment by L-M-Sherlock** [comment]
> In the above patch, it seems that a new fuzz range is created even when rescheduling all cards.

It's created when load_balance is enable.

**Comment by user1823** [comment]
> It's created when load_balance is enable.

But this means that if someone has load balance enabled and reschedules all cards after changing parameters or desired retention, the cards would not be completely rescheduled.

**Comment by user1823** [comment]
By the way, I now think that @franceskoback is also affected by the issue mentioned in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/372. Unfortunately, that issue is not easy to fix. I hope that the above patch atleast makes the feature usable.

> , it still messes everything up, saying I have 213 cards due today, but when I go into stats, it seems I should actually have only 20 more cars today 

That's because you have a backlog (as is evident in the screenshots of Stats) which means that those 193 cards are due in the past.

**Comment by L-M-Sherlock** [comment]
@franceskoback, I update the add-on on AnkiWeb. Please check the update and try to apply easy days again. I hope it would  solve your issue. If it didn't, please report it and I will reopen this issue.
