### ISSUE TITLE
[BUG] due cards are shifted around between days not marked as Easy Days

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#384]
**Describe the bug**
https://forums.ankiweb.net/t/how-to-use-the-next-generation-spaced-repetition-algorithm-fsrs-on-anki/25415/398?u=aleksej

Sometimes, due cards are shifted from non-Easy Days, at least to other non-Easy Days. Apparently it happens when Easy Days are applied automatically on restart.

One occasion was **on Monday**, shifting from Monday to later days like Tuesday and Wednesday.

Another occasion  was **discovered at 3AM Tuesday**, before Anki's "Next day starts at", so Anki's Monday. The cards were shifted from Wednesday to Tuesday. Then Tuesday had 352 cards due, and Wednesday had 92 cards due (and so did the actual Easy Days following it).
**At 11:47**, applying Easy Days shifted cards to Wednesday, now Tuesday has 27 cards due, and Wednesday has 468 cards due, and 22 reviews are backlog (I guess it's because I optimized all presets earlier, and now those cards got rescheduled). Each of the actual Easy Days has ≈90 cards due, non-Easy days have ≈222 cards due. The average for the month is 127.
In 7 days, 1294 cards are due. Remove the backlog, and the average is 182.

My time zone is UTC+3.

**Environment**
 - Anki version: 24.04
 - OS: Debian GNU/Linux testing
 - FSRS4Anki Helper: Updated 2024-03-20. 4.14.3?

**Additional context**

```json
{
    "auto_disperse": false,
    "auto_disperse_after_sync": false,
    "auto_easy_days": true,
    "auto_reschedule_after_review": false,
    "auto_reschedule_after_sync": false,
    "days_to_reschedule": 5,
    "debug_notify": false,
    "display_memory_state": true,
    "easy_days": [
        3,
        4,
        5,
        6
    ],
    "easy_days_review_ratio": 0.3,
    "fsrs_stats": true,
    "load_balance": true,
    "mature_ivl": 21
}
```

**Comment by aleksejrs** [comment]
Sometimes I "Optimize all presets" and don't reschedule the cards. Would that move due cards like that when Anki applies Easy Days?

**Comment by L-M-Sherlock** [comment]
Give it a try: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14917061/fsrs4anki-helper.ankiaddon.zip)

**Comment by L-M-Sherlock** [comment]
> Does applying Easy Days reschedule the dues to when they would be if I rescheduled all cards?

Yes. Easy days are also considered in rescheduling all cards.

**Comment by L-M-Sherlock** [comment]
> But it seems like Load Balancing makes today "easy" even without Easy Days (I did only 4 reviews).

Could you share the screenshot of your Reviews in Stats?

**Comment by aleksejrs** [comment]
> > Does applying Easy Days reschedule the dues to when they would be if I rescheduled all cards?
> 
> Yes. Easy days are also considered in rescheduling all cards.

I mean the other way:
1. I did NOT reschedule cards explicitly.
2. I applied Easy Days.
3. cards that 2 moves are also rescheduled the way I did not in 1.

**Comment by aleksejrs** [comment]
> Could you share the screenshot of your Reviews in Stats?

![Screenshot_2024-04-09_13-39-05 reviews](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/e7bc471e-75ab-4804-a790-086b1a312ec7)

**Comment by aleksejrs** [comment]
Without Load Balancing, the backlog is 680 cards.
With LB without Easy Days, it's 19 cards.
With LB with Easy Days, it's about 22 cards.

**Comment by aleksejrs** [comment]
> Give it a try: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14917061/fsrs4anki-helper.ankiaddon.zip)

I'll try in an hour.

**Comment by aleksejrs** [comment]
> Give it a try: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14917061/fsrs4anki-helper.ankiaddon.zip)

Without LB: same.
With LB: rescheduling is very slow.

**Comment by L-M-Sherlock** [comment]
> With LB: rescheduling is very slow, might take 40 minutes or over an hour.

How much time did it take in the previous version?'

> Without LB: same.

Do you mean `Wed` is still treated as easy day?

**Comment by aleksejrs** [comment]
> > With LB: rescheduling is very slow, might take 40 minutes or over an hour.
> 
> How much time did it take in the previous version?'

A few minutes for over 60000 cards. Not 500 cards/23s.

> 
> > Without LB: same.
> 
> Do you mean `Wed` is still treated as easy day?

I mean the Future Due graph looks similar and the backlog is the same.

**Comment by L-M-Sherlock** [comment]
> 500 cards/s, not 23-100 cards/s.

Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14918894/fsrs4anki-helper.ankiaddon.zip)

This one should be faster.

> I mean, the Future Due graph and backlog **without Load Balancing** (and so without Easy Days) are the same with this and the previous version.

So could you check whether the bug proposed firstly in current issue has been fixed? I guess you need to check it after midnight.

> today's Due decreased so much for no reason

It is another bug. I need to reproduce it with your collection file. Could you share it with me?

**Comment by aleksejrs** [comment]
> Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14918894/fsrs4anki-helper.ankiaddon.zip)

> This one should be faster.

It is about as fast as the normal one. Why is it getting slower as it goes from the first cards to the last cards?

> So could you check whether the bug proposed firstly in current issue has been fixed? I guess you need to check it after midnight.

I'll try to.

> It is another bug. I need to reproduce it with your collection file. Could you share it with me?

I will look for a subset of cards to share.

**Comment by L-M-Sherlock** [comment]
> It is about as fast as the normal one. Why is it getting slower as it goes from the first cards to the last cards?

I guess the intervals of cards are increasing during rescheduling, so load balancer needs to check more dates.

**Comment by L-M-Sherlock** [comment]
I can’t. But you can try this method: 

https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial2.md#:~:text=If%20you%20are%20too%20worried%20about%20privacy%2C%20you%20still%20have%20two%20options.

**Comment by aleksejrs** [comment]
After suspending non-new cards outside of the main deck, the issue still exists. :(

## Graphs including the backlog:

### No Load Balancing:
123 cards due today

![Screenshot_2024-04-09_18-52-06 suspxx-nolb](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/b4579b51-77e9-4041-a5bd-c08336509466)

### Load Balancing, 4 Easy Days
backlog 32
80 cards due today
419 cards due tomorrow
![Screenshot_2024-04-09_19-09-01 lb-noeasydays-backlog](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/f9f19d8a-4997-4154-821c-9460ff2fac55)



## Graphs not including the backlog:

### No Load Balancing:
123 cards due today
![Screenshot_2024-04-09_18-52-28 suspxx-nolb-nobacklog](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/a31e0775-b2bf-46da-9982-c8a064300392)

### Load Balancing, 4 Easy Days
backlog 32
80 cards due today
419 cards due tomorrow
![Screenshot_2024-04-09_19-08-37 lb-noeasydays-nobacklog](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/39a69be3-43e8-4fa3-a007-28d9178fff30)

**Comment by aleksejrs** [comment]
I removed all cards from that deck that didn't share their notes with the main deck. There still are many suspended cards and notes in the main deck.

Now there is a backlog in every case. I guess the backlog in the unused deck was pushing the Dues in the main deck out of the past into the present and future.
"Load Balance, no Easy Days" still has a lower today Due. Does the backlog reduce today's due because of load balancing, or is it still a bug?

## Without backlog:

### Load Balance, 4 Easy Days:

![Screenshot_2024-04-09_19-27-59 lb-4easydays](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/7fa3eaa4-41c2-4be6-8a84-74fca57b03aa)


### No Load Balance:

![Screenshot_2024-04-09_19-33-11 nolb-nobacklog](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/de4ed82c-13b0-43cd-ac91-41aac81fcdf0)


### Load Balance, no Easy Days:
![Screenshot_2024-04-09_19-40-45 lb-noeasydays](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/603d103d-df9f-4b87-a807-71a5b9fd2652)




## With backlog:

### Load Balance, 4 Easy Days:

![Screenshot_2024-04-09_19-28-20 lb-4easydays-backlog](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/aced5dd2-391f-46cd-b010-fd2d3be7ce21)



### No Load Balance:
![Screenshot_2024-04-09_19-33-31 nolb-backlog](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/312fa3a2-954f-4afe-a7b4-c1420ccb16d0)


### Load Balance, no Easy Days:
![Screenshot_2024-04-09_19-41-04 lb-noeasydays-backlog](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/9c633186-7ff9-45cc-9e92-e6c0eff77b09)

**Comment by aleksejrs** [comment]
> So could you check whether the bug proposed firstly in current issue has been fixed? I guess you need to check it after midnight.

Load Balancing enabled, Thu-Sun are Easy Days, auto apply easy days on closing is disabled, on sync is enabled and unused.

- After Reschedule all cards:
04-09 21:21 Today: 127, Tomorrow: 362, Total: 4,125, Backlog: 188, Avg future: 127 reviews/day, decklist: 293+33 due
- Started, without touching anything:
04-10 00:50 Today: 138, Tomorrow: 362, Total: 4,125, Backlog: 188, Avg future: 127 reviews/day, decklist: 293+33 due
- Apply easy days now:
04-10 00:54 Today:  61, Tomorrow: 427, Total: 4,104, Backlog: 213, Avg future: 126 reviews/day, decklist: 241+33 due

**Comment by L-M-Sherlock** [comment]
So could I close this issue and open an new issue to track the "low workload today with load balance" bug?

**Comment by aleksejrs** [comment]
Yes.
