### ISSUE TITLE
[BUG] Error when trying to reschedule cards with the latest copy of FSRS anki

### ISSUE THREAD

**Issue by kevinmonisit** [open-spaced-repetition/fsrs4anki-helper#39]
Bug:

This is similar to that of #34 , but it seems like the user was able to fix it by copying and pasting the latest version of FSRS4Anki. Whenever I run reschedule, I get the following message:

"The number of deckName, w, requestRetention, maximumInterval, easyBonus, or hardInterval unmatch.
Please confirm each item of deckParams have deckName, w, requestRetention, maximumInterval, easyBonus, and hardInterval."

Someone said that it was due to regex issues or incorrect deck configurations. However, I am using the the copy and pasted configs that is provided.

```javascript
const deckParams = [
  {
    // Default parameters of FSRS4Anki for global
    "deckName": "global config for FSRS4Anki",
    "w": [1, 1, 5, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2, -0.2, 0.2, 1],
    // The above parameters can be optimized via FSRS4Anki optimizer.
    // For details about the parameters, please see: https://github.com/open-spaced-repetition/fsrs4anki/wiki/Free-Spaced-Repetition-Scheduler
    // User's custom parameters for global
    "requestRetention": 0.9, // recommended setting: 0.8 ~ 0.9
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2,
    // FSRS only modifies the long-term scheduling. So (re)learning steps in deck options work as usual.
    // I recommend setting steps shorter than 1 day.
  },
  {
    // Example 1: User's custom parameters for this deck and its sub-decks.
    // Need to add <div id=deck deck_name="{{Deck}}"></div> to your card's front template's first line.
    "deckName": "Test",
    "w": [0.9798, 0.9791, 5.0456, -0.4899, -0.5519, 0.1534, 1.3595, -0.0585, 0.7584, 1.9858, -0.2139, 0.5097, 0.9906],
    "requestRetention": 0.9,
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2,
  },
  {
    // Example 2: User's custom parameters for this deck and its sub-decks.
    // Don't omit any keys.
    "deckName": "Test",
    "w": [1.2879, 0.5135, 4.9532, -1.502, -1.0922, 0.0081, 1.3771, -0.0294, 0.6718, 1.8335, -0.4066, 0.7291, 0.5517],
    "requestRetention": 0.9,
    "maximumInterval": 36500,
    "easyBonus": 1.3,
    "hardInterval": 1.2,
  }
];
```

However, I am still getting the above error?

Versions:
Anki 2.1.56
MacOS 13.0
Scheduler Version: The latest version
Plugin Version: The latest version of FSRS4Anki-Helper

Thank you guys for your hard work!

**Comment by kevinmonisit** [comment]
Actually, I'll reopen this issue. I thought I had a lead, but it didn't lead to anything.

**Comment by xjqm-tao** [comment]
Try copying the original script without adding any new comments anywhere, just adding parameters.

**Comment by kevinmonisit** [comment]
Thanks. It works now after removing comments.
