### ISSUE TITLE
Excessive Reschedules with Easy Days Auto-Apply [BUG]

### ISSUE THREAD

**Issue by Daedalus359** [open-spaced-repetition/fsrs4anki-helper#391]
**Describe the bug**
I have been using the "Auto-apply easy days upon closing collection" feature for a couple of weeks now, and the number of reschedules it performs every time I close the app seems excessive. In particular, it will do hundreds of reschedules even when I simply open and close Anki without doing any reviews.

**To Reproduce**
1. Under Tools > FSRS4Anki Helper > Less Anki on Easy Days ..., set Sunday as the easy day, easy days review percentage at 40%, and check the box to auto-apply upon closing collection.
2. Close Anki, noting the number of cards rescheduled (e.g. 847, my result just now)
3. Open Anki again right away, wait for collection sync, and close again, noting cards rescheduled (847 again, although sometimes the number changes between steps 2 and 3)

**Expected behavior**
While I don't fully understand the rules for easy day reschedules, I expect the number of rescheduled cards upon closing Anki to be, at most, comparable to the number of reviews I did since opening the app. In addition, I expect zero reschedules if I simply open and close the app without performing any reviews.

**Environment**
 - Anki version: Version ⁨24.04 (429bc9e1)⁩, Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
 - OS: Windows 10
 - Scheduler / Optimizer / Simulator version: not sure where to find these right now. They should be the versions installed by default with Anki 24.04.

**Additional context**
Anki reported an update to FSRS4Anki a few minutes before I started this report, and I verified that the problem is still occurring after installing it.

**Comment by user1823** [comment]
The short answer is that the add-on doesn't know which reviews were done since opening Anki. In other words, the add-on doesn't know when Anki was last opened. So, it reschedules the cards due in the next few days every time Anki is closed.

**Comment by Daedalus359** [comment]
> if ratio > 0, reschedule all cards due in the reschedule_range

> if ratio = 0, reschedule only those due on Easy days 

Ok thank you, the behavior makes sense if technical limitations force you to handle zero and nonzero targets differently as these comments describe. I'll close the issue.
