### ISSUE TITLE
[BUG] Discrepancy in Total Time

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#395]
**Describe the bug**
Total Time in FSRS stats is not the same as Total under Review Time in the Shift+Left Mouse Click "Stats" menu.

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/6191c059-3708-468c-9544-a954038240b0)

**Comment by aleksejrs** [comment]
"Only calculated for cards with FSRS memory states"?

**Comment by Expertium** [comment]
I thought so too, but the number of "review" cards is vastly greater than the number of "learning" cards in my case, so even if all cards in the "learning" stage are excluded, the impact wouldn't be this big

**Comment by L-M-Sherlock** [comment]
It excludes the cards which have been deleted or suspended:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/ffd02733a99fd0069c06fc052128ea8943ad3658/stats.py#L75-L88
