### ISSUE TITLE
[Question] AUTO RESCHDEULE and AUTO DISPERSE SIBLINGS slow down the responsiveness during review

### ISSUE THREAD

**Issue by fredjoe7** [open-spaced-repetition/fsrs4anki-helper#399]
**Research**

*Enter an [x] character to confirm the points below:*

- [x ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Question**

turning "on" RESCHDEULE CARDS WITH EACH REVIEW and AUTO DISPERSE SIBLINGS seems to slow down the responsiveness during review. It makes it look like the PC is slow. Disabling those two options seems to bring back the responsiveness during review.

Hoping this could be resolved.

**Comment by L-M-Sherlock** [comment]
> I understand that the "Disperse Siblings" feature is much more relevant, and should be resolved first, because it directly affects retention in sets that have many 'Siblings'.

I hope you could request it in https://forums.ankiweb.net/, because the decision is made by dae, the main developer of Anki. By the way, the dispersing method is very complex, so I'm not sure whether it would be integrated into Anki.

**Comment by Expertium** [comment]
@filipenanclarez I also rely on Disperse Siblings a lot, so I would also really like to see it implemented natively. Feel free to open an issue here: https://forums.ankiweb.net/c/fsrs/19

**Comment by filipenanclarez** [comment]
@L-M-Sherlock @Expertium done

https://forums.ankiweb.net/t/native-disperse-siblings/44683
