### ISSUE TITLE
[feature request] possibility to apply it only to selected cards or filtered decks

### ISSUE THREAD

**Issue by galantra** [open-spaced-repetition/fsrs4anki-helper#4]
**Is your feature request related to a problem? Please describe.**
I see that we can apply the helper to the whole collection or to a certain deck. But not to selected cards.

**Describe the solution you'd like**
I would like to search cards in the browser, select them, and reschedule them with the helper add-on. Either via the context menu or the top menu.

Alternatively, I would like to be able apply the helper add-on to a filtered deck.

**Describe alternatives you've considered**
I have made a filtered from the browser search/selection. Then, I used the gear icon to reschedule the cards with the helper add-on, but it didn't have any effect.

**Comment by L-M-Sherlock** [comment]
I check the add-on. It can reschedule the cards in a filtered deck. You should rebuild the filtered deck to check the result.

**Comment by galantra** [comment]
Oh yes, I tried it again, and it does change the due date! Great! Sorry for bothering you.
