### ISSUE TITLE
[BUG] How does fsrs4anki-helper or  fsrs4anki affect revlog?

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs4anki-helper#40]
I have an add-on that measures my progress over the days. I use it since Anki 2.1.26.

[Intervals Over Time Graph](https://ankiweb.net/shared/info/353453575)

To access the old graphics, you have to click on Stats with **SHIFT pressed.**
![image](https://user-images.githubusercontent.com/42243532/223671179-b0de489b-150a-494b-8ce8-4a709a2db74b.png)

But since I started using fsrs4anki I've noticed that the count doesn't match.

Example: I have 1043 studied (not new) cards.

![image](https://user-images.githubusercontent.com/42243532/223668901-bbe444bf-84c4-4f71-88a0-2f5116150e3a.png)

However, the complement informs that I have little more than 500 studied cards.
![image](https://user-images.githubusercontent.com/42243532/223669268-b4f9629e-b898-4cec-aee2-39f13973d6c5.png)

I decided to forget ALL the cards to see what happened (Using a backup base).
![image](https://user-images.githubusercontent.com/42243532/223669445-49b157dd-887d-48fe-90b3-6042a42ecec3.png)

And the number went to close to 1,000 (I imagine that it reads only the "revlog" data).
![image](https://user-images.githubusercontent.com/42243532/223670354-6fd70893-418a-4d33-9863-b12379b2e8e5.png)

Because the number is not above 1,000, i'm trying to understand if it's a bug in this addon or if fsrs4anki-helper or fsrs4anki might be creating states that the addon doesn't foresee (rescheduling?)

**Comment by L-M-Sherlock** [comment]
The code of [Intervals Over Time Graph](https://ankiweb.net/shared/info/353453575) is hard to read😅. I'm unsure how the add-on counts the number of the learned cards. Neither fsrs4anki-helper nor fsrs4anki modify the `revlog`. Only `ivl` and `due` in `card` could be modified.

**Comment by cjdduarte** [comment]
> The code of [Intervals Over Time Graph](https://ankiweb.net/shared/info/353453575) is hard to read😅. I'm unsure how the add-on counts the number of the learned cards. Neither fsrs4anki-helper nor fsrs4anki modify the `revlog`. Only `ivl` and `due` in `card` could be modified.

Thanks. I will review again based on your comment.
