### ISSUE TITLE
[Feature Request] Add a feature to clear review entries created by rescheduling

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#401]
**Is your feature request related to a problem? Please describe.**
Currently, if the user has a large collection and is using rescheduling constantly, the result will be like this:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/c6ae46be-b5a3-47e2-a955-3f7c5cf3021b)
https://www.reddit.com/r/Anki/comments/1cf2z24/ankidroid_performance_problems_likely/

**Describe the solution you'd like**
It should be possible to delete unnecessary review entries using the Helper add-on. You could add a button in Tools -> FSRS4Anki Helper that goes through all cards and removes either all such entries, or all except for the most recent one, if that is important (I don't know if it is).

**Comment by user1823** [comment]
This condition is quite rare. So, I don't think that it is worth making a new option in the add-on. The add-on is already starting to look bloated.

The user can run the following in the Debug Console to delete the reschedule entries. Then, click Check Database and force a one-way sync to AnkiWeb.
```py
mw.col.db.execute("delete from revlog where ease = 0 and factor = 0")
mw.col.mod_schema(False)
```

**Comment by L-M-Sherlock** [comment]
Yeah. The helper add-on's menu has been complicated. So I don't want to add an extra feature to deal with this rare case. user1823's advice is really useful.
