### ISSUE TITLE
[BUG] Text does not fit in the rescheduling progress window.

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#402]
**Describe the bug**
While rescheduling, the window is not large enough to fit the text with font size 15.

![progress-does-not-fit](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/1025861/778c86f0-ddbf-4bb8-ad41-db11964a0525)

**Environment**
 - Anki version: Version ⁨24.04.2 (a1fa865b)⁩ Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
 - OS: Linux

**Comment by L-M-Sherlock** [comment]
I guess it's a problem of Anki?

**Comment by L-M-Sherlock** [comment]
How could you set the font size of Anki? I cannot reproduce this issue.
