### ISSUE TITLE
[Feature Request] Set graph retention rates to 1 if no reviews occured

### ISSUE THREAD

**Issue by FSchliephacke** [open-spaced-repetition/fsrs4anki-helper#404]
The retention rate in the retention graph drops to 0 if no reviews were done in a specific range. For me this sometimes happens if I don't have any mature cards on a specific day. Maybe because I reviewed ahead or just couldn't get all my reviews done.

Setting the retention rate to 1 would make the graph easier to read as it wouldn't stretch it out so much.

**Comment by L-M-Sherlock** [comment]
Closed by #405
