### ISSUE TITLE
[BUG] Update memory state and reschedule button causes crash

### ISSUE THREAD

**Issue by sdavis175** [open-spaced-repetition/fsrs4anki-helper#413]
**Describe the bug**
When I select some buggy cards and click the "FSRS: Update memory state and reschedule", Anki encounters an error. 

**To Reproduce**
1. Go to 'Browse'
2. Select my card from my Mining Deck
3. Click on 'FSRS: Update memory state and reschedule'

**Expected behavior**
Cards should be rescheduled.

**Screenshots**
Debug Info: [error.txt](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/15324449/error.txt)
[Card Download](https://drive.google.com/file/d/1aSXBFIuqlN-p5n87xcCV250D0u33Io1b/view?usp=drive_link)

**Environment**
 - Anki version: Anki 24.04.1 (ccd9ca1a)  (ao)
 - OS: Windows 10 x64

**Additional context**
I am running this plugin on cards that I have transferred the review history from JPDB onto mined cards. Some of the card's data is a bit strange:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/72622628/f564b47f-2e3a-41b7-899e-13b0dafaa295)
Notably, the Reviews and Lapses fields are 0. However, those cards worked. 
Sometimes, the card's (specifically, the card I linked that is causing the crash) history will not display on my User's profile, however if I make a temporary new one it will sometimes fix the problem:
Current profile: ![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/72622628/5ac15df2-53c0-4603-8275-6cf7ca8f0051)
Temporary new profile: ![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/72622628/80c2444d-7882-4460-860d-2f0147d14d72)
I can send you my whole deck that I am working with if you are interested. I get this might not be a direct issue with your plugin but rather with Anki itself as well.

**Comment by L-M-Sherlock** [comment]
This card doesn't have review history, so the helper add-on cannot reschedule it. I will fix the add-on to skip this kind of cards.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/15325638/fsrs4anki-helper.ankiaddon.zip)

Could you help me test it?
