### ISSUE TITLE
[Feature Request] reschedule decks changed by "Optimize All Presets"

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#414]
**Is your feature request related to a problem? Please describe.**
"Optimize All Presets" does not say which presets' parameters were changed. If nothing or only a small deck changed, rescheduling is a waste of time. So I need a way to reschedule only the changed decks.

**Describe the solution you'd like**
A menu item like "Optimize all presets and reschedule those with improved parameters".

**Describe alternatives you've considered**
Anki's own "Reschedule cards on change" might be doing that, but it adds Manual reschedules that litter review history and break "[HUMBLE PIE: "distinct cards studied today" statistic](https://ankiweb.net/shared/info/2133933791)" for today.

**Additional context**
Anki Version ⁨24.06rc1 (c4cd8808)⁩

**Comment by L-M-Sherlock** [comment]
The helper add-on also doesn't know which presets' parameters were changed. I recommend requesting this feature in https://forums.ankiweb.net/
