### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThracianKnight1907** [open-spaced-repetition/fsrs4anki-helper#418]
**Describe the bug**

I have an anki deck with about 600 cards. The max interval is set to 21 days. All of my cards are up to date. If I hit reschedule, some of them have their due date set back in time (eg 13 may, today is 22 may). This means that now 200 cards are due.

**To Reproduce**
1. Go to the anki home page
2. Click on the gear next to the deck
3. Hit reschedule
4. see error

**Expected behavior**

**Screenshots**
![Captură de ecran de la 2024-05-22 23-16-40](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/64692701/9314e283-d3a2-4128-a523-91fc84c92ef3)

**Environment**
 - Anki version: 24.04.1
 - OS: Fedora 40 (flatpak)
 - Scheduler version:  the default (i don't know how to find it)

**Additional context**
There is only one other addon, pass/fail

**Comment by L-M-Sherlock** [comment]
> This means that now 200 cards are due.

If some of your cards have their due date set back in time, they are still due.

**Comment by ThracianKnight1907** [comment]
Isn't rescheduling supposed to happen in the future? I also found this issue that seems similar https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/137#issuecomment-1593397803

**Comment by L-M-Sherlock** [comment]
> Isn't rescheduling supposed to happen in the future?

It may also reschedule cards from the future to the past when the number of review cards due today, combined with the amount of cards you have learned today, is less than the average daily workload.

**Comment by L-M-Sherlock** [comment]
I think it's an expected result.
