### ISSUE TITLE
[Feature Request] Reschedule cards only if the new interval is different by >x%

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#419]
**Is your feature request related to a problem? Please describe.**
This is a continuation of the Discord discussion. Many users avoid rescheduling because it greatly affects their workload even if parameters changed very slightly. Solution: only reschedule cards if the new interval is x% longer/shorter than before rescheduling. Once we test this, it can be implemented natively.

**Describe the solution you'd like**
Add a configurable threshold from 0% to 30%, and I'll test how much it affects the number of due cards when I reschedule.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/15524515/fsrs4anki-helper.ankiaddon.zip)

You can configure the threshold here:

<img width="631" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/6d544689-1630-4438-8a2f-a15de4f6e1dd">

**Comment by user1823** [comment]
I think that

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/2dc880c9f37c272f55b27cfc75b40a742f71cf8f/schedule/reschedule.py#L339

should be changed to

```py
        if abs((new_ivl - card.ivl) / card.ivl) < fsrs.reschedule_threshold:
```

**Comment by Expertium** [comment]
@L-M-Sherlock Before I begin testing, I noticed a bug: if I press "Reschedule all cards" on a deck multiple times, it keeps rescheduling them, even though there shouldn't be anything left to reschedule after the first time.
Example:
First click - 448 cards rescheduled
Second click - 165 cards rescheduled
Third click - 108 cards rescheduled
Fourth click - 83 cards rescheduled

**Comment by user1823** [comment]
I think that this feature breaks load balance because the ratio would always be low when load balancing (because load balancing occurs within the fuzz range).

**Comment by Expertium** [comment]
I still don't understand why this isn't a bug. Also, please implement the change suggested [by user1823](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/419#issuecomment-2143740029)

**Comment by L-M-Sherlock** [comment]
> I still don't understand why this isn't a bug.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/210c60e2f5ba014ce140ae1e53ae4f7fd017ef46/schedule/reschedule.py#L332-L349

If the card's type is `Learn`, it's also counted as a rescheduled card.

**Comment by user1823** [comment]
But, I doubt that there would be so many learning cards.

Also, @L-M-Sherlock, what do you think about my suggestion in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/419#issuecomment-2143740029?

**Comment by L-M-Sherlock** [comment]
Fixed: [fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/15525143/fsrs4anki-helper.ankiaddon.zip)

**Comment by Expertium** [comment]
Alright, so here's the setup. I have a deck with the following stats (I optimized parameters just now):
Total Count: 1558
Average R: 90.39%
Average S: 275 days
Average D: 82%
Daily Load: 26 reviews/day

1) Right now I did all due cards, so the number of due cards is 0. Now I'll try rescheduling using the FSRS Helper add-on (click "Reschedule all cards" on that deck) with different thresholds, and report how many more due cards I get.
Threshold 0% - 16 more due cards
1% - 16
2% - 16
5% - 16
10% - 16
15% - 14
20% - 9
25% - 5
30% - 4

2) Another deck, this time with much easier material
Total Count: 2002
Average R: 93.76%
Average S: 1870 days
Average D: 53%
Daily Load: 4 reviews/day

0% - 604
1% - 604
2% - 604
5% - 604
10% - 604
15% - 602
20% - 602
25% - 602
30% - 601

3) Third deck.
Total Count: 7579
Average R: 93.68%
Average S: 914 days
Average D: 60%
Daily Load: 58 reviews/day

0% - 354
1% - 354
2% - 354
5% - 349
10% - 330
15% - 298
20% - 238
25% - 209
30% - 175


So it seems that thresholds below 10% have very little effect. @user1823 @brishtibheja you guys try it too

**Comment by brishtibheja** [comment]
> > if I press "Reschedule all cards" on a deck multiple times, it keeps rescheduling them, even though there shouldn't be anything left to reschedule after the first time.
> 
> It's not a bug because FSRS also reschedules learning cards (only update their memory state).

I think Expertium meant pressing the button consecutively.

**Comment by Expertium** [comment]
Yeah, I meant rescheduling the same deck multiple times, without undoing reschedulings

**Comment by Expertium** [comment]
> If the card's type is `Learn`, it's also counted as a rescheduled card.

It doesn't explain this behavior:
First click - 448 cards rescheduled
Second click - 165 cards rescheduled
Third click - 108 cards rescheduled
Fourth click - 83 cards rescheduled

**Comment by Expertium** [comment]
> If the card's type is `Learn`, it's also counted as a rescheduled card.

@L-M-Sherlock It doesn't explain this behavior:
First click - 448 cards rescheduled
Second click - 165 cards rescheduled
Third click - 108 cards rescheduled
Fourth click - 83 cards rescheduled

It could explain something like this:
First click - 448 cards rescheduled
Second click - 83 cards rescheduled
Third click - 83 cards rescheduled
Fourth click - 83 cards rescheduled

But that's not what's happening when I consecutively reschedule the same deck multiple times

**Comment by L-M-Sherlock** [comment]
Do you enable `load balance` or `disperse siblings`?

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/5c901b34-6995-483d-a702-49233e74b9f7)
My bad. Yes, I enabled them

**Comment by Expertium** [comment]
@user1823 @brishtibheja I suggest you to try this: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/419#issuecomment-2143818518
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/9de10625-b52f-4fa2-bdb8-dc3dfac8fde4)

And then do what I did here: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/419#issuecomment-2143949599

Also, I'm curious how enabling vs disabling Load Balance will affect results. I'll test it later

**Comment by brishtibheja** [comment]
Can't do it do it myself. Sorry. If you need my collection I can send it to you. Well I presume you don't but still.

**Comment by user1823** [comment]
I will try it when time permits, but based on your observations, I am not convinced with the effectiveness of this approach.

Example 1:
> Daily Load: 58 reviews/day
> 30% - 175

Example 2:
> Daily Load: 4 reviews/day
> 30% - 601

The number of due cards is increasing greatly even when using a threshold of 30%.

**Comment by Expertium** [comment]
Alright, I disabled Load Balance, let's try again

Deck stats
Total Count: 7581
Average R: 93.68%
Average S: 915 days
Average D: 60%
Daily Load: 60 reviews/day
0% - 549
1% - 548
2% - 546
5% - 536
10% - 484
15% - 418
20% - 351
25% - 281
30% - 224

Without Load Balance, results are quite different. Nonetheless, it seems that anything less than 10% has little to no effect, that is true both with and without Load Balance.

**Comment by L-M-Sherlock** [comment]
Fine. Seems this feature doesn't work well. We need find other ways.

**Comment by user1823** [comment]
I think that this feature should be added. However, I think that some modifications are required (see below).

Reasoning:
For some cards, the target retention (R at current due date) can be significantly different from the desired retention. If the user doesn't reschedule these cards, their true retention will suffer. However, currently, the user can reschedule either all cards or none. This feature will provide a middle path.

<hr>

> Nonetheless, it seems that anything less than 10% has little to no effect

This is likely because we have fuzz. So, using a very small value essentially means that we are rescheduling all the cards. I think that we should reschedule cards whose ideal interval is at least 25% (negotiable) different than the current one.

<hr>

### Dealing with siblings

In many cases, >1 cards of the same note will fulfill the above criteria (interval beyond 25%). If we reschedule all of them, they will become overdue and, thus, shown on consecutive days (due to sibling burying).

A way to mitigate this issue will be to reschedule the sibling whose intervals differ by the largest % and then create new fuzz ranges for the other siblings (just like we do in Disperse Siblings and Load Balance).

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/7057f7e61e620bd5f1733674e80fda98ae7de782/schedule/disperse_siblings.py#L107-L110

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/7057f7e61e620bd5f1733674e80fda98ae7de782/schedule/reschedule.py#L91-L97

**Comment by user1823** [comment]
By the way, I think that the % should be calculated with the new interval in the denominator.

E.g.
- Current interval = 30 d
- New interval = 12 d

With the current code, the % will be 18/30 * 100 = 60%.
With my suggestion, the % will be 18/12 * 100 = 150%.

Saying that the card is scheduled at an interval 150% more than the ideal interval seems to be more informative than saying that the ideal interval is 60% less than the current interval.

**Comment by Expertium** [comment]
I wonder if we should use a different % based on desired retention. At high levels of desired retention, even a difference of 1 day can be crucial because R falls of very steeply, plus, the user likely wants to keep high retention at any cost (for an exam or something). On the other hand, at low levels of desired retention, R falls off slowly so we can get away with using a larger % as a cutoff. Plus, at that point the user is likely more concerned with having fewer cards than with maintaining high retention.

I'll see if I can come up with a good approach

**Comment by brishtibheja** [comment]
> On the other hand, at low levels of desired retention, R falls off slowly so we can get away with using a larger % as a cutoff.

What do you think about those cards that are showing a positive change in interval, i.e., cards intervals are increasing. I think their intervals should be allowed to change regardless of the threshold. Am I missing something?

> Plus, at that point the user is likely more concerned with having fewer cards than with maintaining high retention.

I'll add that I'm more concerned with CMRR than anything. I don't mind reviewing stuff below DR but not below CMRR. Maybe should consider that too?

**Comment by Expertium** [comment]
1) Yes, it makes sense to always reschedule cards if their intervals have increased 
2) CMRR value is not stored, so accessing it at any moment is not  possible in Anki, and it **definitely** wouldn't be possible in the Helper add-on

**Comment by Expertium** [comment]
Ok, this ended up requiring a lot more math than I thought, but I think I got it.
First of all, let's talk about deviating from desired retention (DR).

Is being off by 1% acceptable or bad? Depends! A 1% deviation from 70% DR would put you either at 69% or 71% (depending on the sign). In terms of **odds**, odds(70%)=2.33, meaning that you are about 2.33 times more likely to recall a card than to forget it. odds(69%)=2.23, odds(71%)=2.45. So odds don't change much.
But now imagine that your DR is 99%. Being off by 1% would put you either at 100% (which is impossible in FSRS), or at 98%. odds(99%)=99, odds(98%)=49. So if your DR was 99%, you would be 99 times more likely to recall a card than to forget it, but at 98%, you are 49 times more likely to recall a card than to forget it. That's a **huge** difference!

So let's say that we are willing to accept a 5% reduction in **odds** without rescheduling. Anything more than that, and it's rescheduling time. From these new, reduced odds we can calculate the probability aka DR back, and then get new intervals. All of this is a lot of intermediate steps, so I won't bore you to death. Here:
![image](https://github.com/user-attachments/assets/d9a914bf-6ec7-423c-95ff-40c2083a3e0f)

Here's how to interpret the `new interval` column: **it's an interval such that if it is chosen instead of the true optimal interval, the odds of recalling a card will decrease by 5%.**
For example, if S=100 days and DR is 90%, the 5%-reduction-in-odds-interval is 106 days. So if 106 days is used instead of 100, the odds of recalling the card are decreased by 5%.
![image](https://github.com/user-attachments/assets/67346c8c-ec88-4b0c-b4f7-253601701d77)

Ok, but this still isn't the final thing that we want, which is a cutoff for each of DR. We want to know how much the **intervals** have to change for the odds to change by 5%. This time I used S=36500 instead of 100, to calculate the ratios more precisely. And the answer is...
![image](https://github.com/user-attachments/assets/3ad3b0b6-81cf-4a6d-9c55-43fb0abb6604)

Yeah

## A 5% reduction in odds of recall translates into a 5-6% increase in interval length across the entire range of DR values

So we're back to 5%

**Comment by Expertium** [comment]
Just in case someone is curious, here's what happens if we allow a 25% reduction in odds
![image](https://github.com/user-attachments/assets/806f2e2d-00d6-48dd-a971-a0b27a1ca1e6)

**A 25% reduction in odds of recall translates into a 34-41% increase in interval length across the entire range of DR values.**

**Comment by Expertium** [comment]
> I believe that there is a simple mathematical relationship between the odds reduction, interval ratio and desired retention. If you share that equation, we can add it to the code so that the add-on can calculate the interval ratio for the user's desired retention on the fly.

It's not that simple, but here:
```
decay = -0.5
factor = 19/81

optimal_interval = (S/factor)*((DR^(1/decay))-1)
odds=DR/(1-DR)  # this is just p(recall)/p(forgetting)
reduced_odds = 0.75*odds
new_DR = reduced_odds/(1+reduced_odds)
adjusted_interval = (S/factor)*((new_DR^(1/decay))-1)
ratio = adjusted_interval/optimal_interval  # adjusted_interval is longer than optimal_interval 
```
Trying to put all of this into a single formula would look horrible, but as a step-by-step process, it's actually not so bad.
This way we obtain the "theoretical" ratio. Now we need the real ratio:
```
real_ratio = interval(card)/interval(reschedule(card))  # old/new
if real_ratio > ratio:
    reschedule(card)
else:
    pass
```

If the real ratio exceeds the theoretical one, it means that the **old interval is too long** - odds of recall are reduced by more than 25% - and we definitely need to decrease it. If the real ratio is less than the theoretical one, it means that the old interval isn't too long, it's within the "25% reduction in odds" margin.
If you want to treat both increases and decreases equally, you'll also need this:
```
optimal_interval = (S/factor)*((DR^(1/decay))-1)
odds=DR/(1-DR)
increased_odds = 1.25*odds
new_DR = increased_odds/(1+increased_odds)
adjusted_interval = (S/factor)*((new_DR^(1/decay))-1)
ratio = adjusted_interval/optimal_interval  # adjusted_interval is shorter than optimal_interval 

real_ratio = interval(card)/interval(reschedule(card))  # old/new
if real_ratio < ratio:
    reschedule(card)
else:
    pass
```

Here if the real ratio is less than the theoretical one, then it means that the new interval is much longer than the old one, **the old interval is too short**, so rescheduling is needed.

@L-M-Sherlock I'd like you to implement this in the Helper add-on. If we're lucky an everything works well, we may be able to merge this into Anki before the next release.
