### ISSUE TITLE
[Feature Request] Don't redistribute cards with manually set due

### ISSUE THREAD

**Issue by hsseek** [open-spaced-repetition/fsrs4anki-helper#421]
I adjust due dates for some cards. For instance, while the suggested due is 27 days and my exam is in 23 days, then I'd adjust the due date to 20 or so.
When I Load Balance, the due dates are adjusted as a whole, so the card that I deliberatedly arranged on a specific day also are moved to another date. Also, Anki does not provide search options to filter cards with manually set due dates. So, my former arrangements are missing forever.

**Describe the solution you'd like**
I'd like an option to exclude cards with manually set due dates on Load Balance.

**Describe alternatives you've considered**
Load Balance on deck-wise would be great as well.

**Comment by L-M-Sherlock** [comment]
The main problem is, it's impossible to distinguish manual `set due date` and `reschedule cards on change`. So if you enable `reschedule cards on change`, the helper add-on will not redistribute all cards.

**Comment by hsseek** [comment]
Where is the `reschedule cards on change` option?

**Comment by hsseek** [comment]
If I enable `reschedule cards on change` then it would reschedule entire collcection. So I still cannot distinguish the manually set cards, right?

What does the `Load Balance when rescheduling` option do, then? 
1. What is `rescheduling`? Does it include all the actions that change due dates(e.g. Hitting "Good" on a review card).
2. What is the scope of `Load Balance`? For example, if I reschedule(while I don't know what it is exactly) a card, does the addon change the due dates of other cards as well or just the due date of the card I just rescheduled?

**Comment by hsseek** [comment]
If I `Reschedule cards in n days` then it would reshedule all the cards reviewed in n days, including cards with manually set due dates. So the cards wouldn't appear on the dates I set, instead, the dates that add-on redistributed. Am I missing something?

**Comment by L-M-Sherlock** [comment]
Oops. It's unintended. I find out the problem:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/18e9ec348a514d8499e252a9c5233757193622a3/schedule/reschedule.py#L232-L237

Because `set due date` also generates revlog. I will fix it soon.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/15799527/fsrs4anki-helper.ankiaddon.zip)
Have a try.
