### ISSUE TITLE
[Question] Easy Day correct usage

### ISSUE THREAD

**Issue by kfeine** [open-spaced-repetition/fsrs4anki-helper#427]
**Research**

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

Hi, I've been using FSRS Helper for a few months now, with easy days applied to Saturday and Sunday with a 10% percentage. I've also checked the "auto apply easy days on closing collection".

When I open Anki on Saturday or Sunday, at first I have only a few cards to review. But when easy days is then applied (either manually or by closing Anki), a _lot_ more reviews are added (maybe twice). I looked and saw that those cards to review have a negative review date. At the end, the easy days are not that easy, I find I only have less mature cards to review, but the total number is essentially the same (and I'm not learning many news cards at the moment).

For example, on 29/6 I first had 89 due cards, but after applying easy days, 124 cards showed up:
![SCR-20240629-qgh](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/23533762/22cc9e42-922c-4a1a-b4ac-7ee8bea9ea12)
And they all have a past due date:
![SCR-20240629-qps](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/23533762/e4983698-287a-4ea8-b7b9-f53ab53ef2dc)
So I don't know if I'm using Easy Days well, or if it's a bug of some kind (I've seen [this issue](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/356), but it's still occuring in my case): should I only apply easy days manually, for example on Monday? Or is there something I missed?

Thank you for your work and for your help,
Benjamin

**Comment by L-M-Sherlock** [comment]
> When I open Anki on Saturday or Sunday, at first I have only a few cards to review. But when easy days is then applied (either manually or by closing Anki), a _lot_ more reviews are added (maybe twice).

Could you share the screenshots of Future Due stats before and after the easy days is applied?

**Comment by kfeine** [comment]
Here is today's stats before applying easy days:
![SCR-20240702-gcy](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/23533762/c8c6a482-d3b1-4f60-a2a9-e2fff376967a)
And after:
![SCR-20240702-gdi](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/23533762/31e407ca-ced9-41bf-870a-c97c713576ee)
I guess I'll have to wait until next weekend to show you the stats during the weekend, when the issue is occuring

**Comment by L-M-Sherlock** [comment]
I develop a patch to alleviate this problem. Have a try:
[fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/16066222/fsrs4anki-helper.ankiaddon.zip)

**Comment by kfeine** [comment]
Thanks! I'll you know next weekend how it goes :)

**Comment by kfeine** [comment]
Hi, it's working, many thanks!

Before applying easy days:
![SCR-20240706-de2](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/23533762/8fe84e7b-3b89-4a10-8b64-a6cdf8abecbf)
And after:
![SCR-20240706-der](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/23533762/619dffa6-dbcc-4f0c-a660-b96be8d62430)
