### ISSUE TITLE
请问如何在卡片中显示当前卡片的数据？

### ISSUE THREAD

**Issue by jjy1000** [open-spaced-repetition/fsrs4anki-helper#431]
就是我记得原来修改某个代码就可以显示当前卡片难度系数之类的，大概是DSR的数值，请问现在在最新anki中如何显示呢？能不能集成在插件上显示呢？

**Comment by L-M-Sherlock** [comment]
<img width="421" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/720c6e90-a25e-49ae-8ac2-72697c056477">

插件一直都有支持。
