### ISSUE TITLE
[BUG] Add-on ignoring maximum interval

### ISSUE THREAD

**Issue by l-ika-l** [open-spaced-repetition/fsrs4anki-helper#435]
**Describe the bug**
When using Add-on, and load balancing, the future due exceeds the maximum interval set in the settings.

**To Reproduce**
1. set maximum interval to 10 days
2. Check the "Load balance on reschedule" option
3. Reschedule
4. Future due exceeds 1 month

**Expected behavior**
The future due shouldn't exceed the maximum interval

**Screenshots**

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59618441/dd8ff9ac-3c7d-464b-b803-8f6dad43a405)
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59618441/34d2361f-9745-47a4-8f82-5a399d36b03d)
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59618441/797f1033-4d92-4816-ae39-360a12889ba0)
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59618441/3dfdd9ee-ea68-4e40-a9c8-e2e5778ed2f7)
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59618441/3d5f494b-c9d2-4548-8814-d08bbe64f134)

**Environment**
 - Anki version: ⁨24.06.3 (d678e393)⁩
 - OS: Windows 10 (and android)
 - Scheduler version: latest, downloaded with the add on code "759844606" and checked for updates in anki add on manager
 -
**Additional context**
I had been using ankidroid a few times as well as I didn't know it didn't support the add on, and I think that might've caused the issue, as I didn't have this issue before I started using it.

I managed to fix it briefly by adding a new template, and rescheduling, but then after I load balanced it, it broke again and now I can't replicate the fix.

**Comment by L-M-Sherlock** [comment]
Do you set `easy days`?

**Comment by l-ika-l** [comment]
Nope

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/59618441/a8afc23d-cfc9-4b30-870c-0b5b87c7ec27)


> Do you set `easy days`?

**Comment by L-M-Sherlock** [comment]
It's weird. Could you share your collection file with me? I need to reproduce this bug.

**Comment by l-ika-l** [comment]
Not sure which collection file you need, so I uploaded the whole appdata folder to drive, here it is: https://drive.google.com/drive/folders/1M14khhBVohXBNGGVKsIhQTA4_7nrNK38?usp=drive_link

Let me know if this is what you're looking for.

**Comment by L-M-Sherlock** [comment]
I upload the patch in AnkiWeb. Please check update~

**Comment by l-ika-l** [comment]
that fixed it, thanks
