### ISSUE TITLE
[BUG] Helper rescheduling bypass custom scheduling

### ISSUE THREAD

**Issue by abdmohrat** [open-spaced-repetition/fsrs4anki-helper#438]
Thanks Sherlock for your work and continous updates.
I wanted to try the new FSRS-5 so I pasted it into the custom scheduling. But when rescheduling the cards using the addon, the cards get rescheduled based on the built in FSRS not the one in Custom scheduling.

I am using the latest version of Anki as well as the addon.

**Comment by L-M-Sherlock** [comment]
It's not a bug. In fact, the add-on reschedules your cards via the API provided by Anki client. So it cannot reschedule your cards based on custom scheduling.

**Comment by abdmohrat** [comment]
So there is no solution for this?

**Comment by L-M-Sherlock** [comment]
Yeah. There is no solution for this. FSRS-5 is still in alpha stage. When it is supported natively, the helper add-on will support it. too.
