### ISSUE TITLE
Postpone cards

### ISSUE THREAD

**Issue by dpl366** [open-spaced-repetition/fsrs4anki-helper#439]
**Research**

*Enter an [x] character to confirm the points below:*

- [ ] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ ] I have searched for similar existing questions here

**Question**

Hello, I would like to know if it's possible to postpone Anki cards in a more spread-out manner. For example, I have a deck on mathematical calculus with 500 cards accumulated. However, when I select "postpone all cards," almost 200 of those 500 cards are moved to the next day. I'm wondering if there's a way to postpone the cards so that I don't overload the following days. Specifically, I would like to postpone these 500 overdue cards in such a way that I can do 100 of them over the next five days, for example. I hope I've been clear enough, but I urgently need guidance, as I'm unable to clear this backlog of cards. Thank you for your attention, and I look forward to your response.

**Comment by L-M-Sherlock** [comment]
Do you mean this?

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/2f7b98b2-b07a-4d00-b636-108c873863a3)

The blue bar represents the cards need to dilute. The red chunks are the position they will be diluted to.

_Originally posted by @L-M-Sherlock in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/184#issuecomment-1676808496_

**Comment by L-M-Sherlock** [comment]
Before:

<img width="773" alt="image" src="https://github.com/user-attachments/assets/8d61cb88-6e76-4491-bd50-c500e5a3eadc">

Flatten:

<img width="440" alt="image" src="https://github.com/user-attachments/assets/c43c4e76-e298-4696-8141-3820e05f89bd">

After:

<img width="771" alt="image" src="https://github.com/user-attachments/assets/a6c278b5-ccd7-47a9-9a59-0e7b786bd21a">

**Comment by user1823** [comment]
With this option, the add-on flattens the curve for now. But, it will soon become a upward slope.

Reason:
The user will do new cards and fail some review cards. These cards get short intervals and increase the review load on the subsequent days so that the future load increases.

So, I think that this is not very useful.

I think that a better way to deal with this case is to temporarily use 100 as the review limit in the Deck Options.
