### ISSUE TITLE
Error for add on after updating (did not have issues with previous update)[BUG] 

### ISSUE THREAD

**Issue by user2357111317** [open-spaced-repetition/fsrs4anki-helper#441]
i updated my anki rescheduler and this is what is saying. i need to use my anki asap so if you can please help me as quickly as possible.
This is the pop up i am getting when i open my anki:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.

Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-08-08 11:58:36
Add-ons possibly involved: ⁨FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.sync", line 117, in on_future_done
  File "aqt.main", line 1027, in on_collection_sync_finished
  File "_aqt.hooks", line 4878, in __call__
  

what do i do to proceed?

**Comment by L-M-Sherlock** [comment]
I have stopped maintaining Anki 2.1.65 version of the add-on. I recommend updating to latest version.
