### ISSUE TITLE
[Feature Request] Manually set due dates should not get overwritten by resheduling of load balancer

### ISSUE THREAD

**Issue by wadid** [open-spaced-repetition/fsrs4anki-helper#442]
**Is your feature request related to a problem? Please describe.**
Manually set due dates get overwritten by load balancer.

**Describe the solution you'd like**
The manually set due dates should be kept and not get overwritten.

**Additional context**
E.g. when using functionality of manually sheduling cards (see screenshot), the set due dates are getting overwritten currently

![image](https://github.com/user-attachments/assets/2f7a0180-66c7-4400-8a1c-7eed735a9aa4)

**Comment by L-M-Sherlock** [comment]
Have a try:

[fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/16607138/fsrs4anki-helper.ankiaddon.zip)

<img width="431" alt="image" src="https://github.com/user-attachments/assets/9aecb43c-e804-4ed8-bf8a-5bcd1641a6be">

**Comment by wadid** [comment]
@L-M-Sherlock  Awesome, big thanks!!! :)
