### ISSUE TITLE
[BUG]无法分散新卡片的兄弟卡

### ISSUE THREAD

**Issue by Birdling** [open-spaced-repetition/fsrs4anki-helper#446]
**Describe the bug**
我建了一个过滤牌组，我想按照最新添加顺序来学习不同牌组的新卡片，但是我点了disperse siblings和reschedule后，新卡片还是按照第一个卡片、第一个卡片的兄弟、第二个卡片、第二个卡片的兄弟这样出现的。是不是不支持新卡片的disperse呢？如果不支持的话希望可以添加这个功能❤️
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - Anki version: [24.06.3 ]
 - OS: [sonoma 14.0]
 - Scheduler version: [不是就一个插件吗，怎么有三个呢？刚刚更新了，最新的]
 - Optimizer version: []
 - Simulator version: []

**Additional context**

**Comment by L-M-Sherlock** [comment]
FSRS Helper 插件无法修改新卡片的学习时间，这个是 Anki 本身的限制。请使用 Anki 自带的设置来防止这种情况出现：

<img width="607" alt="image" src="https://github.com/user-attachments/assets/4791975b-559a-438d-a3fe-f72ee53dfcef">

**Comment by Birdling** [comment]
好的，感谢
