### ISSUE TITLE
Less Anki on Easy Days

### ISSUE THREAD

**Issue by mitchelnelson04** [open-spaced-repetition/fsrs4anki-helper#448]
**Describe the bug**
The "Less Anki on Easy Days" feature isn't rescheduling mature cards for my AnKing Step Deck.

**To Reproduce**
Here are my current settings:
![image](https://github.com/user-attachments/assets/15599577-b32d-4753-b79a-28bc4b851431)

Verified that FSRS is enabled

Verified that my easy day review percentage is set to 0%

Tried closing the collection without success

Tried hitting the "Apply easy days now" without success

Tried hitting the "Apply easy days for a specific date" without success

**Expected behavior**
Up until a month ago the Easy Days were working perfectly. Then I noticed that it wasn't rescheduling the mature cards for Sundays in the future, but for some reason only within the AnKing Step Deck. It will reschedule immature cards in the AnKing Step Deck. In my other decks it will reschedule mature cards and immature cards.

**Screenshots**
What my Easy days used to look like where all Sundays would be 0%:
![image](https://github.com/user-attachments/assets/a9a821fe-6d01-4029-a714-2892e21b2126)

First noticed this about a month ago. This is a screenshot from last week. The few cards at the 5d future mark are some newly learned cards and were expected to be there.
What my Easy days started to look like where future Sundays would not be 0%:
![image](https://github.com/user-attachments/assets/9863195b-68b6-49b4-a4f6-4fa809ab4674)

What my Easy days now look like:
![image](https://github.com/user-attachments/assets/8eb4f96a-b887-43ca-8830-b516fb1595a5)

Mature cards that are due on my easy day:
![image](https://github.com/user-attachments/assets/0b6d4d0f-cd9b-489b-a422-89303988706e)

**Environment**
 - Anki version: [e.g. 24.06.03]
 - OS: [Sonoma 14.6.1]
 - Scheduler version: [unsure where to find, but verified add-on is up to date]
 - Optimizer version: [unsure where to find, but verified add-on is up to date]
 - Simulator version: [unsure where to find, but verified add-on is up to date]

**Comment by mitchelnelson04** [comment]
Here is that

https://drive.google.com/file/d/18ClSwwlpWEwEvmnoUWYASclVBi-Vv98W/view?usp=sharing

**Comment by L-M-Sherlock** [comment]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/6b811757-c691-4d81-9a2f-64e38b4c389c">

After clicking the button below, I get the result above: 

<img width="294" alt="image" src="https://github.com/user-attachments/assets/5a2eeca2-66c4-4399-af60-6c59c53ac817">

**Comment by L-M-Sherlock** [comment]
> Tried hitting the "Apply easy days now" without success

I don't know why it doesn't work. Could you share the config of the helper add-on? You can find it via Tools > Add-ons > FSRS Helper > Config.

Here is mine: 

<img width="631" alt="image" src="https://github.com/user-attachments/assets/a0cf9913-0b6e-4e00-9b87-10c43590d3f0">

**Comment by mitchelnelson04** [comment]
<img width="743" alt="Screenshot 2024-08-31 at 9 17 59 AM" src="https://github.com/user-attachments/assets/c156db72-2c0f-4a0c-b249-568216dbbbb4">

Here is that.

Yeah it definitely seems like it's something specific to my account or settings then if it worked just fine on your end. I wonder if it could possibly be an interaction with another add-on I have.

**Comment by L-M-Sherlock** [comment]
Could you disable all add-ons except the FSRS helper and try again?

**Comment by mitchelnelson04** [comment]
Just tried that, but looks like it didn't work either.

I then tried deleting the FSRS addon to try reinstalling it and then I got this error message. Not sure if that's helpful at all.

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.main", line 1189, in closeEvent
  File "aqt.main", line 563, in unloadProfileAndExit
  File "aqt.main", line 537, in unloadProfile
  File "_aqt.hooks", line 4130, in __call__
  File "/Users/mitchelnelson/Library/Application Support/Anki2/addons21/759844606/schedule/easy_days.py", line 72, in auto_easy_days
  File "/Users/mitchelnelson/Library/Application Support/Anki2/addons21/759844606/configuration.py", line 167, in auto_easy_days
TypeError: 'NoneType' object is not subscriptable

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])


===IDs of active AnkiWeb add-ons===


===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T07:24, 'None', mod]
Add Hyperlink ['318752047', 2023-06-18T04:39, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T03:10, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T07:34, 'None', mod]
Advanced Card Styles ['1625103157', 2021-12-28T10:49, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-08-19T01:41, 'None', mod]
Anki Palace Butler ['butler', 2022-12-26T23:22, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T10:26, 'None', '']
AnkiHub ['1322529746', 2024-09-02T08:27, 'None', mod]
Batch Editing ['291119185', 2023-10-25T17:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T09:25, 'None', mod]
Browser Resizer ['1435775540', 2023-11-11T10:16, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-30T15:58, 'None', '']
Closet For Anki ['272311064', 2022-08-12T01:27, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T08:06, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-02-29T18:22, 'v1.0.2', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T18:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T02:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T00:19, '6.18', mod]
Exam Notifier ['236593452', 2023-01-19T10:12, 'None', '']
Export Single Tag For Sharing ['960563361', 2022-04-10T14:30, 'None', '']
Extended Card Stats During Review ['1008566916', 2024-02-26T12:07, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T09:58, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T04:47, 'None', '']
Free Weekend - or Any Other Day ['742185195', 2020-04-10T04:57, 'None', mod]
Google Translate ['1536291224', 2024-05-08T07:16, 'None', '']
High Yield Tags ['1918380616', 2023-01-10T12:14, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T12:17, 'None', '']
Hint Hotkeys ['1844908621', 2023-04-14T07:13, 'None', '']
Image Editor ['307397307', 2022-09-07T21:09, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T00:15, 'None', '']
Load Balanced Scheduler ['208879074', 2019-07-23T19:37, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T11:00, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-19T15:49, 'None', mod]
More Overview Stats 21 ['738807903', 2024-08-22T02:14, 'None', mod]
No longer needed Transfer scheduling data Fixed by Shige ['274502770', 2024-08-27T11:43, 'None', mod]
Pop-up Dictionary beta ['153625306', 2019-03-23T10:32, 'None', '']
Progress Bar ['2091361802', 2019-03-02T19:27, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T05:59, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-18T20:15, 'None', mod]
ReColor ['688199788', 2024-03-02T18:45, '3.0', mod]
Reset Ease ['947935257', 2023-11-11T18:22, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2022-08-15T00:22, 'None', '']
Set Added Date ['1124670306', 2023-07-16T10:31, 'None', '']
Special Fields ['1102281552', 2024-03-19T16:34, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T04:24, 'None', '']
Straight Reward ['957961234', 2023-11-01T07:11, 'None', '']
Symbols As You Type ['2040501954', 2024-01-19T22:42, 'None', '']
Symbols ['1461102936', 2024-02-10T09:53, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-01-27T03:19, 'None', '']
True Retention ['613684242', 2017-11-19T13:43, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T12:28, 'None', mod]
Wrapper meta-addon ['396502676', 2024-06-10T03:00, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T09:22, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T07:12, 'None', mod]
rebuildempty some or all filtered decks ['104518886', 2023-05-16T15:33, 'None', '']

**Comment by L-M-Sherlock** [comment]
What's your configuration file after reinstalling the helper add-on?

**Comment by mitchelnelson04** [comment]
<img width="743" alt="Screenshot 2024-09-02 at 8 29 51 PM" src="https://github.com/user-attachments/assets/071fa76b-783c-45f5-a00e-b34757aa0a44">

**Comment by L-M-Sherlock** [comment]
I'm still in traveling, I may check the code when I reach hotel.

**Comment by mitchelnelson04** [comment]
Update: I probably should have tried this earlier, but I ended up deleting my add-ons (previously I had just disabled them) and then I reinstalled and now it's looking like it's back to normal. The easy day is rescheduling just as it's supposed to!
<img width="452" alt="Screenshot 2024-09-05 at 8 14 52 AM" src="https://github.com/user-attachments/assets/8a9f980b-588b-4579-af23-5ff5113ea92b">

**Comment by mitchelnelson04** [comment]
Thank you for the help!!
