### ISSUE TITLE
[BUG] Easy days for specific dates - Please select date first

### ISSUE THREAD

**Issue by VGenosse** [open-spaced-repetition/fsrs4anki-helper#451]
Unsure if a bug but at the least unclear:
When having selected "apply easy days on closing" but not having selected a day of the week a message pops up informing me that no date was selected, which makes sense.
However, when I have selected _specific dates__ but not a certain day of the week I also want FSRShelper to reschedule the cards every time I close the collection, so that this day doesn't get clogged up as I add more cards. This triggers the aforementioned message ("Please select a date first").

- Are cards rescheduled away from a _specific date_ if I have or have not selected "Auto-apply easy days on closing collection"?
- If they are, this error message is not intended I assume?
- If they are not, this should be added. I don't need easy days on a specific day of the week but on specific dates.

As always, thanks for your relentless help :)

Anki:
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1

FSRS4-helper: Up to date (03.09.2024)

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/16918070/fsrs4anki-helper.ankiaddon.zip)

Have a try.

**Comment by VGenosse** [comment]
Solved.

Selecting "Auto applying easy dates on closing collection" no longer triggers a "Please select a date" warning when no day of the week but instead specific dates (Apply easy days for specific dates) is selected.

Thanks!
