### ISSUE TITLE
[Question] Mature Card Question

### ISSUE THREAD

**Issue by snamaz02** [open-spaced-repetition/fsrs4anki-helper#453]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

I am currently adding a lot of cards each day studying for my exams. I wanted to flatten my workload (only the mature review cards I have to do). When I use the flatten feature, will this only apply to my old reviews? Or will it also spread out my new cards that I just added? I.e. i would prefer not to spread out the new ones I just learned, since I am just learning them, and would ideally want to spread out the mature cards that I am reviewing from months ago. I hope that makes sense. Thank you again for all of your help and effort!

**Comment by L-M-Sherlock** [comment]
Please see https://github.com/open-spaced-repetition/fsrs4anki-helper/wiki/Flatten

It explains the basic mechanism of `flatten`.

**Comment by snamaz02** [comment]
Thank you so much! I really appreciate it!

**Comment by L-M-Sherlock** [comment]
Does it solve your problem?
