### ISSUE TITLE
[Feature Request] Customize "Easy Day Review Percentage" per day

### ISSUE THREAD

**Issue by peter-moran** [open-spaced-repetition/fsrs4anki-helper#460]
**Is your feature request related to a problem? Please describe.**
Easy Days is a nice practical feature, and the intro of Review Percentage is great for tuning *how* easy I need it to be. Some days I need easier than others, though, and I'd like to customize that. In my scenario, I need to do minimal reviews on Fridays, and Sat/Sun I would like to do a medium amount of reviews. 

**Describe the solution you'd like**
Allow the Easy Days Review Percentage to apply per-day, rather than a single percentage for all days. This way I could make Fridays 0% and Sat/Sun 50% or so.

**Comment by L-M-Sherlock** [comment]
It's a challenge to customize "Easy Day Review Percentage" per day. For details, please see:
- https://github.com/ankitects/anki/issues/3116#issuecomment-2291394435
- https://github.com/open-spaced-repetition/easy-days-simulator/issues/1

To implement it, I need to refactor the `load balance` and `easy days` modules.

**Comment by L-M-Sherlock** [comment]
Please see #461, which satisfies your needs.

**Comment by peter-moran** [comment]
Cool, I think that normal / reduced / minimal is good enough for me, extra granularity is not so necessary
