### ISSUE TITLE
[Question] Can I use features like load balancing and automatic rescheduling on multiple devices at the same time?

### ISSUE THREAD

**Issue by Lolle2000la** [open-spaced-repetition/fsrs4anki-helper#467]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

When I add ons like straight rewards, it was recommended to only use the add on with a sync hook on one device. I am quite interested in the helpers load balancing functionality, so I wanted to ask if it will work if I enable it on multiple devices, together with the reschedule on sync option.

**Comment by L-M-Sherlock** [comment]
Yes. You can use them in the same time.

**Comment by Lolle2000la** [comment]
Ok, thank you!

**Comment by Lolle2000la** [comment]
Sorry, accidentally reopened this.
