### ISSUE TITLE
[Question] On newer versions of anki, will pressing reschedule in the addon and in the options screen (via the toggle) result in the same results?

### ISSUE THREAD

**Issue by Lolle2000la** [open-spaced-repetition/fsrs4anki-helper#472]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

When using the addon, two ways to reschedule the cards based on the parameters come into existence. One is via the addon and one is by turning on the toggle in the options screen. My question is: is there a difference between both or can they be used interchangebly, especially when using features like load balancing from the addon?

**Comment by Lolle2000la** [comment]
> They should be consistent by design. But if you enable the load balance, they will be different.

So I should only calculate weights in the options window and use the add-on reschedule button?

**Comment by L-M-Sherlock** [comment]
Yes, and don't forget to save your presets.

**Comment by Lolle2000la** [comment]
Ok, thank you!

Do you mean to share them here right now? Would screenshots suffice?

**Comment by L-M-Sherlock** [comment]
Did my answer solve your question? What'd you like to do by sharing the screenshots?

**Comment by Lolle2000la** [comment]
> Did my answer solve your question? What'd you like to do by sharing the screenshots?

Ah sorry, I think I misunderstood you! Yes, thank you!
