### ISSUE TITLE
[Feature Request] Enable "Easy Days" only on specific Anki Decks

### ISSUE THREAD

**Issue by emerald-pham** [open-spaced-repetition/fsrs4anki-helper#473]
**Is your feature request related to a problem? Please describe.**
I would like to use easy days in Anki, but only for certain decks. Other decks, I'm confident I would be able to do any day of the week.

**Describe the solution you'd like**
In configure easy days, have a radio box for enable easy days, or disable easy days, for each of the decks within scope for FSRS.

**Comment by L-M-Sherlock** [comment]
Could you describe how you'd like to set the specific Anki Decks via UI?

**Comment by emerald-pham** [comment]
Hello. Please see  the mockup attached in this reply. Thank you.
![Mockup](https://github.com/user-attachments/assets/674fa616-b842-45a3-a4cd-85001681c562)

**Comment by L-M-Sherlock** [comment]
This feature will be implemented in the next release of Anki natively. So I decide not to implement it in the add-on.
