### ISSUE TITLE
Wrong wording

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#475]
![image](https://github.com/user-attachments/assets/dc507f74-5ad2-4f64-8f7b-0575ecd89870)

Postponing/advancing doesn't change desired retention, it changes retrievability. This should say "Mean retrievability of postponed cards".

**Comment by L-M-Sherlock** [comment]
Target retrievability means the R of the card when it is due. It's not the desired retention.

**Comment by Expertium** [comment]
But it says "target retention", not "retrievability"

**Comment by L-M-Sherlock** [comment]
> This should say "Mean retrievability of postponed cards".

It's misleading because postponing doesn't change the retrievability. Only time and review could change it.

**Comment by Expertium** [comment]
@user1823 help with wording is appreciated

**Comment by user1823** [comment]
I think that the current wording is fine.
