### ISSUE TITLE
[BUG] HUGE discrepancy in Daily Load in Anki 24.10 and the add-on

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#480]
**Describe the bug**
Add-on stats:
![image](https://github.com/user-attachments/assets/24cef69b-1afa-4411-9b1a-7e1c6de0eb90)
Native stats (Anki ⁨24.10 (23b7d636)⁩):
![image](https://github.com/user-attachments/assets/5b6d34ab-21c9-432d-8ccf-0f608593aa94)
Add-on: 244 cards/day
Native: 608 cards/day, 2.5 times greater

**To Reproduce**
1. Go to the add-on stats
2. Check Daily Load (select "collection")
3. Go to the native Anki stats (again, select "collection")
4. Compare the values of Daily Load

**Expected behavior**
The values should be the same.

**Additional context**
I said "select "collection"", but this bug can be reproduced on individual decks, too.
Unrelated, but Daily Load should be measured in reviews/day, not just reviews.
![image](https://github.com/user-attachments/assets/2fc6554d-6202-4470-aab7-d54697c21d00)

**Comment by L-M-Sherlock** [comment]
It's a known issue, and will be fixed in:
- https://github.com/ankitects/anki/pull/3516

**Comment by Expertium** [comment]
In rc1 the discrepancy is smaller, but still very obvious.
![image](https://github.com/user-attachments/assets/c149e300-870b-433b-a71d-8e4feccf84fa)

**Comment by L-M-Sherlock** [comment]
Will be fixed in:
- https://github.com/ankitects/anki/pull/3530
