### ISSUE TITLE
[Question] Postpone just send cards for tomorrow

### ISSUE THREAD

**Issue by bguati** [open-spaced-repetition/fsrs4anki-helper#481]
**Postponing**

I LOVE FSRS Helper, but right now I cannot postpone cards anymore. I mean, I can, but it only sends all the due cards for tomorrow... it's not load balancing and dispersing cards. Can someone help?

**Comment by L-M-Sherlock** [comment]
> but it only sends all the due cards for tomorrow...

You can use postpone tomorrow again.

**Comment by bguati** [comment]
Yes, but I thought the algorithm would disperse and load balance by itself... wasn't it supposed to?

**Comment by L-M-Sherlock** [comment]
The algorithm respects your desired retention at priority. If the card is delayed too much, it cannot postpone it further more.
