### ISSUE TITLE
[BUG] users shouldn't be allowed to set every Easy Day to "minimum" or "reduced"

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#484]
**Describe the bug**
If all days are set to "minimum" or "reduced", it will behave the same as if all days were set to "normal", and the user will be confused.

**To Reproduce**
1. Go to Tools -> Add-ons -> FSRS Helper -> Less Anki on Easy Days -> Configure Easy Days
2. Configure them like this
![image](https://github.com/user-attachments/assets/af5931fb-1221-48e0-b446-5df4ff10ed58)
This shouldn't be allowed

**Expected behavior**
An error message should pop up

**Additional context**
https://forums.ankiweb.net/t/anki-24-10-release-candidate/51191/29?u=expertium

**Comment by L-M-Sherlock** [comment]
It's annoying to handle various user input. The current implementation just falls back the no easy days. It works well.

**Comment by Expertium** [comment]
We don't want users to think "Oh, I can just reduce the number of reviews on ALL days?! That's a great lifehack!"

**Comment by aleksejrs** [comment]
> We don't want users to think "Oh, I can just reduce the number of reviews on ALL days?! That's a great lifehack!"

I don't see a special problem. They can also set Desired retention too high or too low, or postpone all cards with FSRS Helper, or ask how to reschedule all cards after a vacation.

However, this UI has no instructions in it.

**Comment by aleksejrs** [comment]
It could say something with "relative" or "in relation".

**Comment by Expertium** [comment]
I think this is a case where it's better to save the user from themselves - just don't allow them to do something clearly counter-productive because they misunderstood how a feature works.
I would make a PR, if I had any idea how the Helper add-on code works :(

**Comment by aleksejrs** [comment]
I still like the idea of being able to make one or two days UN-reduced, and disable that by making them all reduced. Not that I still use the feature.

**Comment by Expertium** [comment]
https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/485
I made a PR
