### ISSUE TITLE
Why is the optimizing code in section 3 giving me 19 numbers when anki only wants 17 numbers?

### ISSUE THREAD

**Issue by rorobae0411** [open-spaced-repetition/fsrs4anki-helper#486]
- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ x] I have searched for similar existing questions here

Why is the optimizing code in section 3 giving me 19 numbers when anki only wants 17 numbers?

**Comment by L-M-Sherlock** [comment]
Which version do you use? FSRS-5 requires 19 parameters.

**Comment by rorobae0411** [comment]
I just turned on the native fsrs in the latest version of anki (24.06.3) and then tried changing the parameters

**Comment by rorobae0411** [comment]
I think it may be FSRS-4 but I am a beginner and I am unsure about how to navigate the github to find the right code to copy for FSRS5

**Comment by L-M-Sherlock** [comment]
I recommend waiting for the next stable release of Anki.

**Comment by L-M-Sherlock** [comment]
> Why is the optimizing code in section 3 giving me 19 numbers when anki only wants 17 numbers?

By the way, I don't know which optimizer you used. Could you provide the link?

**Comment by user1823** [comment]
The latest version of the Google Colab optimizer produces parameters for FSRS 5, which is supported natively in the latest beta version of Anki (24.10).

If you want to use the Google Colab optimizer with the native FSRS in Anki 24.06.3, you can use https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/v4.15.2/fsrs4anki_optimizer.ipynb

By the way, you don't need to use Google Colab optimizer with the native FSRS. You can simply press `Optimize` in Anki.
