### ISSUE TITLE
Unrealistically long intervals after rescheduing

### ISSUE THREAD

**Issue by mantixero** [open-spaced-repetition/fsrs4anki-helper#49]
I've been using the FSRS scheduler and helper since mid-December last year (when Anki 2.1.55 came out), but hadn't paid attention to what the longer intervals were for some of my cards, since the intervals for the cards coming up for review seemed realistic enough. However, after updating my scheduler code from v3.9.6 to v3.14.3 last night, making sure to leave in my custom parameters from the optimizer that I ran in December (which were based on ~14 years of reviews), I happened to finally look at some of the intervals for cards I wasn't seeing. To my surprise, the intervals for over 7000 of my cards are longer than a decade, some approaching as much as 50 years. I can tell just from a cursory look at the material on the cards that there's no way I'd remember the information that long (i.e. for the rest of my life). Again, since I only noticed the problem after updating and rescheduling, I can't say exactly when the issue occurred. Here is an example:

![egregious-interval_1](https://user-images.githubusercontent.com/38519777/225701415-fb307baf-2c51-4567-aa67-8cb5aaae3b7d.png)

I don't see how a card could go from an interval of 2.4 months to 31.17 years after just one review, but it probably has something to do with the calculation of the "s=" value in Custom Data. I'm noticing that most if not all of the cards with decades-long intervals have been reviewed for a period of time, neglected for several years, then manually repositioned as new cards to relearn since I basically needed to start over on my reviews. My Japanese kanji deck in particular has many cards like this, as I relearned kanji several times with years of neglected study in between, but it isn't limited to that one deck, as you can see in the screenshot below:

![egregious-interval_list](https://user-images.githubusercontent.com/38519777/225707376-760798cb-071f-4133-8624-fb7f34621b38.png)

If you need a copy of my collection to examine, I can provide one.

**Comment by L-M-Sherlock** [comment]
I see a large gap between 2016 and 2023 in your review history. What happened? Why is there not a manual reset in your review history?

**Comment by mantixero** [comment]
It could be that my way of resetting the card intervals was incorrect. I think what I did when manually resetting was select all relevant cards in the browser, right click, and choose "Forget". However, I don't remember what options were there in Anki at the time, and even if they're the same as now, I don't remember if I checked the box next to "Reset repetition and lapse counts". Whatever I chose, it looks like Anki correctly returned the cards to the "learning" state, and kept the intervals at realistic values until I used the FSRS Helper:

![egregious-interval_2](https://user-images.githubusercontent.com/38519777/225714554-ed1ced5c-eeab-487f-988d-6b9e44969ef8.png)

**Comment by L-M-Sherlock** [comment]
> I think what I did when manually resetting was select all relevant cards in the browser, right click, and choose "Forget".

If you press' Forget', it will generate a review log with the type `Manual` in the browser. I try it in my collection:

![image](https://user-images.githubusercontent.com/32575846/225791652-7573aae8-895a-4285-b4c9-925ed67a945b.png)

FSRS4Anki helper has considered this case. But your cards' review logs didn't contain a `Manual` review, the rescheduling couldn't deal with it normally.

**Comment by L-M-Sherlock** [comment]
I plan to fix it, so I need some revlog from your collection. Could you share them with me?

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11036996/fsrs4anki-helper.zip)

**Comment by mantixero** [comment]
Are those the w values generated from the Google Colab? I haven't ran the optimizer since December 2022. Should I run it again?

**Comment by L-M-Sherlock** [comment]
Oh, I find out the problem. The optimizer also doesn't know about the resetting of cards. I recommend setting `revlog_start_date` with '2020-01-01' in the optimizer to avoid this problem.

**Comment by L-M-Sherlock** [comment]
I will track this problem in a new issue.

**Comment by L-M-Sherlock** [comment]
> Update 2: Looking at which cards in my kanji deck came back for review, a common theme seems to be that they all entered the "Relearn" state at some point due to a 1 Rating in my reviews. However, the thing that the FSRS Helper seems to be ignoring for cards without a Relearn state in their history is the part in brackets, where a card enters a "Learn" state without a 1 Rating (i.e. Rescheduling cards as new via older Anki versions that didn't set the status type to "Manual").

I don't know why this card's first review log type is `Review`.

**Comment by L-M-Sherlock** [comment]
And why this card has a `Relearn` after a `Learn`?

![image](https://user-images.githubusercontent.com/32575846/227227301-0e0125a7-256a-4dd1-abb5-d176a5e27a92.png)

**Comment by mantixero** [comment]
Yes, both of those look strange. Those reviews were from back in the Anki 1.0 days, so it's hard to say what Anki was thinking at the time. If you need to ignore any review information from Anki 1.0, I'm personally fine with that, although I can't speak for everyone else who has used Anki this long.

**Comment by L-M-Sherlock** [comment]
OK, I decided to reset the card's interval and due if the revlog is strange.

Could you help me to test it?

[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11052384/fsrs4anki-helper.zip)

**Comment by mantixero** [comment]
I tried rescheduling all cards in my collection with the .zip file you linked, and there are now 433 kanji cards up for review (compared to 130 or so before), but there are still many cards with long intervals, as you can see:

![Screenshot 2023-03-23 111715](https://user-images.githubusercontent.com/38519777/227249862-bef43039-0e06-4446-bcb2-33df06055c83.png)

**Comment by L-M-Sherlock** [comment]
> I tried rescheduling all cards in my collection with the .zip file you linked, and there are now 433 kanji cards up for review (compared to 130 or so before), but there are still many cards with long intervals, as you can see:

I found that the ratings of these cards' all reviews are greater than or equal to 3.

**Comment by mantixero** [comment]
Whether it's reasonable to assume that I can recall the said information in 10-50 years is something I can only guess at, but I will try to put it in perspective.

I think the chances are increased if my flashcards were only testing recognition, but most if not all of my cards are production (cloze deletion) style cards, which are much more difficult to answer than cards that merely ask if I recognize the information on the front of the cards. I have to recall the correct information from memory and place it in the blanks, not just nod my head in understanding of what is already presented.

All I can say for sure is, using Anki's v2 scheduler with an interval of 0.82 for many years until December 2022, I had a recall rate of ~93% for mature (cloze deletion) cards. Targeting that same retention rate (0.93) with the FSRS scheduler, I can reasonably guess that the chances of me forgetting the information on those cards with 10- to 50-year intervals is significantly greater than 7%, which means my recall rate will end up being significantly worse than with Anki's v2 scheduler.

I'm happy with Anki's v2 scheduler results, but the number of reviews during the initial intervals made it hard to study more than 5 to 10 new cards per day, which is why I decided to try FSRS: I was hoping that FSRS could give me similar results with fewer reviews. I have a hunch that the majority of my reviews could be decreased by adjusting the 3rd-8th review intervals, not the 9th+ intervals on very mature cards. This is just my guess, and it would take many years of interval testing to prove.

I guess my question would be: does the FSRS algorithm treat cloze deletion cards differently than recognition cards? If not, I think it needs to account for the difference in difficulty between the two styles. Me adjusting Anki's v2 interval to 0.82 was my way of adjusting for the added difficulty of such cards.

**Comment by L-M-Sherlock** [comment]
> does the FSRS algorithm treat cloze deletion cards differently than recognition cards?

FSRS treats all card types consistently.

**Comment by mantixero** [comment]
That should be fine as long as my intervals are optimized based on my actual historical patterns of remembering/forgetting. Maybe having to ignore the 10+ years of reviews occurring before 1-1-2020 is why the mature intervals don't seem realistic (greater than 7% chance of forgetting).

**Comment by mantixero** [comment]
I'd like to go back to Anki's v2 scheduler, but even after setting that preference in Anki, I still have all the cards with unrealistically long intervals. How can I get their intervals back down to v2 scheduler values?

**Comment by L-M-Sherlock** [comment]
You can use `set due date` in the card browser.

**Comment by mantixero** [comment]
Wouldn't that just set the due date to something within the next 7 days? I don't want to study 7000 cards this week, I just want the intervals to go back to what they would have been if I had used the v2 scheduler for the past 5 months instead of FSRS.

**Comment by L-M-Sherlock** [comment]
So, you want a feature that could reset the interval and return to the last normal scheduling. I will deal with it in a new issue.

**Comment by user1823** [comment]
@mantixero

I have a possible solution for the problem of FSRS not working correctly for you.

The issue results from the fact that some (or most) of your cards have abnormal review history, due to which the optimizer is not working correctly.

Also, setting the revlog_start_date to 2020-01-01 in the optimizer doesn't work, probably because it means having to ignore the 10+ years of reviews occurring before 2020-01-01.

So, one possible solution I can think of is that you can move the cards with abnormal review history to another deck and then **use only the cards with "normal" review history to train the optimizer**. When you do this, keep the revlog_start_date setting at the default value. Probably, this would mean that the optimizer produces a reasonable `w` value that would produce the expected intervals.

**Comment by user1823** [comment]
If the `w` value produced by the optimizer is correct, I think that even the cards with abnormal review history would be assigned correct intervals by the helper because of the patches developed by @L-M-Sherlock (https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/51 and https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/53).

**Comment by mantixero** [comment]
Thanks for the suggestion. I think your idea would indeed result in more accurate `w` values, but finding all cards with abnormal review history is quite a daunting task given that I have 58,613 cards in my collection. I would hope that the Helper fixes (#51 and #53) could also be applied to the Optimizer so that incomplete revlogs would be ignored, and only results after a card's last Review to Learning shift would be taken into account.

**Comment by L-M-Sherlock** [comment]
I have a simple solution to filter these cards in the optimizer. Just ignore those cards reviewed before a specific date.

**Comment by user1823** [comment]
> I have a simple solution to filter these cards in the optimizer. Just ignore those cards reviewed before a specific date.

This approach doesn't work. The reason is that it is not the case where @mantixero reset all their cards on a single day.

Also, when @mantixero tried with revlog_start_date in the optimizer set to 2020-01-01, the intervals were still very long. This was probably because more than 10 years of review history was ignored when calculating the `w` values.

In the patches https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/51 and https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/53, you made the helper ignore the problematic part of the revlogs.

Probably, if the optimizer also ignores the problematic part of the revlogs but still trains on the "normal" reviews made during the same time period, it would come up with better `w` values.
