### ISSUE TITLE
[Feature Request] Consideration for cards seen outside Anki

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki-helper#491]
Sometimes I will get a review card that I don't actually know the answer to, but I will get the card right because I saw the content of the card somewhere else recently. The problem is that Anki assumes that you are only learning this content on Anki, nowhere else. But most people use Anki alongside other resources, often with overlapping content.

Example: There is a review card due today that if answered correctly, will have a new interval of 1 year. But if I just watched a lecture that covered the content on that card, I would definitely get that card right, even if I have not memorized it yet, and not see it again for another year. This is not an accurate interval for this card; the interval should be much smaller.

Potential solution: A feature to select cards in the browse window and mark them as seen. Marking the card in this way would adjust the interval to make it smaller.

**Comment by L-M-Sherlock** [comment]
I guess this add-on satisfy your need:

https://ankiweb.net/shared/info/1021636467

**Comment by akavi1** [comment]
Oh cool, I think this works
