### ISSUE TITLE
[Feature Request] Working with delay sibilings

### ISSUE THREAD

**Issue by Sterling1919** [open-spaced-repetition/fsrs4anki-helper#50]
Hi,
How does the helper work with the delay siblings add-on? If they are both set to auto on sync, which goes first and which is given priority? Any chance you could build in the delay siblings feature into the helper? Thank you very much

**Comment by L-M-Sherlock** [comment]
You can use the delay siblings add-on. I will fix it if it is incompatible with the FSRS helper add-on.

**Comment by Expertium** [comment]
I agree with user1823. Delay siblings improves the efficiency of spaced repetition, and if it's built into FSRS then you won't need to worry about compatibility with the actual delay siblings add-on, just tell the users to turn that add-on off.

**Comment by L-M-Sherlock** [comment]
I have implemented this feature. You can track it at #50

**Comment by Expertium** [comment]
Should I turn the Delay Siblings add-on off then?

**Comment by user1823** [comment]
It is not on AnkiWeb yet. Also, it still needs some final polishing.
