### ISSUE TITLE
[Question] Disperse siblings after rescheduling - does it need "breaks Load Balance"?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#507]
![image](https://github.com/user-attachments/assets/e02dbb4a-343b-4936-9de9-2a45b889bb68)

Is the "breaks Load Balance" relevant in Anki 24.11?

**Comment by L-M-Sherlock** [comment]
> Is the "breaks Load Balance" relevant in Anki 24.11?

It makes the workload unbalanced. So I think it's relevant.
