### ISSUE TITLE
[Question] How to Enable the Option to Pick Days Off in the Anki Add-On?

### ISSUE THREAD

**Issue by madeleinelion** [open-spaced-repetition/fsrs4anki-helper#517]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**

Hello,

I want to pick my days off but the option dosen't show up for me. Where can i find the the option to pick my days off? I tried to follow the tutorial but the option just dosen't show up.

Thank you so much for your help!

**Comment by L-M-Sherlock** [comment]
Deck options

<img width="800" alt="image" src="https://github.com/user-attachments/assets/1ce4ee4c-265e-40e3-bfc6-ab74f962ca95" />

**Comment by madeleinelion** [comment]
Omg thank you so much, I found it. On 12. Dec 2024, at 02:40, Jarrett Ye ***@***.***> wrote:﻿
Deck options
image.png (view on web)
