### ISSUE TITLE
[Feature Request] Detect hard misuse

### ISSUE THREAD

**Issue by galantra** [open-spaced-repetition/fsrs4anki-helper#519]
Now that we can _remedy_ hard misuse, is there a way how a user can know that they should use that feature, i.e. that they have in fact been abusing hard? 

I'm imagining a simulator, for example. It would take the user's cards or a sample of them and runs a simulation. This way, it compares if the card _would have_ performed better if _again_ had been used instead of _hard_. Is this feasible?

**Comment by L-M-Sherlock** [comment]
In my opinion, it's infeasible. We don't know who are right: the model or the user.
