### ISSUE TITLE
[BUG] Reschedule doesn't work for some (low retention?) cards

### ISSUE THREAD

**Issue by s9gf4ult** [open-spaced-repetition/fsrs4anki-helper#521]
**Describe the bug**
Reschedule doesn't affect some cards. Even if cards are explicitly selected the cards browser.

**To Reproduce**
1. Go to cards browser
2. Select cards with low retention by the query `prop:r<0.88 -is:suspended`
3. Browser shows about 1500 cards
4. Ctrl-A to select all cards
5. Right click on selected cards and "FSRS: Update memory state and reschedule"

**Expected behavior**
All selected cards are rescheduled.

**Actual behavior**
Rescheduled only 4 random cards.

**Environment**
 - Anki version: 24.11 (87ccd24e)⁩
 - OS: Linux (NixOS 24.11.20241223.6c90912)
 - Scheduler version: FSRS5
 - Optimizer version: ???
 - Simulator version: ???

**Additional context**
If select cards with high retention by query `prop:r>0.88 -is:suspended` and reschedule all the cards then everything works just fine.

My retention is set to `0.9`

Presumably the bug appeared since `Anki-24.11` because I don't remember such a behavior on `24.06`

**Comment by L-M-Sherlock** [comment]
Please provide the card's info.

**Comment by s9gf4ult** [comment]
Here are some screens of one of such cards
![image](https://github.com/user-attachments/assets/506c9c4b-e4fb-4990-90cf-fd9dbb967f9a)
![image](https://github.com/user-attachments/assets/82930921-828b-4f0c-9301-044fa1b95ee6)
![image](https://github.com/user-attachments/assets/22a334a5-fe51-46a3-88de-73f1dd27b5eb)

**Comment by user1823** [comment]
You likely used Anki's "Reschedule cards on change" feature in June. Use that feature again to reschedule your cards now.

After you do that, helper add-on's rescheduling function will start working again.

**Comment by user1823** [comment]
The problem is that, in earlier versions of Anki, the revlog entries created by "Reschedule cards on change" couldn't be distinguished from those created by "Set Due Date".

So, if the latest revlog entry is one of those, helper add-on doesn't reschedule the card in an attempt to prevent undoing the manually set due date by the user.

**Comment by s9gf4ult** [comment]
Well, this heuristics sounds reasonable for the "Reschedule cards reviewed in last 7 days" or something because it is automatic and massive. But it is weird when it works if you explicitly select cards in browser and the "reschedule selected" just does nothing without any notification. 

IMHO it shouldn't be applied in the browser at least. Or make it an explicit option in settings

**Comment by user1823** [comment]
Your argument makes sense. But, this is a problem only for those users who
- Used Anki's "Reschedule cards on change" in Anki < 24.11, AND
- Didn't use Anki's "Reschedule cards on change" in Anki 24.11+, AND
- Didn't review the card after it was rescheduled in Anki < 24.11

A case that fulfils all of the above 3 requirements is rare (yours is one). So, I don't think that changing the behaviour would be worth the trouble.

**Comment by s9gf4ult** [comment]
Well, mkay

**Comment by L-M-Sherlock** [comment]
Is this issue resolved?

**Comment by s9gf4ult** [comment]
yp
