### ISSUE TITLE
[BUG] Consider card has manual reset even if its first review kind is not learning 

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#56]
Now, we need to change this line
`if i == 0 and (revlog.review_kind not in (0, 2)) and not has_again(revlogs):`
to
`if i == 0 and (revlog.review_kind not in (0, 2)) and not (has_again(revlogs) or has_manual_reset(revlogs)):`
and define the function `has_manual_reset`.

By manual reset, I mean manual reset without the manual rating in the revlog (https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/51).

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki/issues/191#issuecomment-1500939089_

**Comment by user1823** [comment]
> By manual reset, I mean manual reset without the manual rating in the revlog ([open-spaced-repetition/fsrs4anki-helper#51](https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/51)).

I thought about it again and realised that it is better to include both manual reset with revlog and without revlog.

The reason is that it doesn't actually matter whether the manual entry is there in the revlogs or not. If the card was reset, it should not be withheld because the first review in the revlog was not of learn or relearn type.

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki/issues/191#issuecomment-1500940624_

**Comment by L-M-Sherlock** [comment]
@mantixero, here is the patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11187975/fsrs4anki-helper.zip)

It could fix the four strange cards in your collection.

**Comment by mantixero** [comment]
Thank you. I no longer see a `Reset all cards`, so I should do a `Reschedule all cards`, correct?

**Comment by user1823** [comment]
> The improvements in this helper patch were not in the optimizer, correct? If the optimizer were to have this patch applied, would it be worth re-running it to get new w values?

Yes, there was no new patch applied to the optimizer. So, you don't need to re-run the optimizer.

**Comment by L-M-Sherlock** [comment]
😁I hope my efforts worth a thumb on the helper add-on page.

**Comment by L-M-Sherlock** [comment]
I will merge and release the patch tomorrow.

**Comment by mantixero** [comment]
Sounds great! I've updated my review on the Helper add-on page, and left room for you to comment (if you want) with a specific revision number you would recommend for similarly affected users.
