### ISSUE TITLE
[Bug] Error on using Undo rescheduling of all cards

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#58]
Whenever I select the new "Undo rescheduling of all cards" option in the latest version of the Helper add-on from AnkiWeb, I get the following error:

> Error 
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
> If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
> When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
> Debug info:
> Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
> Platform: Windows-10-10.0.22621
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-04-11 20:35:49
> 
> Caught exception:
> Traceback (most recent call last):
>   File "C:\Users\<User>\AppData\Roaming\Anki2\addons21\759844606\__init__.py", line 42, in <lambda>
>     action.triggered.connect(lambda b, did=None: fun(did))
>   File "C:\Users\<User>\AppData\Roaming\Anki2\addons21\759844606\reset.py", line 43, in reset
>     reset_ivl_and_due(cid, revlogs)
>   File "C:\Users\<User>\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 183, in reset_ivl_and_due
>     card.ivl = int(revlogs[0].interval / 86400)
>   File "google.protobuf.internal.containers", line 93, in __getitem__
> IndexError: list index out of range

**Comment by L-M-Sherlock** [comment]
Do you have some cards that don’t have any revlogs?

**Comment by user1823** [comment]
Yes

**Comment by L-M-Sherlock** [comment]
OK, I will fix it tomorrow.
