### ISSUE TITLE
Reschedule not working for manually scheduled cards

### ISSUE THREAD

**Issue by tkozybski** [open-spaced-repetition/fsrs4anki-helper#64]
I set up free days to Sunday (today) and did a rescheduling of all cards. What surprised me is that it added even more cards to the review queue instead of emptying it.  

I noticed is that only cards from my “comprehension” decks that were rescheduled like that, the ones that were manually set by “Set due date” like the ones in the picture, not all of them though. Some were left untouched (the last picture). They all seem to have been rescheduled with an interval of 5 days, which is the graduation interval for that config. 

I did some testing and the ones getting the interval of 5 days hit the "if last_s is None:" line in reschedule.py. last_s is set by the second to last review (why not the last one?). If it was manual, rescheduler will treat it like a new card, because manual review kind has no button_chosen attribute, and it triggers the "# forget card" part of the logic.

I propose we treat manually rescheduled cards as review ones with rating set to 3 (good answer). Anki treats them like that.

![image](https://user-images.githubusercontent.com/5121875/232280323-3e20f987-dd8d-43f2-8fdd-b497d220cd28.png)
![image](https://user-images.githubusercontent.com/5121875/232280498-4452ab5a-ef5b-450f-89dc-3d6dcb968d77.png)
![image](https://user-images.githubusercontent.com/5121875/232281830-1c9224c9-15af-4034-a8b3-1f0ebcc02ccf.png)
![image](https://user-images.githubusercontent.com/5121875/232283439-7e331aa0-c770-4ab4-976c-27bc02e139e7.png)

**Comment by L-M-Sherlock** [comment]
> I propose we treat manually rescheduled cards as review ones with rating set to 3 (good answer). Anki treats them like that.

I don't think `Set Due Date` should be treated as a good answer. But I need to ask more people.

@user1823, @Expertium and @mantixero, what do you think of this issue?

**Comment by tkozybski** [comment]
I made a pull request that does what I propose. I tested it on my collection, and it seems to work great.

**Comment by mantixero** [comment]
I've never manually set a due date on my cards before, so I don't know how Anki treats them.

**Comment by tkozybski** [comment]
It promotes the card to review state and sets the interval to the one you typed.

**Comment by user1823** [comment]
@L-M-Sherlock

I think that what @tkozybski proposes here makes sense.

If the change only affects the cards that were manually rescheduled, most people wouldn't be affected.

Also, the people who manually rescheduled their cards would expect something similar to what @tkozybski proposed.

**Comment by user1823** [comment]
I agree that the manual rescheduling is not a review (no active recall took place). But, the proposed solution seems to be best way to deal with such cases.

**Comment by L-M-Sherlock** [comment]
OK, I will review the Pull Request tomorrow.

**Comment by galantra** [comment]
There are two ways to use Set Due Date: 
![grafik](https://user-images.githubusercontent.com/52420923/232340196-dd0c7bd3-ba29-4720-9893-c9dd5549fbbb.png)
The first changes the interval (interval-changing), the second is like burying (interval-preserving).
We should make clear which we are talking about.

# interval-changing Set Due Date

This is intended to be a way to rate a card after review where the user is able to fine-tune the interval.

If I remember correctly, the interval-changing Set Due Date also calculates whether the interval corresponds to the interval of a hard, good or easy grade. Or at least it used to do that when Set Due Date was not yet natively implemented in Anki but provided by the [ReMemorize add-on](https://web.archive.org/web/20211201021611/https://ankiweb.net/shared/info/323586997). For example:

> previous interval: 5
> Set Due Date: set interval to 25
> → Review log should treat this as an easy rating, because the new ivl is 500% of the old interval.

> previous interval: 5
> Set Due Date: set interval to 6
> → Review log should treat this as hard rating, because the new ivl is 120% of the old ivl.

And when I write "review log", I actually mean the FSRS4Anki Scheduler and Helper (for the purposes of the present discussion).

# interval-preserving Set Due Date 

Since this is just long-term burying, it should not be considered as a review/rating.

**Comment by L-M-Sherlock** [comment]
Yep. And it is possible that users `Set Due Date` in Card Browser directly. They could not see the content of the cards.

**Comment by L-M-Sherlock** [comment]
There perhaps are two purposes of `Set Due Date`. In SuperMemo, there are two way to change the the date of the next [repetition](https://supermemopedia.com/wiki/Repetition):

- Reschedule repetition: Ctrl+J adds to the [interval](https://supermemopedia.com/wiki/Interval) ([last repetition](https://supermemopedia.com/wiki/Last_repetition) unchanged). It should be used to change the date of the repetition in cases when the repetition did not take place (or should be ignored).
- Execute repetition: Ctrl+Shift+R executes a [repetition](https://supermemopedia.com/wiki/Repetition) and sets a new [interval](https://supermemopedia.com/wiki/Interval) ([last repetition](https://supermemopedia.com/wiki/Last_repetition) set to today). It should be used when the repetition took place or should take place.

For example, you see a question that you do not want to answer and do not want to see for a year (use Ctrl+J and 365 day interval). If you see a question that you forgot or must remember perfectly, execute a repetition and schedule a new one at a set interval.

Original source: https://supermemopedia.com/wiki/Ctrl%2BJ_vs._Ctrl%2BShift%2BR
