### ISSUE TITLE
[Feature Request] Auto disperse siblings after rescheduling.

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#67]
Now, need to add an option to call this function on every sync (after the rescheduling), which would ensure that after reviews are done on other devices, the siblings are separated.

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki/issues/188#issuecomment-1510312853_

**Comment by L-M-Sherlock** [comment]
To improve performance and prevent wastage of network resources, I suggest you filter the cards whose intervals were changed after the sync (as I suggested in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/46#issuecomment-1509660879). (We may need to filter the "notes" rather than "cards" because the function must operate on all the siblings.)

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki/issues/188#issuecomment-1510312853_

So auto dispersing siblings only be called after synced? Or should it also be called after manual rescheduling?

**Comment by user1823** [comment]
> So auto dispersing siblings only be called after synced? Or should it also be called after manual rescheduling?

It should be called after both.

**Comment by L-M-Sherlock** [comment]
Due to #70, filtering the nid before dispersing siblings is meaningful because the number of rescheduled cards is few. But manual rescheduling will change all cards' intervals (especially when load balance is enabled). In this case, is it helpful to filter nid?

**Comment by user1823** [comment]
Do you mean to say that if the user reschedules all the cards, then we can skip the filtering and proceed directly to dispersing the siblings?

If this is what you are asking, I agree with it.

**Comment by L-M-Sherlock** [comment]
> Do you mean to say that if the user reschedules all the cards, then we can skip the filtering and proceed directly to dispersing the siblings (for all the cards)?

Yep. And I want to know how much time dispersing siblings costs in your collection. Is it faster than rescheduling?

**Comment by user1823** [comment]
- Rescheduling 8481 cards took 10 seconds.
- Dispersing 2956 cards in 1478 notes took 3 seconds.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11249229/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/1fd9cc285ab2d0fe2b9dc511ae1df4728f55638b
Note: I haven't implement it after manual rescheduling.

**Comment by user1823** [comment]
I tried it.

It didn't show any message about dispersing the cards after syncing my reviews to Anki Desktop. So, did it disperse them and not show any message? Or it didn't disperse?

**Comment by user1823** [comment]
But, some of them had siblings.

**Comment by L-M-Sherlock** [comment]
Did you review them on another device? How many cards did FSRS auto-reschedule?

**Comment by L-M-Sherlock** [comment]
Here is the code:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/1fd9cc285ab2d0fe2b9dc511ae1df4728f55638b/sync_hook.py#L15-L51

I don't know where the bug happened.

**Comment by user1823** [comment]
I tried to change the following lines

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/1fd9cc285ab2d0fe2b9dc511ae1df4728f55638b/sync_hook.py#L50-L51

to
```
    if affected_notes > 0:
        disperse_siblings(None, filter=True, filtered_nid_string=",".join([str(nid) for nid in rescheduled_nids_with_siblings]))
        return
```

But, it still didn't work. 

Is it possible that Anki doesn't allow showing two tooltips one after the other and so the tooltip telling the user about the dispersing of cards didn't appear?

Also, the `askUser(f"Rescheduling done. {affected_notes} notes with siblings affected. Disperse siblings?")` part would make the user approve dispersing the cards after every sync. Doesn't it make sense to store the user's choice in the config file?

**Comment by user1823** [comment]
What does the `data like '%"cd"%'` part mean?

Also, is it possible that the code is checking for the presence of both the siblings within the reviewed cards? If this is the case, it would always output zero notes unless the reviews from more than one day are synced together or the "Bury siblings" is turned off in deck options.

**Comment by L-M-Sherlock** [comment]
> What does the data like '%"cd"%' part mean?

It is used to check whether the card has custom data.

**Comment by user1823** [comment]
> The new tooltips will close the old one.

Then, we might want to save the contents of the reschedule tooltip and display it along with the disperse_siblings tooltip because currently, the reschedule tooltip is not being shown at all (if the disperse_siblings is called without using the if statement).

According to my experimentation, {affected_notes} is always yielding zero. So, you might have to check the following code thoroughly:
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/1fd9cc285ab2d0fe2b9dc511ae1df4728f55638b/sync_hook.py#L33-L49

Also, does this code work for you if you do your reviews on another device and sync to Desktop?

**Comment by L-M-Sherlock** [comment]
> Also, does this code work for you if you do your reviews on another device and sync to Desktop?

Instead, the current code only works for this case.

**Comment by user1823** [comment]
I mean that does it work for you? That is, have you tried using it?

**Comment by user1823** [comment]
@Expertium,
If you do your reviews on other devices and then sync your reviews to Anki Desktop, can you help us test this new feature?

Brief summary of what it should do:
When you sync reviews to Anki Desktop, it will automatically reschedule the synced cards and then disperse the siblings for the synced cards.

According to my testing, the reschedule part is working fine. But, the disperse siblings part is not. (The filtered nids for passing into the disperse_siblings function is empty.)

Can you spot any errors in the code?

**Comment by Expertium** [comment]
I'm not a programmer, I barely know some basic Python stuff.

**Comment by L-M-Sherlock** [comment]
> The filtered nids for passing into the disperse_siblings function is empty.

In my review, the bug seems to be located in the SQL query. Could you check those cards reviewed in another device? Did they have some characteristics?

**Comment by user1823** [comment]
> Could you check those cards reviewed in another device? Did they have some characteristics?

Like what characteristics?

**Comment by L-M-Sherlock** [comment]
Are they buried?

**Comment by L-M-Sherlock** [comment]
I find out a possible cause. I use `queue` instead of `type` to filter the cards. I will fix it and submit the patch later.

**Comment by user1823** [comment]
The reviewed cards are not buried. But, their siblings definitely are buried (Anki buries them automatically.)

**Comment by L-M-Sherlock** [comment]
> The reviewed cards are not buried. But, their siblings definitely are buried (Anki buries them automatically.)

Thanks for your valuable information. I will deal with this case.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11261942/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/751787415961c90b9766b1b5a2c33184d064f3e9

**Comment by user1823** [comment]
It works fine after this patch. Thanks!

But, I want to share the following points:
- Currently, the helper requests the user to approve dispersing the cards after every sync. Doesn't it make sense to store the user's choice in the config file?
- If we indeed store the user's preference in the config file and remove the askUser function, the two tooltips (reschedule + disperse_siblings) would be scheduled to come one after the other. This would cause the reschedule tooltip to be not shown at all because the disperse_siblings tooltip will close the reschedule one. So, we might want to save the contents of the reschedule tooltip and display it along with the disperse_siblings tooltip.
