### ISSUE TITLE
[BUG] Error when rescheduling

### ISSUE THREAD

**Issue by tnyjcb** [open-spaced-repetition/fsrs4anki-helper#72]
Unable to reschedule cards after the recent update. Advance, disperse, etc. all seem to be working correctly.
```
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-13.3.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-18 10:44:35
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/tnyjcb/Library/Application Support/Anki2/addons21/759844606/__init__.py", line 45, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did))
  File "/Users/tnyjcb/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 248, in reschedule
    fsrs.due_cnt_perday_from_first_day[due_before] -= 1
KeyError: 620
```

**Comment by L-M-Sherlock** [comment]
It seemly relates to #65. But I need more data to confirm it. Could you share the collection file with me? Or the related deck files?

**Comment by tnyjcb** [comment]
[collection-2023-04-18@11-09-42.colpkg.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11260578/collection-2023-04-18%4011-09-42.colpkg.zip)

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11260622/fsrs4anki-helper.ankiaddon.zip)
Could you test it?

**Comment by tnyjcb** [comment]
That's fixed it. Everything is working as before. Thank you.
