### ISSUE TITLE
[Bug] Inconsistencies in number of notes and cards in auto-disperse siblings

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#77]
In the auto-disperse siblings feature, I am seeing some inconsistencies between the number of notes and the number of cards in the tooltip message.

For example, today, after dispersing the synced reviews, the helper showed the message "92 cards in 47 notes dispersed." Now, how can 47 notes with 2 cards each have 92 cards in total?

Yesterday, the number of cards shown was some odd number (I don't exactly remember what it was). Now, my notetype is such that a note can have either 1 or 2 cards, but not more than 2. So, how can notes with siblings have an odd number of cards in total?

**Comment by L-M-Sherlock** [comment]
Do you use filtered decks? Those cards in filtered decks would not be dispersed in the current version.

**Comment by user1823** [comment]
Yes, I use filtered decks.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11300915/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/740338d90a6db820fbb3489862c244d1c28c1909

**Comment by user1823** [comment]
It seems to work fine. Thanks!
