### ISSUE TITLE
[Feature Request] Deck specific reschedule of recent reviews

### ISSUE THREAD

**Issue by Deminix** [open-spaced-repetition/fsrs4anki-helper#79]
Can you add an option to reschedule the review cards from the last few days per deck instead of just globally from the drop-down menu next to each deck?

**Comment by L-M-Sherlock** [comment]
When and where will you need this feature?

**Comment by Deminix** [comment]
It would just provide the functionality of it for when the global option errors. I have decks I can reschedule manually in their entirety from the individual options but yet cannot globally reschedule everything due to errors

**Comment by L-M-Sherlock** [comment]
If the global option raised errors, the best choice is to fix it. I will provide this feature in next version. But I hope you report the errors here.

**Comment by Deminix** [comment]
Awesome. Thanks. Here's the error I'm getting.

Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-12.6.3-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-21 15:53:31
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/cole/Library/Application Support/Anki2/addons21/759844606/__init__.py", line 45, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did))
  File "/Users/cole/Library/Application Support/Anki2/addons21/759844606/__init__.py", line 83, in reschedule_recent
    reschedule(did, recent=True)
  File "/Users/cole/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 153, in reschedule
    for cid in mw.col.find_cards(query):
  File "anki.collection", line 674, in find_cards
  File "anki._backend_generated", line 1522, in search_cards
  File "anki._backend", line 156, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨the escape sequence <code>⁨\o⁩</code> is not defined. If you want to search for a literal backslash <code>\</code>, prepend another one: <code>\\</code>.⁩</p>

**Comment by L-M-Sherlock** [comment]
So weird. I guess it is caused by the invalid deck name. Could you share your screenshot of the Decks with me?

**Comment by Deminix** [comment]
I figured out the issue. One of my decks was named heme\onco with a backslash like that, and that was throwing the error. When I renamed it, everything was fixed. Thanks for the update too. Appreciate it.
