### ISSUE TITLE
Hopefully Support Mobile Anki

### ISSUE THREAD

**Issue by HillCat** [open-spaced-repetition/fsrs4anki-helper#8]
I read the official document, and it said Advanced Scheduling supports Mobile Anki, I want to know if the add-on can support iphone's Anki.
https://faqs.ankiweb.net/the-2021-scheduler.html#add-ons-and-custom-scheduling
![anki_Imu1Da1e2g](https://user-images.githubusercontent.com/41800196/215271227-8e751f7f-9204-4cc3-b843-8e98b6c6f76f.png)

**Comment by L-M-Sherlock** [comment]
FSRS4Anki requires the customData feature which was implemented in Anki 2.1.55. The customData feature hasn't been supported in Mobile Anki.

**Comment by L-M-Sherlock** [comment]
The customData feature is a new part of Advanced Scheduling. It is only supported by Anki PC version.
