### ISSUE TITLE
Disperse siblings info

### ISSUE THREAD

**Issue by Sterling1919** [open-spaced-repetition/fsrs4anki-helper#80]
Hi,
Can you please update the readme to explain how disperse siblings works? I would like to understand how/why it is working, and how it compares to ‘Delay Siblings.’ Also, does it reschedule cards which were automatically buried by Anki? Thanks.

**Comment by L-M-Sherlock** [comment]
I'm busy with another project recently. You can read this before I update the document.

https://github.com/open-spaced-repetition/fsrs4anki/issues/188#issuecomment-1510032739

And the rescheduling affects buried cards.

**Comment by user1823** [comment]
> why it is working

The purpose is the same as that of Delay Siblings. It tries to maximize the delay between the review of siblings.

> how it compares to ‘Delay Siblings.’ 

The main difference is that Delay Siblings only delays the sibling cards (and not the card you just reviewed). On the other hand, Disperse Siblings reschedules all the cards associated with the note.
The details of how the cards are rescheduled such that they are maximally spaced is explained in the comment linked by @L-M-Sherlock above.

Also, Delay Siblings works as soon as you review a card. However, you have to manually disperse siblings with the FSRS Helper. (Though if you do your reviews on another device or on AnkiWeb, you can set it to automatically disperse the siblings in your reviewed cards as the reviews are synced back to Desktop Anki.)

Thirdly, FSRS helper disperses the siblings within the fuzz range calculated from the optimal interval (which is calculated from the stability). However, Delay Siblings just uses the present interval of the card to calculate the fuzz range. So, Delay Siblings can cause fuzz to be applied multiple times to the same card.

> does it reschedule cards which were automatically buried by Anki?

Yes, the Disperse Siblings reschedules the cards that were automatically buried by Anki during review (and also the ones you manually bury).

**Comment by Sterling1919** [comment]
Very helpful. Thank you.

**Comment by Sterling1919** [comment]
Does disperse siblings work for cards with more than 1 sibling?

**Comment by L-M-Sherlock** [comment]
> Does disperse siblings work for cards with more than 1 sibling?

Of cause.
