### ISSUE TITLE
`check_fsrs4anki` can be improved

### ISSUE THREAD

**Issue by kylegoetz** [open-spaced-repetition/fsrs4anki-helper#83]
Right now, the utility function `check_fsrs4anki` takes `all_config` and returns an object that is presumed to be a well-formed representation of a `custom_scheduler`. It also optionally warns the user of malformed data.

It follows this logic:

1. does `all_config` have a property `cardStateCustomizer`? If not, warn user and return `None`
2. does the value at `cardStateCustomizer` have the JavaScript comment "// FSRS4Anki" in it? If not, warn user and return `None`
3. return the value at `cardStateCustomizer`

This presents a couple issues:

1. `cardStateCustomizer` might have the data we need but the user might have deleted the JS comments to make what they pasted easier to read. This leads to a failure case when it could be a success case
2. the value at `cardStateCustomizer` is not actually validated for what is needed.

I notice this function is fed in data from `mw`, which is the same thing used by `Config` to load the plugin's configuration. I propose we create a data type representing well-formed custom scheduler, the `check_fsrs4anki` be moved to the `Config` class, and have it return `Optional[CustomScheduler]`. Or return a nullable `CustomScheduler?` like it basically does now.

IMO it's better for the code to determine right away whether the custom scheduler is well-formed, and then only ever work with that instead of re-validating every time the data is needed.

(As an aside, `reviewer.py` could use this function instead of having the line hard-coded 

>self._state_mutation_js = self.mw.col.get_config("cardStateCustomizer")

`reviewer.py` is missing the checks to make sure the property exists and is well-formed.)

**Comment by kylegoetz** [comment]
I'll start on a PR

**Comment by L-M-Sherlock** [comment]
Do you know how to implement it? Should we introduce a javaScript AST to parse the code? I'm not professional here.

**Comment by L-M-Sherlock** [comment]
FSRS has been integrated into Anki 23.10. The add-on has removed `check_fsrs4anki`.
