### ISSUE TITLE
Postpone and Advance Question

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki-helper#84]
I am a little confused about how the Postpone and Advance features work. Are they similar to "bury" and "learn ahead" but limited to only those cards with a certain retention?

If I choose to postpone cards with retention higher than 90%, how many days into the future will they be rescheduled?
If I choose to advance cards with retention lower than 50%, will it move ALL cards with low retention to be due today or only cards that would have been due tomorrow?

**Comment by L-M-Sherlock** [comment]
> If I choose to postpone cards with retention higher than 90%, how many days into the future will they be rescheduled?

They will be rescheduled to the date when their retention is 90%.

**Comment by user1823** [comment]
> If I choose to advance cards with retention lower than 50%, will it move ALL cards with low retention to be due today or only cards that would have been due tomorrow?

All cards with low retention will be rescheduled, not only those that would have been due tomorrow.

By the way, none of the cards would have retention lower than 50% unless your requestRetention is lower than 0.50 (which is not recommended) or you have a large backlog.
