### ISSUE TITLE
Does this conflict with Anking Weekends and Holidays Addon? 

### ISSUE THREAD

**Issue by ballin4dapandas** [open-spaced-repetition/fsrs4anki-helper#86]
https://www.patreon.com/posts/new-add-on-alpha-58277501

I have been avoiding using this addon because I am worried it will conflict with the FSR scheduling. I work per diem 1x per week and it's on random days of the week, being able to set a "holiday" for FSR to avoid scheduling on those work days (I work 12 hours those days) would be super useful. I tried setting the days I work on a week to week basis but the scheduler's "free Saturday" for example will end up causing me to avoid a completely different day so that hasn't been an option. 

As an enhancement, could you possibly add an avoid holidays function that allows you to set the date. The addon looks like

**Comment by L-M-Sherlock** [comment]
I cannot test the add-on because I doesn't subscribe Anking. Could you test the compatibility?

**Comment by L-M-Sherlock** [comment]
> I tried setting the days I work on a week to week basis but the scheduler's "free Saturday" for example will end up causing me to avoid a completely different day so that hasn't been an option.

Could you describe it in detail? I don't know what's the completely different day you mean.
