### ISSUE TITLE
‘Disperse siblings’ doesn’t respect ‘No Anki on Free Days’

### ISSUE THREAD

**Issue by Sterling1919** [open-spaced-repetition/fsrs4anki-helper#87]
If I have no Anki on Saturday, then reschedule the whole deck, I appropriately get little to no cards due on Saturday. If I then disperse siblings in the deck, many cards are then scheduled for Saturday. Disperse siblings should respect ‘No Anki on Free Days.’

Also, why would anyone want to reschedule the cards and NOT disperse siblings? Seems that these could be combined together in the future. 

<img width="754" alt="19D91547-D6F8-4317-AD9D-6F7AD8447B85" src="https://user-images.githubusercontent.com/128503543/236043206-373f5d4b-1d0d-438c-8215-e37bd775c224.png">
<img width="760" alt="EEBC9440-57CA-4B27-BEFA-B03B027E9FAE" src="https://user-images.githubusercontent.com/128503543/236043210-898d797e-232b-4efb-a71c-34187b6f6522.png">

**Comment by Sterling1919** [comment]
Also, the load balancing is off

**Comment by L-M-Sherlock** [comment]
> Disperse siblings should respect ‘No Anki on Free Days.’

I also want to make it subject to `No Anki on Free Days`. But it is hard to implement and could reduce the performance.

**Comment by L-M-Sherlock** [comment]
> Also, why would anyone want to reschedule the cards and NOT disperse siblings?

It is still an experimental feature.

**Comment by Sterling1919** [comment]
Makes sense. Thank you for all your work on this.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11748132/fsrs4anki-helper.zip)

@Sterling1919, sorry for my late reply. Recently, I have refactored the `Disperse siblings`. In this patch, `Disperse siblings` will consider `No Anki on Free Days`. But it is not perfect. Could you help me test it?
