### ISSUE TITLE
Ability to search for cards by retention, stability, difficulty, etc

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki-helper#88]
It would be nice to be able to search for cards based on the metrics that fsrs assigns. For example a search for fsrs:difficulty>8 would show all the cards that are deemed particularly difficult for the user. Or a search for (fsrs:retention>0.85 fsrs:retention<0.9) would show all the cards that would be due if the user decides to change the desired retention from 0.85 to 0.9 while keeping the "w" parameters the same.

While I am not sure how they did it, the [Ankihub addon](https://ankiweb.net/shared/info/1322529746) has custom search filters similar to this

**Comment by L-M-Sherlock** [comment]
Thanks to your valued suggestion. I'm browsing the code of the Ankihub addon. It's a big project, so I require some time to learn their code.

**Comment by L-M-Sherlock** [comment]
work-in-progress:

![image](https://user-images.githubusercontent.com/32575846/236397926-79160666-da16-4e0e-b90e-9099ca8fa038.png)

**Comment by akavi1** [comment]
Thank you! I just realized the [Advanced Browser addon](https://ankiweb.net/shared/info/874215009) also offers a similar feature that may be easier to implement

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11404648/fsrs4anki-helper.zip)

This patch has implemented DSR columns. The feature of search is still in-progress.

**Comment by akavi1** [comment]
The three columns show up well, but I get this error when trying to sort by any of the fsrs columns:

DbError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"malformed JSON\"))", kind: Other }

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11406532/fsrs4anki-helper.zip)

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/32575846/236468201-8bd3094a-20b0-4197-ad8c-0fd54bf08c2f.png">

Could you test this version?

**Comment by L-M-Sherlock** [comment]
> If you open browser, try to sort by an fsrs coloumn, close browser then open again, the browser will show up empty until you sort by another non-fsrs column
> 
> I clicked on the Retention column header and this popped up

I didn't encounter this problem. Could you share your collection with me to reproduce the bug?

**Comment by akavi1** [comment]
I think there is some issue with sorting by fsrs column and searching using d,s,r at the same time. Individually, I am able to search and sort, but errors arise when I do both together.
If you search for d>3 you get the expected results but cannot then sort by the fsrs columns.
Similarly, if the cards are sorted by one of the fsrs columns, you cannot search for d>3 without first clicking on one of the non-fsrs columns

**Comment by L-M-Sherlock** [comment]
> I think there is some issue with sorting by fsrs column and searching using d,s,r _at the same time_. Individually, I am able to search and sort, but errors arise when I do both together.
> If you search for d>3 you get the expected results but cannot then sort by the fsrs columns.
> Similarly, if the cards are sorted by one of the fsrs columns, you cannot search for d>3 without first clicking on one of the non-fsrs columns

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11411012/fsrs4anki-helper.zip)
I fixed the bug occurred when searching and sorting were applied together. But I cannot reproduce the bug `DbError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("malformed JSON"))", kind: Other }`.

**Comment by akavi1** [comment]
Here is exactly what I did to get the error:
1. open browser
2. right click on column headers and show difficulty column 
3. sort by deck
4. search for rated:2 (you can search for anything)
5. sord by difficulty
6. search for d>4
7. error pops up

not sure if it matters, but the error says:
`DbError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"malformed JSON\"))", kind: Other }` not `Some("malformed JSON"))`

**Comment by L-M-Sherlock** [comment]
> Here is exactly what I did to get the error:

Does it still happen after you update the add-on?

**Comment by akavi1** [comment]
Yes, still happening

**Comment by L-M-Sherlock** [comment]
Weird, I try to follow the steps that you give, but I doesn't meet the error. Could you share more information about the environment?

**Comment by akavi1** [comment]
I'm using the Anking v12 deck. These are the other addons I have
![image](https://user-images.githubusercontent.com/55925875/236624955-8eb7a989-3d53-49be-8f9b-e188e4532939.png)

**Comment by user1823** [comment]
> Here is exactly what I did to get the error:

I followed these steps and I didn't get the error. Probably, this has something to do with one of your add-ons.

To troubleshoot, disable all add-ons except the FSRS helper add-on and restart Anki.

> If the problem goes away when add-ons are disabled, you can narrow down the culprit by disabling one or more add-ons, restarting Anki, and seeing if the problem goes away. If you have lots of them, you can select the top half of your add-ons in the Add-ons screen and disable them. If after restarting Anki, the problem is still there, try the other half instead. Once you’ve found the half that is causing the problem, divide that half into half again, and repeat. You should be able to narrow it down in around ~6 steps that way.
>
> Alternatively, if you don’t need all the add-ons you have installed, you could start by disabling all the ones you don’t need, and seeing if that helps. Repeat the process trying different add-ons, until you discover which one is causing the problem.

Source: https://faqs.ankiweb.net/when-problems-occur.html

**Comment by akavi1** [comment]
The problem is still there even if I disable all my addons except the FSRS helper. Very confused why you guys arent gettign this error

**Comment by user1823** [comment]
Did you restart your Anki after disabling the add-ons? The add-ons remain in effect until Anki is restarted.

If you restarted Anki before checking again, I have no idea what is happening here.

**Comment by L-M-Sherlock** [comment]
If the problem still exists, I need to dive into your collection to find out what's wrong.
