### ISSUE TITLE
Dealing with cards in relearning stages that were rated 'Again' on AnkiDroid

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#90]
I rated a card `Again` on AnkiDroid and then synced my collection to the Desktop. This card was still in its relearning phase at that time. So, it was not rescheduled. When I tried to rate this card on the Desktop, I was shown the following intervals:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/92206575/236454059-9e207134-52c3-49f3-9dc7-04d4fe5998e6.png">

Seeing such large intervals, I didn't rate the card. These large intervals were probably because the stability was still high, and the difficulty was still low (because the card was not rescheduled by the helper). Here is the screenshot of the card info of the card at that time:

<img width="602" alt="Untitled" src="https://user-images.githubusercontent.com/92206575/236454763-309657ef-3e95-46a3-bcd8-bd2f071dc474.png">

Then, I opened AnkiDroid, rated the card and then synced again. Now, the card was rescheduled by the helper because had already left its relearning stage. Here is the screenshot of the card after it was rescheduled.

<img width="593" alt="Untitled" src="https://user-images.githubusercontent.com/92206575/236455890-56d3a2d0-2755-4646-bc91-1d7efec660ad.png">

As is evident, if I had rated the card on the Desktop, the card would have got much larger interval than it got when I rated it on AnkiDroid. This is obviously something not expected to happen.

Now, I don't know any easy solution for this problem. Making the helper reschedule relearning cards would re-introduce the issue 1 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/16. (Absurd intervals and due dates for cards with multi-day relearning steps)

**Comment by L-M-Sherlock** [comment]
> I rated a card `Again` on AnkiDroid and then synced my collection to the Desktop. This card was still in its relearning phase at that time. So, it was not rescheduled. When I tried to rate this card on the Desktop, I was shown the following intervals:
> 
> <img alt="image" width="305" src="https://user-images.githubusercontent.com/92206575/236454059-9e207134-52c3-49f3-9dc7-04d4fe5998e6.png">
> 
> Seeing such large intervals, I didn't rate the card. These large intervals were probably because the stability was still high, and the difficulty was still low (because the card was not rescheduled by the helper). Here is the screenshot of the card info of the card at that time:

It is caused by these codes:

```javascript
  // For learning/relearning cards
} else if (is_learning()) {
  // Init states if the card didn't contain customData
  if (is_empty()) {
    init_states();
  }
  const good_interval = next_interval(customData.good.s);
  const easy_interval = Math.max(next_interval(customData.easy.s * easyBonus), good_interval + 1);
  if (states.good.normal?.review) {
    states.good.normal.review.scheduledDays = good_interval;
  }
  if (states.easy.normal?.review) {
    states.easy.normal.review.scheduledDays = easy_interval;
  }
```
https://github.com/open-spaced-repetition/fsrs4anki/blob/e97e9cbf875367afbcc5d4131e9228aada4dd053/fsrs4anki_scheduler.js#L128-L141

For the relearning cards, the scheduler assumes they were reviewed by FSRS and updated their stability. But for those cards from AnkiDroid, their stability is still not updated. So it induced the large interval.

**Comment by L-M-Sherlock** [comment]
There is only one simple way to solve it except finishing the relearning stages in Ankidroid and rescheduling it in Desktop.

**Comment by user1823** [comment]
> There is only one simple way to solve it except finishing the relearning stages in Ankidroid and rescheduling it in Desktop.

What is that simple way?

**Comment by L-M-Sherlock** [comment]
Sorry for the mistake, `Grammarly` rewrote my sentence in the opposite way.

**Comment by L-M-Sherlock** [comment]
But there is a hard way to solve it, where the rescheduling should be applied to relearning cards. It shouldn't modify their interval but update their memory states stored in custom data.

**Comment by user1823** [comment]
> But there is a hard way to solve it, where the rescheduling should be applied to relearning cards. It shouldn't modify their interval but update their memory states stored in custom data.

This seems to be a good solution for this issue. Also, I don't think that it would be much difficult to implement.

**Comment by L-M-Sherlock** [comment]
> This seems to be a good solution for this issue. Also, I don't think that it would be much difficult to implement.

Because the rescheduling has been complex. I'm afraid that there are some cases I haven't considered.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11522488/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/b773059134fc6c372b96cf0659912f19fa5e3c9e

Could you help me test it?

**Comment by user1823** [comment]
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/b773059134fc6c372b96cf0659912f19fa5e3c9e/reschedule.py#L208

Shouldn't this be `revlog.review_kind in (REVLOG_LRN, REVLOG_RELRN)` instead of `not in`?

**Comment by L-M-Sherlock** [comment]
> Shouldn't this be `revlog.review_kind in (REVLOG_LRN, REVLOG_RELRN)` instead of `not in`?

Thanks for your review, I fix it.

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11522585/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/b2519cce3618c81cb16e42772c37eb41de16a2dd

**Comment by user1823** [comment]
This patch works as intended. Thanks.
