### ISSUE TITLE
search prop:lapses does not work

### ISSUE THREAD

**Issue by StefanVukovic99** [open-spaced-repetition/fsrs4anki-helper#93]
In Browse window, searching with card property 'lapses' (prop:lapses>3) does not work.

Error: Invalid search: ⁨⁨prop:⁩ was given an invalid argument '⁨lapse⁩'. "⁩

 - Anki version: Version ⁨2.1.56 (07fd88dd)⁩ Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
 - OS: Windows

When this add-on is disabled the search works normally.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11421923/fsrs4anki-helper.zip)

**Comment by StefanVukovic99** [comment]
Works now, thanks!
