### ISSUE TITLE
Question: Optimize whole collection or each deck?

### ISSUE THREAD

**Issue by akavi1** [open-spaced-repetition/fsrs4anki-helper#95]
Is it better to 
1) optimize using the whole collection and have one set of parameters for everything OR 
2) optimize and create a different set of parameters for each deck

I understand option 2 would probably take a significantly longer time to do, but assuming time isn't an issue, which would be better? All the cards in my collections are the same in terms of the amount of information on the card, options for the deck, note type. The decks are organized by subject.

I was thinking if #91 is implemented, then it would be significantly easier to optimize each deck individually.

**Comment by L-M-Sherlock** [comment]
If the materials are significantly different among your decks, I recommend optimizing different parameters for each deck.
