### ISSUE TITLE
FSRS stats don't include cards in filtered decks

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#98]
When seeing the FSRS stats of the parent deck, the cards that are currently in filtered decks are not considered in the Stats. This behavior is inconsistent with the default Anki behavior where all the cards (whether filtered or not) are included in the stats of the parent deck.

**Comment by L-M-Sherlock** [comment]
> This behavior is inconsistent with the default Anki behavior where all the cards (whether filtered or not) are included in the stats of the parent deck.

I think the default anki behavior is the filtered cards are excluded in the stats of the parent deck.

Before creating filtered deck:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/602d7acb-b194-4ad2-a1b1-8ab30e07a476)

After creating filtered deck:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/38ffd36a-9c4e-435a-97b6-de8886b197a2)

The number of total cards decreased.

**Comment by user1823** [comment]
> I think the default anki behavior is the filtered cards are excluded in the stats of the parent deck.

This is not the case with me, at least for the new statistics page.

I can't check the old statistics page now because I am not currently on my computer.

**Comment by L-M-Sherlock** [comment]
> If it is possible to include the filtered cards in the FSRS Stats, I would suggest to include them. The reason is that most users mainly use the new statistics page and are, thus, accustomed to the behaviour of the new statistics page. Any deviation from that behaviour feels like a bug.

It is impossible. Because Anki didn't maintain the old stats since 2.1.33. And I implemented the FSRS stats based on the feature provided by Anki. It required the old stats feature to update, which is impossible.

**Comment by user1823** [comment]
> It is impossible. Because Anki didn't maintain the old stats since 2.1.33. And I implemented the FSRS stats based on the feature provided by Anki. It required the old stats feature to update, which is impossible.

I understand that it is not possible for add-ons to modify the new stats page.

But, is it possible that the add-on imports stats from the new stats page and then inserts the FSRS Stats in the old stats page?

**Comment by L-M-Sherlock** [comment]
> But, is it possible that the add-on imports stats from the new stats page and then inserts the FSRS Stats in the old stats page?

It is impossible because the new stats page is implemented in Rust instead of Python.
